const $=id=>document.getElementById(id),video=$('camera'),canvas=$('fx'),ctx=canvas.getContext('2d',{alpha:true}),sourceLayer=$('overlaySources');
const state={running:false,w:innerWidth,h:innerHeight,t:0,freq:0,db:-100,audioAmp:0,lum:0,brightRegions:[],heading:null,alpha:null,beta:null,gamma:null,acc:0,rot:0,lat:null,lon:null,gpsAccuracy:null,mode:'all',showSources:true,scan:null,wizardStep:0,scanning:false,scanStart:0,samples:[],lastLightSample:0,lastAudioSample:0,temperatureC:null,temperatureSource:null,temperatureUpdatedAt:null,temperatureStatus:'NO SENSOR',tempDevice:null};
let audioCtx,analyser,freqData,timeData,gpsWatch=null,scanRAF=0;
const sampleCanvas=document.createElement('canvas');sampleCanvas.width=80;sampleCanvas.height=54;const sctx=sampleCanvas.getContext('2d',{willReadFrequently:true});
const FOV=64,SCAN_KEY='spectralSpatialScanV3';
const steps=[
 {key:'prepare',icon:'◎',title:'Preparación espacial',desc:'El wizard creará una referencia del entorno. Mantén el teléfono aproximadamente a la altura del pecho y evita cubrir micrófonos o cámara.',seconds:0,instructions:['Permite cámara, micrófono, movimiento y orientación.','Para mejores resultados aléjate de paredes durante el barrido.','Las posiciones de sonido serán estimadas; las regiones luminosas sí se detectan visualmente.']},
 {key:'sound',icon:'◖)))',title:'Barrido de fuentes de sonido',desc:'Gira lentamente 360° sobre tu eje. Relacionaremos nivel, frecuencia dominante y rumbo para encontrar máximos acústicos.',seconds:14,instructions:['Haz una vuelta lenta y continua.','No hables durante el barrido si quieres localizar fuentes ambientales.','El teléfono tiene acceso web limitado a micrófonos; la dirección será una estimación por barrido.']},
 {key:'light',icon:'✦',title:'Barrido de fuentes de luz',desc:'Vuelve a girar lentamente. La cámara analizará regiones brillantes y asociará cada una con su rumbo aproximado.',seconds:14,instructions:['Mantén las luces dentro de la cámara al recorrer el espacio.','No apuntes directamente al sol.','Detectaremos fuentes primarias y consolidaremos observaciones repetidas.']},
 {key:'motion',icon:'⌁',title:'Calibración de movimiento',desc:'Mantén el teléfono quieto unos segundos. Esto crea una referencia para separar movimiento del dispositivo de cambios del entorno.',seconds:5,instructions:['Sujeta el teléfono lo más estable posible.','La calibración guarda aceleración y rotación de referencia.']},
 {key:'environment',icon:'⌾',title:'Entorno y sensores',desc:'Haremos una lectura corta de contexto: GPS, brújula, orientación y capacidades que el navegador realmente puede exponer.',seconds:4,instructions:['Mantén el teléfono estable y deja la cámara apuntando al frente.','GPS y brújula pueden tardar unos segundos en estabilizarse.','Wi‑Fi GHz, RF y Bluetooth de bajo nivel no se inventan: si iOS no los expone, se marcarán como no disponibles.']},
 {key:'temperature',icon:'♨',title:'Temperatura ambiental',desc:'Comprobaremos si existe una fuente de temperatura real conectada. En Safari del iPhone no se inventan °C: sin sensor externo o puente nativo se mostrará como no disponible.',seconds:3,instructions:['Si ya hay un sensor externo conectado, mantén el teléfono cerca de la zona a medir.','La temperatura de color de las luces (K) es distinta de la temperatura ambiental (°C).','En navegadores con Web Bluetooth compatible puedes conectar un sensor Environmental Sensing; en iPhone Safari se requiere puente nativo o hardware con otra vía de datos.']},
 {key:'summary',icon:'◇',title:'Mapa listo',desc:'La calibración terminó. El visor combinará las mediciones actuales con las fuentes y referencias recopiladas.',seconds:0,instructions:[]}
];
function txt(id,v){const e=$(id);if(e)e.textContent=v}function clamp(v,a,b){return Math.min(b,Math.max(a,v))}function norm360(v){return (v%360+360)%360}function angleDiff(a,b){return ((a-b+540)%360)-180}function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}function median(a){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2}function cardinal(d){return ['N','NE','E','SE','S','SO','O','NO'][Math.round(norm360(d)/45)%8]}
function notify(m,ms=5000){const n=$('notice');n.textContent=m;n.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>n.classList.remove('show'),ms)}
function resize(){const dpr=Math.min(devicePixelRatio||1,2);state.w=innerWidth;state.h=innerHeight;canvas.width=state.w*dpr;canvas.height=state.h*dpr;canvas.style.width=state.w+'px';canvas.style.height=state.h+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();

function cctLabel(k){if(!isFinite(k)||k<=0)return '—';if(k<3000)return 'Cálida';if(k<4000)return 'Cálida-neutra';if(k<5000)return 'Neutra';if(k<6500)return 'Fría / daylight';return 'Muy fría'}
function sourceLightScore(stability,uniformity,glare,modulation){const glareScore=100-clamp(glare||0,0,100),modScore=100-clamp(modulation||0,0,100);return clamp(Math.round((stability||0)*.32+(uniformity||0)*.28+glareScore*.20+modScore*.20),0,100)}
