async function startAll(){if(!isSecureContext)notify('Necesitas HTTPS para cámara, micrófono y sensores.',9000);const sp=requestMotionOrientation();try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});video.srcObject=stream;await video.play();setupAudio(stream)}catch(e){notify('No pude abrir cámara/micrófono: '+e.message,9000);return}await sp;setupGeo();state.running=true;$('gate').style.display='none';$('liveDot').classList.add('on');txt('status','LIVE');loadScan();requestAnimationFrame(loop);openWizard(0)}
async function requestMotionOrientation(){try{if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function')await DeviceMotionEvent.requestPermission();if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){try{await DeviceOrientationEvent.requestPermission(true)}catch(_){await DeviceOrientationEvent.requestPermission()}}}catch(e){notify('Sensores de orientación no autorizados; el barrido espacial tendrá menor precisión.')}addEventListener('devicemotion',onMotion,{passive:true});addEventListener('deviceorientation',onOrientation,{passive:true});addEventListener('deviceorientationabsolute',onOrientation,{passive:true})}
function onMotion(e){const a=e.acceleration||e.accelerationIncludingGravity;if(a){const x=a.x||0,y=a.y||0,z=a.z||0;state.acc=Math.sqrt(x*x+y*y+z*z);txt('acc',state.acc.toFixed(2));}const r=e.rotationRate;if(r){const x=r.alpha||0,y=r.beta||0,z=r.gamma||0;state.rot=Math.sqrt(x*x+y*y+z*z);txt('rot',state.rot.toFixed(1))}}
function onOrientation(e){state.alpha=e.alpha;state.beta=e.beta;state.gamma=e.gamma;let h=null;if(typeof e.webkitCompassHeading==='number')h=e.webkitCompassHeading;else if(e.absolute&&typeof e.alpha==='number')h=norm360(360-e.alpha);if(h!=null){state.heading=h;txt('heading',Math.round(h)+'°');txt('headingLabel',cardinal(h)+' · '+(e.webkitCompassHeading!=null||e.absolute?'medido':'estimado'))}}
function setupAudio(stream){audioCtx=new(window.AudioContext||window.webkitAudioContext)();const src=audioCtx.createMediaStreamSource(stream);analyser=audioCtx.createAnalyser();analyser.fftSize=4096;analyser.smoothingTimeConstant=.62;src.connect(analyser);freqData=new Uint8Array(analyser.frequencyBinCount);timeData=new Uint8Array(analyser.fftSize)}
function analyseAudio(){if(!analyser)return;analyser.getByteFrequencyData(freqData);analyser.getByteTimeDomainData(timeData);let max=0,idx=0;for(let i=2;i<freqData.length;i++){if(freqData[i]>max){max=freqData[i];idx=i}}state.freq=idx*audioCtx.sampleRate/analyser.fftSize;let sum=0;for(const v of timeData){const n=(v-128)/128;sum+=n*n}const rms=Math.sqrt(sum/timeData.length);state.audioAmp=rms;state.db=20*Math.log10(Math.max(rms,1e-6));txt('freq',state.freq>25?Math.round(state.freq)+' Hz':'— Hz');txt('db',state.db.toFixed(1)+' dBFS');txt('note',state.freq>25?audioLabel(state.freq)+' · medido':'medido')}
function audioLabel(f){if(f<90)return'grave / hum';if(f<280)return'mecánico probable';if(f<3400)return'banda voz/ambiente';if(f<8000)return'agudo';return'alta frecuencia'}
function analyseLight(now){if(!video.videoWidth||now-state.lastLightSample<95)return;state.lastLightSample=now;try{sctx.drawImage(video,0,0,sampleCanvas.width,sampleCanvas.height);const im=sctx.getImageData(0,0,sampleCanvas.width,sampleCanvas.height),d=im.data;let sum=0;const vals=[];for(let y=0;y<sampleCanvas.height;y+=3){for(let x=0;x<sampleCanvas.width;x+=3){const i=(y*sampleCanvas.width+x)*4,l=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2];sum+=l;vals.push({x,y,l})}}state.lum=100*sum/(vals.length*255);txt('lum',state.lum.toFixed(1)+'%');const sorted=vals.map(v=>v.l).sort((a,b)=>a-b),p90=sorted[Math.floor(sorted.length*.90)]||220,threshold=Math.max(170,p90*1.08);const candidates=vals.filter(v=>v.l>=threshold).sort((a,b)=>b.l-a.l),picked=[];for(const c of candidates){if(picked.every(p=>Math.hypot(c.x-p.x,c.y-p.y)>10)){picked.push(c);if(picked.length>=4)break}}state.brightRegions=picked.map(p=>({x:p.x/sampleCanvas.width,y:p.y/sampleCanvas.height,intensity:p.l/255}));txt('brightNow',String(state.brightRegions.length))}catch(_){}}
function setupGeo(){if(!navigator.geolocation)return;gpsWatch=navigator.geolocation.watchPosition(p=>{state.lat=p.coords.latitude;state.lon=p.coords.longitude;state.gpsAccuracy=p.coords.accuracy;txt('gps',p.coords.latitude.toFixed(4)+','+p.coords.longitude.toFixed(4));txt('gpsAcc','±'+Math.round(p.coords.accuracy)+' m')},()=>txt('gps','sin permiso'),{enableHighAccuracy:true,maximumAge:5000,timeout:10000})}
function loadScan(){try{const s=JSON.parse(localStorage.getItem(SCAN_KEY)||'null');if(s&&s.version===2){state.scan=s;updateScanUI()}}catch(_){}}
function saveScan(){if(!state.scan)return;localStorage.setItem(SCAN_KEY,JSON.stringify(state.scan));updateScanUI()}
function updateScanUI(){const s=state.scan;if(!s){txt('soundSources','0');txt('lightSources','0');txt('scanAge','—');txt('quality','—');return}txt('soundSources',String(s.soundSources?.length||0));txt('lightSources',String(s.lightSources?.length||0));const mins=Math.max(0,Math.round((Date.now()-s.createdAt)/60000));txt('scanAge',mins<1?'ahora':mins<60?mins+' min':Math.round(mins/60)+' h');txt('quality',(s.quality||0)+'%')}
