function openWizard(step=0){state.wizardStep=step;state.scanning=false;state.samples=[];$('wizard').style.display='block';renderWizard()}
function renderWizard(){const s=steps[state.wizardStep];txt('stepLabel','PASO '+(state.wizardStep+1)+'/'+steps.length);$('wizardProgress').style.width=((state.wizardStep)/(steps.length-1)*100)+'%';txt('stepIcon',s.icon);txt('stepTitle',s.title);txt('stepDesc',s.desc);$('instructions').innerHTML=s.instructions.map((x,i)=>'<div class="instruction"><b>'+String(i+1).padStart(2,'0')+'</b><span>'+x+'</span></div>').join('');$('scanBar').style.width='0%';txt('wsSamples','0');txt('wsHeading',state.heading==null?'—':Math.round(state.heading)+'°');txt('wsReading','—');$('summaryGrid').style.display=s.key==='summary'?'grid':'none';$('scanMeter').style.display=s.key==='summary'?'none':'block';$('wizBack').disabled=state.wizardStep===0||state.scanning;$('wizSkip').style.display=(s.key==='summary'||s.key==='prepare')?'none':'block';$('wizAction').textContent=s.key==='summary'?'ABRIR VISOR':s.key==='prepare'?'COMENZAR CALIBRACIÓN':'INICIAR ESCANEO';if(s.key==='summary')renderSummary();else{txt('scanBig',s.key==='prepare'?'LISTO':'PENDIENTE');txt('scanSmall',s.key==='prepare'?'Revisa las instrucciones y continúa.':'Pulsa iniciar cuando estés preparado.')}}
function renderSummary(){const s=state.scan||finalizeAll();const sensorCount=(s.environment?.headingAvailable?1:0)+(s.environment?.gpsAvailable?1:0)+(analyser?1:0)+(video.videoWidth?1:0);const items=[['FUENTES SONIDO',(s.soundSources||[]).length],['FUENTES LUZ',(s.lightSources||[]).length],['BASE AUDIO',(s.baselineDb??-100).toFixed(1)+' dB'],['BASE LUZ',(s.baselineLum??0).toFixed(1)+'%'],['COBERTURA',s.coverage+'°'],['SENSORES',sensorCount+'/4'],['GPS',s.environment?.gpsAccuracy?'±'+Math.round(s.environment.gpsAccuracy)+' m':'—'],['CALIDAD',s.quality+'%']];$('summaryGrid').innerHTML=items.map(x=>'<div class="summaryItem"><b>'+x[0]+'</b><strong>'+x[1]+'</strong></div>').join('')}
function beginStepScan(){const s=steps[state.wizardStep];if(!s.seconds){if(s.key==='prepare'){state.wizardStep++;renderWizard()}return}state.scanning=true;state.samples=[];state.scanStart=performance.now();$('wizAction').disabled=true;$('wizBack').disabled=true;$('wizSkip').disabled=true;txt('scanBig','ESCANEANDO');scanRAF=requestAnimationFrame(scanTick)}
function scanTick(now){if(!state.scanning)return;const s=steps[state.wizardStep],elapsed=(now-state.scanStart)/1000,p=clamp(elapsed/s.seconds,0,1);$('scanBar').style.width=(p*100)+'%';txt('scanSmall',Math.max(0,s.seconds-elapsed).toFixed(1)+' s restantes · gira lentamente');txt('wsHeading',state.heading==null?'—':Math.round(state.heading)+'° '+cardinal(state.heading));if(s.key==='sound'){txt('wsReading',state.db.toFixed(1)+' dB');if(now-state.lastAudioSample>110){state.lastAudioSample=now;state.samples.push({h:state.heading,db:state.db,f:state.freq,t:Date.now()})}}else if(s.key==='light'){txt('wsReading',state.lum.toFixed(1)+'% · '+state.brightRegions.length+' src');for(const r of state.brightRegions){const bearing=state.heading==null?null:norm360(state.heading+(r.x-.5)*FOV);state.samples.push({h:state.heading,b:bearing,x:r.x,y:r.y,i:r.intensity,lum:state.lum,t:Date.now()})}}else if(s.key==='motion'){txt('wsReading',state.acc.toFixed(2)+' m/s²');state.samples.push({a:state.acc,r:state.rot,t:Date.now()})}else if(s.key==='environment'){const g=state.gpsAccuracy==null?'GPS —':'GPS ±'+Math.round(state.gpsAccuracy)+'m';txt('wsReading',(state.heading==null?'HDG —':'HDG '+Math.round(state.heading)+'°')+' · '+g);state.samples.push({h:state.heading,lat:state.lat,lon:state.lon,gps:state.gpsAccuracy,t:Date.now()})}txt('wsSamples',String(state.samples.length));if(p>=1){finishStepScan(s.key);return}scanRAF=requestAnimationFrame(scanTick)}
function finishStepScan(key){state.scanning=false;cancelAnimationFrame(scanRAF);if(!state.scan)state.scan={version:2,createdAt:Date.now(),soundSources:[],lightSources:[],parts:{}};state.scan.parts[key]=state.samples.slice();if(key==='sound')processSoundScan(state.samples);if(key==='light')processLightScan(state.samples);if(key==='motion')processMotionScan(state.samples);if(key==='environment')processEnvironmentScan(state.samples);txt('scanBig','COMPLETO');txt('scanSmall','Datos procesados. Puedes continuar.');$('wizAction').disabled=false;$('wizAction').textContent='CONTINUAR';$('wizBack').disabled=false;$('wizSkip').disabled=false;$('wizAction').dataset.done='1';saveScan()}
function processSoundScan(samples){const valid=samples.filter(x=>x.h!=null&&isFinite(x.db));const levels=valid.map(x=>x.db),base=levels.length?median(levels):-70;state.scan.baselineDb=base;const bins=[];for(let b=0;b<360;b+=15){const arr=valid.filter(x=>Math.abs(angleDiff(x.h,b))<=10);if(arr.length)bins.push({b,db:avg(arr.map(x=>x.db)),f:median(arr.map(x=>x.f).filter(f=>f>25))})}bins.sort((a,b)=>b.db-a.db);const sources=[];for(const x of bins){if(sources.every(s=>Math.abs(angleDiff(s.bearing,x.b))>35)&&x.db>base+1){sources.push({id:'S'+(sources.length+1),bearing:x.b,db:x.db,f:x.f,confidence:clamp(Math.round(55+(x.db-base)*7),55,94),kind:audioLabel(x.f)});if(sources.length>=4)break}}state.scan.soundSources=sources;state.scan.soundCoverage=coverageFromHeadings(valid.map(x=>x.h))}
function processLightScan(samples){const valid=samples.filter(x=>x.b!=null&&x.i>.67);state.scan.baselineLum=median(samples.map(x=>x.lum).filter(Number.isFinite));const clusters=[];for(const p of valid.sort((a,b)=>b.i-a.i)){let c=clusters.find(c=>Math.abs(angleDiff(c.bearing,p.b))<16);if(!c){c={bearing:p.b,vals:[],xs:[],bearings:[]};clusters.push(c)}c.vals.push(p.i);c.xs.push(p.x);c.bearings.push(p.b);c.bearing=circularMean(c.bearings)??c.bearing}clusters.sort((a,b)=>Math.max(...b.vals)-Math.max(...a.vals));state.scan.lightSources=clusters.slice(0,6).map((c,i)=>({id:'L'+(i+1),bearing:c.bearing,intensity:Math.max(...c.vals),confidence:clamp(Math.round(60+c.vals.length*2+Math.max(...c.vals)*18),62,97)}));state.scan.lightCoverage=coverageFromHeadings(samples.map(x=>x.h).filter(x=>x!=null))}
function circularMean(deg){if(!deg.length)return null;let s=0,c=0;for(const d of deg){s+=Math.sin(d*Math.PI/180);c+=Math.cos(d*Math.PI/180)}return norm360(Math.atan2(s,c)*180/Math.PI)}
function processMotionScan(samples){state.scan.baselineAcc=median(samples.map(x=>x.a));state.scan.baselineRot=median(samples.map(x=>x.r));}
function processEnvironmentScan(samples){const gps=samples.map(x=>x.gps).filter(x=>x!=null&&isFinite(x));state.scan.environment={headingAvailable:samples.some(x=>x.h!=null),gpsAvailable:gps.length>0,gpsAccuracy:gps.length?median(gps):null,network:(navigator.connection&&navigator.connection.effectiveType)||'browser-limited',bluetooth:!!navigator.bluetooth};}
function coverageFromHeadings(hs){if(!hs.length)return 0;const bins=new Set(hs.map(h=>Math.floor(norm360(h)/15)));return Math.round(bins.size*15)}
function finalizeAll(){if(!state.scan)state.scan={version:2,createdAt:Date.now(),soundSources:[],lightSources:[],parts:{}};const cov=Math.max(state.scan.soundCoverage||0,state.scan.lightCoverage||0);state.scan.coverage=Math.min(360,cov);state.scan.quality=clamp(Math.round(35+state.scan.coverage/360*45+Math.min(20,(state.scan.soundSources.length+state.scan.lightSources.length)*3)),35,100);state.scan.createdAt=Date.now();saveScan();return state.scan}
function advanceWizard(){const s=steps[state.wizardStep];if(s.key==='summary'){$('wizard').style.display='none';finalizeAll();return}if($('wizAction').dataset.done==='1'){delete $('wizAction').dataset.done;state.wizardStep=Math.min(steps.length-1,state.wizardStep+1);if(state.wizardStep===steps.length-1)finalizeAll();renderWizard();return}beginStepScan()}
function skipStep(){if(state.scanning)return;state.wizardStep=Math.min(steps.length-1,state.wizardStep+1);if(state.wizardStep===steps.length-1)finalizeAll();renderWizard()}
function goBack(){if(state.scanning||state.wizardStep===0)return;state.wizardStep--;renderWizard()}
