const EXP=new Uint8Array(512),LOG=new Uint8Array(256);let x=1;for(let i=0;i<255;i++){EXP[i]=x;LOG[x]=i;x<<=1;if(x&0x100)x^=0x11d;}for(let i=255;i<512;i++)EXP[i]=EXP[i-255];
export const gf={add:(a,b)=>a^b,mul:(a,b)=>(a===0||b===0)?0:EXP[LOG[a]+LOG[b]],inv:a=>{if(!a)throw new Error('GF inverse of zero');return EXP[255-LOG[a]];},pow:(a,n)=>a===0?0:EXP[(LOG[a]*n)%255]};
function ident(n){return Array.from({length:n},(_,r)=>Uint8Array.from({length:n},(_,c)=>r===c?1:0));}
export function invertMatrix(input){const n=input.length,A=input.map(r=>Uint8Array.from(r)),I=ident(n);for(let c=0;c<n;c++){let p=c;while(p<n&&A[p][c]===0)p++;if(p===n)throw new Error('Singular GF matrix');if(p!==c){[A[p],A[c]]=[A[c],A[p]];[I[p],I[c]]=[I[c],I[p]];}const inv=gf.inv(A[c][c]);for(let j=0;j<n;j++){A[c][j]=gf.mul(A[c][j],inv);I[c][j]=gf.mul(I[c][j],inv);}for(let r=0;r<n;r++){if(r===c)continue;const f=A[r][c];if(!f)continue;for(let j=0;j<n;j++){A[r][j]^=gf.mul(f,A[c][j]);I[r][j]^=gf.mul(f,I[c][j]);}}}return I;}
function multiply(A,B){const rows=A.length,mid=B.length,cols=B[0].length,out=Array.from({length:rows},()=>new Uint8Array(cols));for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){let v=0;for(let k=0;k<mid;k++)v^=gf.mul(A[r][k],B[k][c]);out[r][c]=v;}return out;}
const cache=new Map();
export function generatorMatrix(k,r){const key=`${k}:${r}`;if(cache.has(key))return cache.get(key);const n=k+r,V=Array.from({length:n},(_,row)=>{const a=row+1;return Uint8Array.from({length:k},(_,col)=>col===0?1:gf.pow(a,col));});const topInv=invertMatrix(V.slice(0,k));const G=multiply(V,topInv);cache.set(key,G);return G;}
export function encodeParity(dataBlocks,r){const k=dataBlocks.length;if(!k||!r)return[];const len=dataBlocks[0].length,G=generatorMatrix(k,r),out=[];for(let p=0;p<r;p++){const row=G[k+p],par=new Uint8Array(len);for(let i=0;i<k;i++){const coef=row[i];if(!coef)continue;const src=dataBlocks[i];for(let j=0;j<len;j++)par[j]^=gf.mul(coef,src[j]);}out.push(par);}return out;}
export function recoverData(received,k,r,blockLen){const G=generatorMatrix(k,r);const available=[...received.entries()].filter(([,b])=>b).slice(0,k);if(available.length<k)throw new Error('Not enough blocks for FEC recovery');const rows=available.map(([slot])=>G[slot]),inv=invertMatrix(rows),src=available.map(([,b])=>b),out=Array.from({length:k},()=>new Uint8Array(blockLen));for(let d=0;d<k;d++)for(let s=0;s<k;s++){const coef=inv[d][s];if(!coef)continue;for(let j=0;j<blockLen;j++)out[d][j]^=gf.mul(coef,src[s][j]);}return out;}
