import { crc32 } from './crc32.js';
export const PROFILES={robust:{id:1,name:'Robusto',bits:2,k:6,r:3,efficiency:.62},balanced:{id:2,name:'Balanceado',bits:3,k:8,r:2,efficiency:.73},turbo:{id:3,name:'Turbo',bits:4,k:10,r:2,efficiency:.78}};
const ANCHORS=['#ff20d6','#00efff','#ffe12b','#34ff73'];
const PALETTES={2:['#151921','#f4f7ff','#00d6ff','#ff2ec8'],3:['#171a20','#f5f7ff','#ff3b3b','#38ef73','#3187ff','#ffe02d','#ff39d4','#35f0e5'],4:['#11151d','#f8f9ff','#ff334f','#32ef72','#3388ff','#ffe139','#ff3bd7','#35e9e2','#ff8a2e','#834dff','#72ff31','#ff6fae','#2ecbff','#b8ff55','#ffd0f2','#7f94a8']};
function parseHex(h){const n=parseInt(h.slice(1),16);return[(n>>16)&255,(n>>8)&255,n&255];}
export function getPalette(bits){return PALETTES[bits].map(parseHex);}
export function chooseProfile(mode){if(mode==='robust'||mode==='balanced'||mode==='turbo')return {...PROFILES[mode],key:mode};return {...PROFILES.balanced,key:'balanced'};}
export function gridSpec(grid,bits){const [cols,rows]=grid.split('x').map(Number),anchor=6,border=2,headerRows=6,calRows=2;const innerCols=cols-border*2,innerRows=rows-border*2;const payloadRows=innerRows-headerRows-calRows;const headerCells=innerCols*headerRows;const payloadCells=innerCols*payloadRows;const payloadBytes=Math.floor(payloadCells*bits/8)-24;return{cols,rows,anchor,border,headerRows,calRows,innerCols,innerRows,payloadRows,headerCells,payloadCells,payloadBytes:Math.max(64,payloadBytes)};}
export function resolveProfile(mode,grid){const p=chooseProfile(mode),spec=gridSpec(grid,p.bits);return {...p,...spec,payloadBytes:spec.payloadBytes};}
function writeU32(a,o,v){new DataView(a.buffer).setUint32(o,v>>>0);}function writeU16(a,o,v){new DataView(a.buffer).setUint16(o,v&65535);}
export function buildHeader(frame,transport,profile,seq,total){const h=new Uint8Array(28);h.set([0x48,0x58,0x32,0x46],0);h[4]=2;h[5]=profile.id;h[6]=profile.bits;h[7]=frame.kind;writeU32(h,8,seq);writeU32(h,12,total);writeU16(h,16,frame.group);h[18]=frame.slot;h[19]=transport.k;h[20]=transport.r;writeU32(h,21,transport.streamLength);writeU16(h,25,frame.payload.length);h[27]=crc32(frame.payload)&0xff;return h;}
function bytesToBits(bytes){const bits=[];for(const b of bytes)for(let i=7;i>=0;i--)bits.push((b>>i)&1);return bits;}
function symbolValues(bytes,bitsPer){const out=[];let buf=0,n=0;for(const b of bytes){buf=(buf<<8)|b;n+=8;while(n>=bitsPer){n-=bitsPer;out.push((buf>>n)&((1<<bitsPer)-1));buf&=(1<<n)-1;}}if(n)out.push((buf<<(bitsPer-n))&((1<<bitsPer)-1));return out;}
export function renderOpticalFrame(canvas,frame,transport,profile,seq,total){const ctx=canvas.getContext('2d',{alpha:false}),{cols,rows,border,headerRows,calRows}=profile;canvas.width=cols*10;canvas.height=rows*10;const cw=canvas.width/cols,ch=canvas.height/rows;ctx.fillStyle='#05070a';ctx.fillRect(0,0,canvas.width,canvas.height);const cell=(x,y,c)=>{ctx.fillStyle=c;ctx.fillRect(Math.floor(x*cw),Math.floor(y*ch),Math.ceil(cw+1),Math.ceil(ch+1));};for(let x=0;x<cols;x++){cell(x,0,'#ffffff');cell(x,rows-1,'#ffffff');}for(let y=0;y<rows;y++){cell(0,y,'#ffffff');cell(cols-1,y,'#ffffff');}const a=profile.anchor;for(let yy=1;yy<1+a;yy++)for(let xx=1;xx<1+a;xx++)cell(xx,yy,ANCHORS[0]);for(let yy=1;yy<1+a;yy++)for(let xx=cols-1-a;xx<cols-1;xx++)cell(xx,yy,ANCHORS[1]);for(let yy=rows-1-a;yy<rows-1;yy++)for(let xx=cols-1-a;xx<cols-1;xx++)cell(xx,yy,ANCHORS[2]);for(let yy=rows-1-a;yy<rows-1;yy++)for(let xx=1;xx<1+a;xx++)cell(xx,yy,ANCHORS[3]);const header=buildHeader(frame,transport,profile,seq,total),hb=bytesToBits(header);let hi=0;for(let y=border;y<border+headerRows;y++)for(let x=border;x<cols-border;x++){const bit=hb[hi%hb.length];cell(x,y,bit?'#f7f9ff':'#090b0f');hi++;}const palette=PALETTES[profile.bits];const calY=border+headerRows;for(let y=calY;y<calY+calRows;y++)for(let x=border;x<cols-border;x++)cell(x,y,palette[(x-border)%palette.length]);const vals=symbolValues(frame.payload,profile.bits);let vi=0;for(let y=calY+calRows;y<rows-border;y++)for(let x=border;x<cols-border;x++){cell(x,y,palette[vals[vi%vals.length]]);vi++;}return {header,payloadCrc:crc32(frame.payload)};}
export function nearestPalette(rgb,palette){let best=0,bd=Infinity;for(let i=0;i<palette.length;i++){const p=palette[i],d=(rgb[0]-p[0])**2+(rgb[1]-p[1])**2+(rgb[2]-p[2])**2;if(d<bd){bd=d;best=i;}}return best;}
