import { recoverData } from './gf256.js';
import { restoreFile } from './superstream.js';
import { crc32 } from './crc32.js';
import { GRIDS,gridSpec,getPalette,nearestPalette } from './optical.js';

function readU32(a,o){return new DataView(a.buffer,a.byteOffset,a.byteLength).getUint32(o);}function readU16(a,o){return new DataView(a.buffer,a.byteOffset,a.byteLength).getUint16(o);}
function bitsToBytes(bits,count){const out=new Uint8Array(count);for(let i=0;i<count*8;i++)out[i>>3]|=(bits[i]&1)<<(7-(i&7));return out;}
function symbolsToBytes(symbols,bitsPer,count){const out=new Uint8Array(count);let acc=0,n=0,oi=0;for(const s of symbols){acc=(acc<<bitsPer)|s;n+=bitsPer;while(n>=8&&oi<count){n-=8;out[oi++]=(acc>>n)&255;acc&=(1<<n)-1;}if(oi>=count)break;}return out;}
function squareHomography(p0,p1,p2,p3){const dx1=p1.x-p2.x,dx2=p3.x-p2.x,dx3=p0.x-p1.x+p2.x-p3.x,dy1=p1.y-p2.y,dy2=p3.y-p2.y,dy3=p0.y-p1.y+p2.y-p3.y;let g=0,h=0;const det=dx1*dy2-dx2*dy1;if(Math.abs(dx3)>1e-6||Math.abs(dy3)>1e-6){if(Math.abs(det)<1e-9)return null;g=(dx3*dy2-dx2*dy3)/det;h=(dx1*dy3-dx3*dy1)/det;}const a=p1.x-p0.x+g*p1.x,b=p3.x-p0.x+h*p3.x,c=p0.x,d=p1.y-p0.y+g*p1.y,e=p3.y-p0.y+h*p3.y,f=p0.y;return(u,v)=>{const z=g*u+h*v+1;return{x:(a*u+b*v+c)/z,y:(d*u+e*v+f)/z};};}
function sampleRGB(data,W,H,x,y,r=1){let R=0,G=0,B=0,n=0;const cx=Math.round(x),cy=Math.round(y);for(let yy=cy-r;yy<=cy+r;yy++)for(let xx=cx-r;xx<=cx+r;xx++){if(xx<0||yy<0||xx>=W||yy>=H)continue;const o=(yy*W+xx)*4;R+=data[o];G+=data[o+1];B+=data[o+2];n++;}return n?[R/n,G/n,B/n]:[0,0,0];}

export class ReceiverSession{
  constructor(){this.reset();}
  reset(){this.frames=new Map();this.groups=new Map();this.streamLength=0;this.blockLen=0;this.k=0;this.r=0;this.dataCount=0;this.recovered=0;}
  ingest(decoded){if(!decoded)return null;const h=decoded.header;if(!this.streamLength){this.streamLength=h.streamLength;this.blockLen=decoded.payload.length;this.k=h.k;this.r=h.r;this.dataCount=Math.ceil(this.streamLength/this.blockLen);}if(h.streamLength!==this.streamLength||h.k!==this.k||h.r!==this.r)return null;const key=`${h.group}:${h.slot}`;if(this.frames.has(key))return this.progress();this.frames.set(key,decoded.payload);if(!this.groups.has(h.group))this.groups.set(h.group,new Map());this.groups.get(h.group).set(h.slot,decoded.payload);this.tryRecover(h.group);return this.progress();}
  tryRecover(group){const m=this.groups.get(group);if(!m||m.size<this.k)return;let missing=0;for(let i=0;i<this.k;i++)if(!m.get(i))missing++;if(!missing)return;try{const rec=recoverData(m,this.k,this.r,this.blockLen);for(let i=0;i<this.k;i++)if(!m.get(i)){m.set(i,rec[i]);this.frames.set(`${group}:${i}`,rec[i]);this.recovered++;}}catch{}}
  progress(){let have=0;for(let i=0;i<this.dataCount;i++){const g=Math.floor(i/this.k),s=i%this.k;if(this.groups.get(g)?.get(s))have++;}return{have,total:this.dataCount,ratio:this.dataCount?have/this.dataCount:0,recovered:this.recovered,complete:have>=this.dataCount};}
  async assemble(){const out=new Uint8Array(this.dataCount*this.blockLen);for(let i=0;i<this.dataCount;i++){const g=Math.floor(i/this.k),s=i%this.k,b=this.groups.get(g)?.get(s);if(!b)throw new Error(`Falta bloque ${i}`);out.set(b,i*this.blockLen);}return restoreFile(out.slice(0,this.streamLength));}
}

export class CameraTracker{
  constructor(video,overlay,onQuality,onFrame){this.video=video;this.overlay=overlay;this.onQuality=onQuality;this.onFrame=onFrame;this.running=false;this.raf=0;this.work=document.createElement('canvas');this.wctx=this.work.getContext('2d',{willReadFrequently:true});this.lastDecode=0;this.lastHeader=null;}
  start(){this.running=true;this.loop();}stop(){this.running=false;cancelAnimationFrame(this.raf);}
  loop=now=>{if(!this.running)return;this.raf=requestAnimationFrame(this.loop);if(this.video.readyState<2)return;const srcW=this.video.videoWidth||640,srcH=this.video.videoHeight||480,W=Math.min(720,srcW),H=Math.round(W*srcH/srcW);if(this.work.width!==W||this.work.height!==H){this.work.width=W;this.work.height=H;}this.wctx.drawImage(this.video,0,0,W,H);const img=this.wctx.getImageData(0,0,W,H),anchors=this.findAnchors(img.data,W,H);this.draw(anchors);const lock=this.geometryScore(anchors);this.onQuality?.({lock,anchors});if(lock>.85&&now-this.lastDecode>35){this.lastDecode=now;const decoded=this.decode(img.data,W,H,anchors);if(decoded)this.onFrame?.(decoded);}};
  colorScore(idx,r,g,b){if(idx===0)return r+b-2*g;if(idx===1)return g+b-2*r;if(idx===2)return r+g-2*b;return 2*g-r-b;}
  findAnchors(data,W,H){const out=[];for(let idx=0;idx<4;idx++){const binsX=24,binsY=24,sums=new Float64Array(binsX*binsY),counts=new Uint16Array(binsX*binsY);for(let y=0;y<H;y+=3)for(let x=0;x<W;x+=3){const o=(y*W+x)*4,r=data[o],g=data[o+1],b=data[o+2],s=this.colorScore(idx,r,g,b);if(s<60)continue;const bx=Math.min(binsX-1,Math.floor(x/W*binsX)),by=Math.min(binsY-1,Math.floor(y/H*binsY)),bi=by*binsX+bx;sums[bi]+=s;counts[bi]++;}let best=-1,bi=-1;for(let i=0;i<sums.length;i++){const v=sums[i]/Math.max(1,counts[i]);if(counts[i]>=3&&v>best){best=v;bi=i;}}if(bi<0||best<90){out.push(null);continue;}const bx=bi%binsX,by=Math.floor(bi/binsX),cx=(bx+.5)/binsX*W,cy=(by+.5)/binsY*H,rad=Math.max(W/binsX,H/binsY)*1.7;let sx=0,sy=0,sw=0;for(let y=Math.max(0,Math.floor(cy-rad));y<Math.min(H,Math.ceil(cy+rad));y+=2)for(let x=Math.max(0,Math.floor(cx-rad));x<Math.min(W,Math.ceil(cx+rad));x+=2){const o=(y*W+x)*4,s=Math.max(0,this.colorScore(idx,data[o],data[o+1],data[o+2])-65);if(s){sx+=x*s;sy+=y*s;sw+=s;}}out.push(sw?{x:sx/sw,y:sy/sw,score:best}:null);}return out;}
  geometryScore(a){if(a.some(x=>!x))return a.filter(Boolean).length/4*.6;const[tl,tr,br,bl]=a;const top=Math.hypot(tr.x-tl.x,tr.y-tl.y),bottom=Math.hypot(br.x-bl.x,br.y-bl.y),left=Math.hypot(bl.x-tl.x,bl.y-tl.y),right=Math.hypot(br.x-tr.x,br.y-tr.y),area=Math.abs((tl.x*tr.y-tr.x*tl.y)+(tr.x*br.y-br.x*tr.y)+(br.x*bl.y-bl.x*br.y)+(bl.x*tl.y-tl.x*bl.y))/2;const W=this.work.width,H=this.work.height;if(area<W*H*.03)return .4;const symmetry=Math.min(top,bottom)/Math.max(top,bottom)*Math.min(left,right)/Math.max(left,right);return Math.min(1,.7+.3*symmetry);}
  decode(data,W,H,anchors){for(const grid of GRIDS){for(const bits of [2,3,4]){const spec=gridSpec(grid,bits),header=this.decodeHeader(data,W,H,anchors,spec);if(!header||header.bits!==bits||header.cols!==spec.cols||header.rows!==spec.rows)continue;const payload=this.decodePayload(data,W,H,anchors,spec,header);if(payload&&crc32(payload)===header.crc)return{header,payload,grid,quality:1};}}return null;}
  mapper(anchors,spec){const[tl,tr,br,bl]=anchors,map=squareHomography(tl,tr,br,bl);if(!map)return null;const ca=1+spec.anchor/2,nx0=ca/spec.cols,nx1=1-ca/spec.cols,ny0=ca/spec.rows,ny1=1-ca/spec.rows;return(x,y)=>{const nx=(x+.5)/spec.cols,ny=(y+.5)/spec.rows,u=(nx-nx0)/(nx1-nx0),v=(ny-ny0)/(ny1-ny0);return map(u,v);};}
  decodeHeader(data,W,H,anchors,spec){const map=this.mapper(anchors,spec);if(!map)return null;const samples=[],need=34*8;for(let y=spec.border;y<spec.border+spec.headerRows;y++)for(let x=spec.border;x<spec.cols-spec.border;x++){const p=map(x,y),rgb=sampleRGB(data,W,H,p.x,p.y,0),lum=.2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];samples.push(lum);}if(samples.length<need)return null;const sorted=[...samples].sort((a,b)=>a-b),lo=sorted[Math.floor(sorted.length*.15)],hi=sorted[Math.floor(sorted.length*.85)],thr=(lo+hi)/2;if(hi-lo<45)return null;const votes=Array.from({length:need},()=>[0,0]);for(let i=0;i<samples.length;i++)votes[i%need][samples[i]>thr?1:0]++;const bits=votes.map(v=>v[1]>=v[0]?1:0),h=bitsToBytes(bits,34);if(h[0]!==0x48||h[1]!==0x58||h[2]!==0x32||h[3]!==0x46||h[4]!==2||h[33]!==0xA7)return null;const header={profileId:h[5],bits:h[6],kind:h[7],seq:readU32(h,8),total:readU32(h,12),group:readU16(h,16),slot:h[18],k:h[19],r:h[20],streamLength:readU32(h,21),payloadLen:readU16(h,25),cols:h[27],rows:h[28],crc:readU32(h,29)};if(header.bits<2||header.bits>4||header.k<1||header.k>20||header.r>10||header.payloadLen<1||header.payloadLen>65535)return null;return header;}
  decodePayload(data,W,H,anchors,spec,header){const map=this.mapper(anchors,spec);if(!map)return null;const ideal=getPalette(header.bits),observed=ideal.map(()=>[0,0,0,0]),calY=spec.border+spec.headerRows;for(let y=calY;y<calY+spec.calRows;y++)for(let x=spec.border;x<spec.cols-spec.border;x++){const idx=(x-spec.border)%ideal.length,p=map(x,y),rgb=sampleRGB(data,W,H,p.x,p.y,0),o=observed[idx];o[0]+=rgb[0];o[1]+=rgb[1];o[2]+=rgb[2];o[3]++;}const palette=observed.map((o,i)=>o[3]?[o[0]/o[3],o[1]/o[3],o[2]/o[3]]:ideal[i]),symbols=[];const needed=Math.ceil(header.payloadLen*8/header.bits);for(let y=calY+spec.calRows;y<spec.rows-spec.border&&symbols.length<needed;y++)for(let x=spec.border;x<spec.cols-spec.border&&symbols.length<needed;x++){const p=map(x,y),rgb=sampleRGB(data,W,H,p.x,p.y,0);symbols.push(nearestPalette(rgb,palette));}if(symbols.length<needed)return null;return symbolsToBytes(symbols,header.bits,header.payloadLen);}
  draw(anchors){const c=this.overlay,rect=this.video.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=rect.width*dpr;c.height=rect.height*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,rect.width,rect.height);const sx=rect.width/this.work.width,sy=rect.height/this.work.height,pts=anchors.map(a=>a?{x:a.x*sx,y:a.y*sy}:null);ctx.lineWidth=2;ctx.strokeStyle='#69f7d1';for(const p of pts)if(p){ctx.beginPath();ctx.arc(p.x,p.y,7,0,Math.PI*2);ctx.stroke();}if(pts.every(Boolean)){ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);ctx.lineTo(pts[1].x,pts[1].y);ctx.lineTo(pts[2].x,pts[2].y);ctx.lineTo(pts[3].x,pts[3].y);ctx.closePath();ctx.stroke();}}
}
