import { recoverData } from './gf256.js';
import { restoreFile } from './superstream.js';
import { crc32 } from './crc32.js';
import { GRIDS,gridSpec,getPalette,nearestPalette,HDP,finderCenters,isReservedCell } from './optical2.js';

function readU32(a,o){return new DataView(a.buffer,a.byteOffset,a.byteLength).getUint32(o);}function readU16(a,o){return new DataView(a.buffer,a.byteOffset,a.byteLength).getUint16(o);}
function bitsToBytes(bits,count){const out=new Uint8Array(count);for(let i=0;i<count*8;i++)out[i>>3]|=(bits[i]&1)<<(7-(i&7));return out;}
function symbolsToBytes(symbols,bitsPer,count){const out=new Uint8Array(count);let acc=0,n=0,oi=0;for(const s of symbols){acc=(acc<<bitsPer)|s;n+=bitsPer;while(n>=8&&oi<count){n-=8;out[oi++]=(acc>>n)&255;acc&=(1<<n)-1;}if(oi>=count)break;}return out;}
function sampleRGB(data,W,H,x,y,r=0){let R=0,G=0,B=0,n=0;for(let yy=Math.round(y)-r;yy<=Math.round(y)+r;yy++)for(let xx=Math.round(x)-r;xx<=Math.round(x)+r;xx++){if(xx<0||yy<0||xx>=W||yy>=H)continue;const o=(yy*W+xx)*4;R+=data[o];G+=data[o+1];B+=data[o+2];n++;}return n?[R/n,G/n,B/n]:[0,0,0];}
function lum(rgb){return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];}
function homographyFromQuad(p0,p1,p2,p3){const dx1=p1.x-p2.x,dx2=p3.x-p2.x,dx3=p0.x-p1.x+p2.x-p3.x,dy1=p1.y-p2.y,dy2=p3.y-p2.y,dy3=p0.y-p1.y+p2.y-p3.y;let g=0,h=0;const det=dx1*dy2-dx2*dy1;if(Math.abs(dx3)>1e-6||Math.abs(dy3)>1e-6){if(Math.abs(det)<1e-9)return null;g=(dx3*dy2-dx2*dy3)/det;h=(dx1*dy3-dx3*dy1)/det;}const a=p1.x-p0.x+g*p1.x,b=p3.x-p0.x+h*p3.x,c=p0.x,d=p1.y-p0.y+g*p1.y,e=p3.y-p0.y+h*p3.y,f=p0.y;return(u,v)=>{const z=g*u+h*v+1;return{x:(a*u+b*v+c)/z,y:(d*u+e*v+f)/z};};}
function polyArea(q){let s=0;for(let i=0;i<4;i++){const a=q[i],b=q[(i+1)%4];s+=a.x*b.y-b.x*a.y;}return Math.abs(s)/2;}
function hueScore(idx,r,g,b){if(idx===0)return Math.min(r,b)-g;if(idx===1)return Math.min(g,b)-r;if(idx===2)return Math.min(r,g)-b;return g-Math.max(r,b);}

export class ReceiverSession{
  constructor(){this.reset();}
  reset(){this.frames=new Map();this.groups=new Map();this.streamLength=0;this.blockLen=0;this.k=0;this.r=0;this.dataCount=0;this.recovered=0;this.duplicates=0;}
  ingest(decoded){if(!decoded)return null;const h=decoded.header;if(!this.streamLength){this.streamLength=h.streamLength;this.blockLen=decoded.payload.length;this.k=h.k;this.r=h.r;this.dataCount=Math.ceil(this.streamLength/this.blockLen);}if(h.streamLength!==this.streamLength||h.k!==this.k||h.r!==this.r)return null;const key=`${h.group}:${h.slot}`;if(this.frames.has(key)){this.duplicates++;return this.progress();}this.frames.set(key,decoded.payload);if(!this.groups.has(h.group))this.groups.set(h.group,new Map());this.groups.get(h.group).set(h.slot,decoded.payload);this.tryRecover(h.group);return this.progress();}
  tryRecover(group){const m=this.groups.get(group);if(!m||m.size<this.k)return;let missing=0;for(let i=0;i<this.k;i++)if(!m.get(i))missing++;if(!missing)return;try{const rec=recoverData(m,this.k,this.r,this.blockLen);for(let i=0;i<this.k;i++)if(!m.get(i)){m.set(i,rec[i]);this.frames.set(`${group}:${i}`,rec[i]);this.recovered++;}}catch{}}
  progress(){let have=0,missing=0,pendingGroups=0;const groupCount=Math.ceil(this.dataCount/this.k);for(let g=0;g<groupCount;g++){let groupMissing=0;for(let s=0;s<this.k;s++){const idx=g*this.k+s;if(idx>=this.dataCount)continue;if(this.groups.get(g)?.get(s))have++;else{missing++;groupMissing++;}}if(groupMissing)pendingGroups++;}return{have,total:this.dataCount,missing,pendingGroups,ratio:this.dataCount?have/this.dataCount:0,recovered:this.recovered,duplicates:this.duplicates,complete:have>=this.dataCount};}
  async assemble(){const out=new Uint8Array(this.dataCount*this.blockLen);for(let i=0;i<this.dataCount;i++){const g=Math.floor(i/this.k),s=i%this.k,b=this.groups.get(g)?.get(s);if(!b)throw new Error(`Falta bloque ${i}`);out.set(b,i*this.blockLen);}return restoreFile(out.slice(0,this.streamLength));}
}

export class CameraTracker{
  constructor(video,overlay,onQuality,onFrame){this.video=video;this.overlay=overlay;this.onQuality=onQuality;this.onFrame=onFrame;this.running=false;this.raf=0;this.work=document.createElement('canvas');this.ctx=this.work.getContext('2d',{willReadFrequently:true});this.lastQuad=null;this.stable=0;this.lastDecode=0;this.scanTick=0;}
  start(){this.running=true;this.loop();}stop(){this.running=false;cancelAnimationFrame(this.raf);}
  loop=now=>{if(!this.running)return;this.raf=requestAnimationFrame(this.loop);if(this.video.readyState<2)return;const sw=this.video.videoWidth||640,sh=this.video.videoHeight||480,W=Math.min(720,sw),H=Math.max(1,Math.round(W*sh/sw));if(this.work.width!==W||this.work.height!==H){this.work.width=W;this.work.height=H;}this.ctx.drawImage(this.video,0,0,W,H);const img=this.ctx.getImageData(0,0,W,H);let found=null;if(!this.lastQuad||(++this.scanTick%2===0))found=this.detectBeacons(img.data,W,H,this.lastQuad);if(found){this.lastQuad=this.smooth(this.lastQuad,found.quad,.34);this.stable=Math.min(16,this.stable+2);}else this.stable=Math.max(0,this.stable-.35);const lock=this.lastQuad?Math.min(1,this.stable/6)*this.geometryScore(this.lastQuad,W,H):0;this.draw(this.lastQuad,lock);this.onQuality?.({lock,quad:this.lastQuad,mode:'LIGHTHOUSE'});if(this.lastQuad&&lock>.62&&now-this.lastDecode>32){this.lastDecode=now;const decoded=this.decode(img.data,W,H,this.lastQuad);if(decoded)this.onFrame?.(decoded);}};
  smooth(a,b,k){if(!a)return b;return b.map((p,i)=>({x:a[i].x*(1-k)+p.x*k,y:a[i].y*(1-k)+p.y*k}));}
  findBeacon(data,W,H,idx,expected){const gw=Math.min(240,Math.max(140,Math.round(W*.42))),gh=Math.max(90,Math.round(gw*H/W)),mask=new Uint8Array(gw*gh),weights=new Uint8Array(gw*gh);for(let gy=0;gy<gh;gy++)for(let gx=0;gx<gw;gx++){const x=(gx+.5)/gw*W,y=(gy+.5)/gh*H,[r,g,b]=sampleRGB(data,W,H,x,y,0),s=hueScore(idx,r,g,b),bright=Math.max(r,g,b);if(s>72&&bright>115){const i=gy*gw+gx;mask[i]=1;weights[i]=Math.min(255,Math.round(s));}}const seen=new Uint8Array(mask.length);let best=null,bestScore=-1;for(let i=0;i<mask.length;i++){if(!mask[i]||seen[i])continue;const stack=[i];seen[i]=1;let count=0,minX=gw,maxX=0,minY=gh,maxY=0,sx=0,sy=0,sw=0;while(stack.length){const n=stack.pop(),x=n%gw,y=Math.floor(n/gw),w=weights[n]+1;count++;sx+=(x+.5)*w;sy+=(y+.5)*w;sw+=w;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const xx=x+dx,yy=y+dy;if(xx<0||yy<0||xx>=gw||yy>=gh)continue;const j=yy*gw+xx;if(mask[j]&&!seen[j]){seen[j]=1;stack.push(j);}}}if(count<8)continue;const bw=maxX-minX+1,bh=maxY-minY+1,density=count/(bw*bh),square=Math.min(bw,bh)/Math.max(bw,bh);if(bw<3||bh<3||density<.18||square<.35)continue;const px=sx/sw/gw*W,py=sy/sw/gh*H;let score=count*density*(.55+.45*square);if(expected){const d=Math.hypot(px-expected.x,py-expected.y),diag=Math.hypot(W,H);score*=Math.exp(-d/(diag*.13));}if(score>bestScore){bestScore=score;best={x:px,y:py,score};}}return best;}
  detectBeacons(data,W,H,expected){const pts=[];for(let i=0;i<4;i++){const p=this.findBeacon(data,W,H,i,expected?.[i]);if(!p)return null;pts.push(p);}if(polyArea(pts)<W*H*.018)return null;const q=pts.map(p=>({x:p.x,y:p.y}));const g=this.geometryScore(q,W,H);if(g<.45)return null;return{quad:q,confidence:g};}
  geometryScore(q,W,H){if(!q||q.length!==4)return 0;const area=polyArea(q);if(area<W*H*.012)return .15;const[tl,tr,br,bl]=q,top=Math.hypot(tr.x-tl.x,tr.y-tl.y),bottom=Math.hypot(br.x-bl.x,br.y-bl.y),left=Math.hypot(bl.x-tl.x,bl.y-tl.y),right=Math.hypot(br.x-tr.x,br.y-tr.y);if(Math.min(top,bottom,left,right)<Math.min(W,H)*.07)return .2;const sym=Math.min(top,bottom)/Math.max(top,bottom)*Math.min(left,right)/Math.max(left,right);return Math.min(1,.58+.42*sym);}
  mapper(quad,spec){const map=homographyFromQuad(...quad);if(!map)return null;const c=finderCenters(spec),u0=c[0].x/spec.cols,u1=c[1].x/spec.cols,v0=c[0].y/spec.rows,v1=c[3].y/spec.rows;return(x,y)=>{const nx=(x+.5)/spec.cols,ny=(y+.5)/spec.rows;return map((nx-u0)/(u1-u0),(ny-v0)/(v1-v0));};}
  decode(data,W,H,quad){for(const grid of GRIDS)for(const bits of [2,3,4]){const spec=gridSpec(grid,bits),header=this.decodeHeader(data,W,H,quad,spec);if(!header||header.bits!==bits||header.cols!==spec.cols||header.rows!==spec.rows)continue;const payload=this.decodePayload(data,W,H,quad,spec,header);if(payload&&crc32(payload)===header.crc)return{header,payload,grid,quality:1};}return null;}
  decodeHeader(data,W,H,quad,spec){const map=this.mapper(quad,spec);if(!map)return null;const samples=[],need=38*8;for(let y=spec.top;y<spec.top+spec.headerRows;y++)for(let x=spec.left;x<spec.right;x++){if(isReservedCell(spec,x,y))continue;const p=map(x,y);samples.push(lum(sampleRGB(data,W,H,p.x,p.y,0)));}if(samples.length<need)return null;const sorted=[...samples].sort((a,b)=>a-b),lo=sorted[Math.floor(sorted.length*.14)],hi=sorted[Math.floor(sorted.length*.86)],thr=(lo+hi)/2;if(hi-lo<38)return null;const votes=Array.from({length:need},()=>[0,0]);for(let i=0;i<samples.length;i++)votes[i%need][samples[i]>thr?1:0]++;const h=bitsToBytes(votes.map(v=>v[1]>=v[0]?1:0),38);if(h[0]!==0x48||h[1]!==0x44||h[2]!==0x50||h[3]!==0x32||h[4]!==HDP.version||h[37]!==0xD4)return null;const header={profileId:h[5],bits:h[6],kind:h[7],seq:readU32(h,8),total:readU32(h,12),group:readU16(h,16),slot:h[18],k:h[19],r:h[20],streamLength:readU32(h,21),payloadLen:readU16(h,25),cols:h[27],rows:h[28],crc:readU32(h,29),finder:h[33],quiet:h[34],guard:h[35],hdp:h[36]};if(header.hdp!==HDP.version||header.bits<2||header.bits>4||header.payloadLen<1||header.payloadLen>65535)return null;return header;}
  decodePayload(data,W,H,quad,spec,header){const map=this.mapper(quad,spec);if(!map)return null;const ideal=getPalette(header.bits),obs=ideal.map(()=>[0,0,0,0]),calY=spec.top+spec.headerRows+spec.syncRows;for(let y=calY;y<calY+spec.calRows;y++)for(let x=spec.left;x<spec.right;x++){if(isReservedCell(spec,x,y))continue;const p=map(x,y),rgb=sampleRGB(data,W,H,p.x,p.y,0),idx=(x-spec.left)%ideal.length,o=obs[idx];o[0]+=rgb[0];o[1]+=rgb[1];o[2]+=rgb[2];o[3]++;}const palette=obs.map((o,i)=>o[3]?[o[0]/o[3],o[1]/o[3],o[2]/o[3]]:ideal[i]),symbols=[],need=Math.ceil(header.payloadLen*8/header.bits);for(let y=spec.payloadTop;y<spec.payloadBottom&&symbols.length<need;y++)for(let x=spec.left;x<spec.right&&symbols.length<need;x++){if(isReservedCell(spec,x,y))continue;const p=map(x,y);symbols.push(nearestPalette(sampleRGB(data,W,H,p.x,p.y,0),palette));}if(symbols.length<need)return null;return symbolsToBytes(symbols,header.bits,header.payloadLen);}
  draw(q,lock){const c=this.overlay,rect=this.video.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=rect.width*dpr;c.height=rect.height*dpr;const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);if(!q)return;const sx=rect.width/this.work.width,sy=rect.height/this.work.height,pts=q.map(p=>({x:p.x*sx,y:p.y*sy})),colors=['#ff00ff','#00ffff','#ffff00','#00ff00'];ctx.lineWidth=lock>.62?3:2;ctx.strokeStyle=lock>.62?'#68f7d1':'#ffca55';ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(let i=1;i<4;i++)ctx.lineTo(pts[i].x,pts[i].y);ctx.closePath();ctx.stroke();for(let i=0;i<4;i++){ctx.fillStyle=colors[i];ctx.beginPath();ctx.arc(pts[i].x,pts[i].y,7,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#000';ctx.stroke();}}
}
