import {packFile,restoreFile,humanBytes} from '../hopperlink-pixelstream/src/superstream.js';
import {FountainDecoder} from './fountain.js';
import {BUILD,PROFILES,profileByKey,randomSession,nominalRate} from './protocol.js';

const $=s=>document.querySelector(s), text=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=String(v);};
const fmtRate=n=>`${humanBytes(n)}/s`, fmtTime=s=>!Number.isFinite(s)?'—':s<60?`${s.toFixed(s<10?1:0)} s`:`${Math.floor(s/60)} min ${Math.round(s%60)} s`;
let selectedFile=null,packed=null,send=null,rx=null;
text('build',BUILD);
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active');};

const frameCanvas=[document.createElement('canvas'),document.createElement('canvas')];
function symbolToCanvas(symbol,index){const c=frameCanvas[index],w=symbol.width,h=symbol.height;if(c.width!==w||c.height!==h){c.width=w;c.height=h;}const ctx=c.getContext('2d',{alpha:false}),img=ctx.createImageData(w,h),u32=new Uint32Array(img.data.buffer),d=new Uint8ClampedArray(symbol.data),edge=d[0];for(let i=0;i<d.length;i++)u32[i]=d[i]===edge?0xffffffff:0xff000000;ctx.putImageData(img,0,0);return c;}
function paintPair(){if(!send?.running)return;const p=send.profile,need=[];for(let i=0;i<p.codes;i++)need.push(send.nextSeq+i);if(!need.every(n=>send.buffer.has(n))){send.starved++;return;}const stage=$('#txCanvas'),ctx=stage.getContext('2d',{alpha:false}),cssW=Math.max(720,p.codes*720),cssH=720;if(stage.width!==cssW||stage.height!==cssH){stage.width=cssW;stage.height=cssH;}ctx.fillStyle='#fff';ctx.fillRect(0,0,stage.width,stage.height);for(let i=0;i<p.codes;i++){const seq=need[i],sym=send.buffer.get(seq);send.buffer.delete(seq);const q=symbolToCanvas(sym,i),side=Math.min(stage.height,stage.width/p.codes)*.96,x=i*stage.width/p.codes+(stage.width/p.codes-side)/2,y=(stage.height-side)/2;ctx.imageSmoothingEnabled=false;ctx.drawImage(q,0,0,q.width,q.height,x,y,side,side);}send.nextSeq+=p.codes;send.presented+=p.codes;send.lastPresentedAt=performance.now();prefillSender();}
function txLoop(now){if(!send?.running)return;const dt=1000/send.profile.fps;if(now-send.lastTick>=dt){send.lastTick=now;paintPair();updateSender();}send.raf=requestAnimationFrame(txLoop);}
function makeSenderWorkers(count){const ws=[];for(let i=0;i<count;i++){const w=new Worker('./sender-worker.js?v=qf01',{type:'module'});w.busy=false;w.onmessage=e=>{const m=e.data;if(m.type==='ready'){w.ready=true;prefillSender();}else if(m.type==='frame'){w.busy=false;send?.buffer.set(m.seq,{...m,data:m.data});send&&(send.generated++,prefillSender());}else if(m.type==='error'){w.busy=false;send&&(send.errors++,text('sendState','Error QR: '+m.message));prefillSender();}};ws.push(w);}return ws;}
function prefillSender(){if(!send)return;const target=send.nextSeq+Math.max(24,send.profile.codes*24);for(const w of send.workers){if(w.busy||!w.ready)continue;while(send.requestSeq<target&&send.buffer.has(send.requestSeq))send.requestSeq++;if(send.requestSeq>=target)break;const seq=send.requestSeq++,codeIndex=seq%send.profile.codes;w.busy=true;w.postMessage({type:'render',seq,codeIndex});}}
function updateSender(){if(!send)return;const elapsed=(performance.now()-send.startedAt)/1000,textRate=send.presented*send.profile.blockLen/Math.max(.001,elapsed);text('txSeq',send.presented.toLocaleString());text('txOut',fmtRate(textRate));text('txBuffer',`${send.buffer.size} QR`);text('txGen',fmtRate(send.generated*send.profile.blockLen/Math.max(.001,elapsed)));text('txStarve',String(send.starved));}
async function stopSender(msg='Detenido.'){if(!send)return;send.running=false;cancelAnimationFrame(send.raf);for(const w of send.workers)w.terminate();send=null;text('sendState',msg);document.body.classList.remove('tx-full');try{if(document.fullscreenElement)await document.exitFullscreen();}catch{}}
$('#fileInput').onchange=e=>{selectedFile=e.target.files[0]||null;packed=null;$('#prepareBtn').disabled=!selectedFile;$('#startBtn').disabled=true;text('fileState',selectedFile?`${selectedFile.name} · ${humanBytes(selectedFile.size)}`:'Sin archivo');};
$('#profile').onchange=()=>{const p=profileByKey($('#profile').value);text('profileBudget',`${fmtRate(nominalRate(p))} nominal · ${p.fps} fps × ${p.codes} QR`);};$('#profile').dispatchEvent(new Event('change'));
$('#prepareBtn').onclick=async()=>{if(!selectedFile)return;$('#prepareBtn').disabled=true;text('sendState','Preparando y verificando archivo…');try{packed=await packFile(selectedFile);const p=profileByKey($('#profile').value),k=Math.ceil(packed.stream.length/p.blockLen);text('preparedInfo',`${humanBytes(packed.stream.length)} ópticos · ${k} bloques fuente · SHA-256 ${packed.meta.sha256.slice(0,12)}…`);$('#startBtn').disabled=false;text('sendState','Preparado. El receptor puede incorporarse en cualquier momento.');}catch(e){text('sendState',e.message);}finally{$('#prepareBtn').disabled=false;}};
$('#startBtn').onclick=async()=>{if(!packed||send?.running)return;const p=profileByKey($('#profile').value),session=randomSession(),workers=makeSenderWorkers(Math.min(4,Math.max(2,navigator.hardwareConcurrency||4)));send={running:true,profile:p,session,workers,buffer:new Map(),nextSeq:0,requestSeq:0,presented:0,generated:0,starved:0,errors:0,startedAt:performance.now(),lastTick:0,lastPresentedAt:0,raf:0};for(const w of workers)w.postMessage({type:'init',stream:packed.stream.slice().buffer,blockLen:p.blockLen,session,qrVersion:p.qrVersion});text('sendState',`Transmitiendo sesión ${session.toString(16)} · sin handshake.`);document.body.classList.add('tx-full');try{await $('#txStage').requestFullscreen?.();if(p.codes>1)await screen.orientation?.lock?.('landscape');}catch{}send.raf=requestAnimationFrame(txLoop);};
$('#stopBtn').onclick=()=>stopSender();$('#exitTx').onclick=()=>stopSender();

function workerCount(){return Math.min(4,Math.max(2,navigator.hardwareConcurrency||4));}
function makeDecoderWorkers(n){const ws=[];for(let i=0;i<n;i++){const w=new Worker('./decoder-worker.js?v=qf01',{type:'module'});w.busy=false;w.ready=false;w.onmessage=e=>{const m=e.data;if(m.type==='ready'){w.ready=true;}else if(m.type==='decoded'){w.busy=false;if(rx){rx.decodedJobs++;for(const p of m.packets)handlePacket(p);scheduleCapture();}}else if(m.type==='error'){w.busy=false;if(rx){rx.decodeErrors++;scheduleCapture();}}};w.postMessage({type:'init'});ws.push(w);}return ws;}
function packetObject(m){return{...m.header,payload:new Uint8Array(m.payload)};}
async function handlePacket(m){if(!rx)return;const p=packetObject(m);if(!rx.decoder||rx.decoder.session!==p.session){rx.decoder=new FountainDecoder(p);rx.session=p.session;rx.firstPacketAt=performance.now();rx.lastSolved=0;text('rxSession',p.session.toString(16));text('rxState','Sesión encontrada. Reconstruyendo desde cualquier QR válido…');}
 if(!rx.decoder.compatible(p))return;const before=rx.decoder.progress().solved,progress=rx.decoder.ingest(p);if(progress.solved>before)rx.lastUsefulAt=performance.now();rx.uniquePackets=progress.received;rx.lastSolved=progress.solved;updateReceiver();if(progress.complete&&!rx.verifying){rx.verifying=true;try{const stream=rx.decoder.assemble(),file=await restoreFile(stream),elapsed=(performance.now()-rx.firstPacketAt)/1000;rx.completedAt=performance.now();rx.goodput=stream.length/elapsed;const url=URL.createObjectURL(new Blob([file.data],{type:file.meta.type||'application/octet-stream'})),a=document.createElement('a');a.href=url;a.download=file.meta.name;a.textContent='Guardar '+file.meta.name;const pEl=document.createElement('p');pEl.textContent=`SHA-256 OK · ${fmtTime(elapsed)} · ${fmtRate(rx.goodput)}`;$('#received').replaceChildren(pEl,a);$('#received').hidden=false;text('rxState','Archivo completo y verificado.');}catch(e){text('rxState','Error final: '+e.message);rx.decoder=null;}finally{rx.verifying=false;updateReceiver();}}}
function updateReceiver(){if(!rx)return;const now=performance.now(),elapsed=rx.firstPacketAt?(rx.completedAt??now)-rx.firstPacketAt:0,p=rx.decoder?.progress(),seconds=elapsed/1000,solvedBytes=p?Math.min(rx.decoder.totalLen,p.solved*rx.decoder.blockLen):0;const useful=seconds>0?solvedBytes/seconds:0;const captureSeconds=Math.max(.001,(now-rx.statsStart)/1000);text('rxCapture',`${(rx.captures/captureSeconds).toFixed(1)} fps`);text('rxDecode',`${(rx.decodedJobs/captureSeconds).toFixed(1)} jobs/s`);text('rxPackets',p?`${p.received} QR / ${p.solved}/${p.k} bloques`:'0');text('rxUseful',fmtRate(rx.completedAt?rx.goodput:useful));text('rxDrop',String(rx.droppedBusy));text('rxErrors',String(rx.decodeErrors));if(p){const pct=Math.min(100,p.ratio*100);$('#rxBar > div').style.width=pct+'%';text('rxPct',pct.toFixed(1)+'%');}}
function scheduleCapture(){}
function captureFrame(now,meta){if(!rx?.running)return;rx.lastCallback=now;const video=$('#rxVideo');if(video.readyState<2){requestRxFrame();return;}const free=rx.workers.find(w=>w.ready&&!w.busy);if(!free){rx.droppedBusy++;requestRxFrame();return;}const sw=video.videoWidth,sh=video.videoHeight;if(!sw||!sh){requestRxFrame();return;}const max=1280,scale=Math.min(1,max/Math.max(sw,sh)),W=Math.max(1,Math.round(sw*scale)),H=Math.max(1,Math.round(sh*scale)),c=rx.canvas;if(c.width!==W||c.height!==H){c.width=W;c.height=H;}rx.ctx.drawImage(video,0,0,W,H);const img=rx.ctx.getImageData(0,0,W,H),id=++rx.jobId;free.busy=true;rx.captures++;free.postMessage({type:'decode',id,width:W,height:H,rgba:img.data.buffer},[img.data.buffer]);if(rx.captures%10===0)updateReceiver();requestRxFrame();}
function requestRxFrame(){if(!rx?.running)return;const v=$('#rxVideo');if(v.requestVideoFrameCallback)rx.vfc=v.requestVideoFrameCallback(captureFrame);else rx.raf=requestAnimationFrame(t=>captureFrame(t,{mediaTime:v.currentTime}));}
async function stopReceiver(){if(!rx)return;rx.running=false;const v=$('#rxVideo');if(v.cancelVideoFrameCallback&&rx.vfc)v.cancelVideoFrameCallback(rx.vfc);cancelAnimationFrame(rx.raf);for(const w of rx.workers)w.terminate();rx.stream?.getTracks().forEach(t=>t.stop());v.srcObject=null;rx=null;text('cameraBtn','Iniciar cámara');text('rxState','Receptor detenido.');}
async function openCamera(deviceId=''){const base={width:{ideal:1920},height:{ideal:1080},...(deviceId?{deviceId:{exact:deviceId}}:{facingMode:{ideal:'environment'}})};try{return await navigator.mediaDevices.getUserMedia({video:{...base,frameRate:{exact:60}},audio:false});}catch{return await navigator.mediaDevices.getUserMedia({video:{...base,frameRate:{ideal:60,min:24}},audio:false});}}
async function refreshCameras(selected=''){try{const devices=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='videoinput'),sel=$('#cameraSelect'),old=selected||sel.value;sel.replaceChildren(new Option('Trasera automática',''));for(const [i,d] of devices.entries())sel.add(new Option(d.label||`Cámara ${i+1}`,d.deviceId));if([...sel.options].some(o=>o.value===old))sel.value=old;}catch{}}
$('#cameraBtn').onclick=async()=>{if(rx){await stopReceiver();return;}text('rxState','Solicitando cámara…');try{const stream=await openCamera($('#cameraSelect').value),video=$('#rxVideo');video.srcObject=stream;await video.play();const settings=stream.getVideoTracks()[0].getSettings(),workers=makeDecoderWorkers(workerCount());rx={running:true,stream,workers,canvas:document.createElement('canvas'),ctx:null,decoder:null,session:0,firstPacketAt:0,completedAt:0,goodput:0,verifying:false,captures:0,decodedJobs:0,droppedBusy:0,decodeErrors:0,jobId:0,statsStart:performance.now(),raf:0,vfc:0,lastCallback:0,uniquePackets:0,lastSolved:0};rx.ctx=rx.canvas.getContext('2d',{willReadFrequently:true,alpha:false});await refreshCameras(stream.getVideoTracks()[0].getSettings().deviceId||$('#cameraSelect').value);text('cameraBtn','Apagar cámara');text('cameraInfo',`${settings.width||video.videoWidth}×${settings.height||video.videoHeight} · cámara ${settings.frameRate||'?'} fps · ${workers.length} workers WASM`);text('rxState','Buscando QR Hopper Fountain. No necesita anuncio inicial.');requestRxFrame();}catch(e){text('rxState','No se pudo abrir la cámara: '+e.message);}};
$('#cameraSelect').onchange=async()=>{if(rx){await stopReceiver();$('#cameraBtn').click();}};
$('#resetRx').onclick=()=>{if(!rx)return;rx.decoder=null;rx.session=0;rx.firstPacketAt=0;rx.completedAt=0;rx.goodput=0;rx.verifying=false;$('#received').hidden=true;$('#received').replaceChildren();$('#rxBar > div').style.width='0%';text('rxPct','0.0%');text('rxState','Receptor limpio. Puede incorporarse a una transmisión ya iniciada.');};

window.addEventListener('pagehide',()=>{stopSender();stopReceiver();});
window.__hopperFountain={get send(){return send;},get rx(){return rx;},PROFILES};
window.__hopperBootOK=true;
