import { packFile,buildTransport,humanBytes } from './src/superstream.js';
import { resolveProfile,renderOpticalFrame } from './src/optical.js';
import { CameraTracker,ReceiverSession } from './src/receiver.js';
const $=s=>document.querySelector(s),logEl=$('#diagnostics');
function log(msg){const t=new Date().toLocaleTimeString();logEl.textContent=`[${t}] ${msg}\n`+logEl.textContent.slice(0,7000);}function fmtRate(n){return `${(n/1024).toFixed(n/1024>=100?0:1)} KB/s`;}
let file=null,packed=null,transport=null,profile=null,tx={running:false,index:0,raf:0,last:0};
for(const b of document.querySelectorAll('.tab'))b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');};
$('#fileInput').onchange=e=>setFile(e.target.files[0]);const dz=$('#dropzone');dz.ondragover=e=>e.preventDefault();dz.ondrop=e=>{e.preventDefault();setFile(e.dataTransfer.files[0]);};
function setFile(f){if(!f)return;file=f;$('#fileState').textContent=`${f.name} · ${humanBytes(f.size)}`;$('#prepareBtn').disabled=false;log(`Archivo seleccionado: ${f.name} (${f.size} B)`);}
function currentProfile(){return resolveProfile($('#profileSelect').value,$('#gridSelect').value);}function updateBench(){const p=currentProfile(),fps=+$('#fpsSelect').value,gross=p.payloadCells*p.bits*fps/8,fec=p.k/(p.k+p.r),net=gross*p.efficiency*fec;$('#bCells').textContent=p.payloadCells.toLocaleString();$('#bBpc').textContent=p.bits;$('#bGross').textContent=fmtRate(gross);$('#bNet').textContent=fmtRate(net);}['profileSelect','gridSelect','fpsSelect'].forEach(id=>$('#'+id).onchange=updateBench);updateBench();
$('#prepareBtn').onclick=async()=>{if(!file)return;const btn=$('#prepareBtn');btn.disabled=true;btn.textContent='Preparando…';try{profile=currentProfile();packed=await packFile(file);profile.payloadBytes=Math.min(profile.payloadBytes,65535);transport=buildTransport(packed.stream,profile);const baseline=Math.ceil(packed.originalBytes/profile.payloadBytes),systematic=transport.dataCount;$('#mOriginal').textContent=humanBytes(packed.originalBytes);$('#mPacked').textContent=humanBytes(packed.stream.length);$('#mCompression').textContent=packed.meta.codec==='raw'?'pass-through':`${(packed.originalBytes/packed.packedBytes).toFixed(2)}× gzip`;$('#mCollapse').textContent=`${baseline} → ${systematic}`;$('#mPayload').textContent=humanBytes(profile.payloadBytes);$('#mFec').textContent=`RS ${profile.k}+${profile.r}`;$('#startTxBtn').disabled=false;$('#txPlaceholder').classList.add('hidden');renderAt(0);$('#tGain').textContent=`${(packed.originalBytes/packed.stream.length).toFixed(2)}×`;log(`SuperStream v2: ${packed.meta.codec}, ${packed.stream.length} B, ${transport.dataCount} bloques útiles + FEC.`);}catch(err){log(`ERROR: ${err.message}`);alert(err.message);}finally{btn.disabled=false;btn.textContent='Analizar y preparar';}};
function renderAt(i){if(!transport)return;const frame=transport.frames[i];renderOpticalFrame($('#txCanvas'),frame,transport,profile,i,transport.frames.length);$('#tFrame').textContent=`${i+1}/${transport.frames.length}`;$('#txProgress').style.width=`${((i+1)/transport.frames.length)*100}%`;const fps=+$('#fpsSelect').value,gross=profile.payloadBytes*fps,net=gross*(profile.k/(profile.k+profile.r))*profile.efficiency;$('#tGross').textContent=fmtRate(gross);$('#tRate').textContent=fmtRate(net);}
function txLoop(now){if(!tx.running)return;const interval=1000/+$('#fpsSelect').value;if(!tx.last||now-tx.last>=interval){tx.last=now;renderAt(tx.index++);if(tx.index>=transport.frames.length){tx.running=false;$('#txStatus').textContent='COMPLETO';$('#txStatus').className='status-dot live';$('#pauseTxBtn').disabled=true;return;}}tx.raf=requestAnimationFrame(txLoop);}
$('#startTxBtn').onclick=()=>{if(!transport)return;tx.running=true;tx.index=0;tx.last=0;$('#txStatus').textContent='EMITIENDO';$('#txStatus').className='status-dot live';$('#pauseTxBtn').disabled=false;$('#pauseTxBtn').textContent='Pausar';tx.raf=requestAnimationFrame(txLoop);};
$('#pauseTxBtn').onclick=()=>{tx.running=!tx.running;if(tx.running){tx.last=0;$('#pauseTxBtn').textContent='Pausar';tx.raf=requestAnimationFrame(txLoop);}else{cancelAnimationFrame(tx.raf);$('#pauseTxBtn').textContent='Continuar';$('#txStatus').textContent='PAUSA';}};$('#fullTxBtn').onclick=async()=>{const el=$('#txStage');if(!document.fullscreenElement)await el.requestFullscreen?.();else await document.exitFullscreen?.();};
let media=null,tracker=null,rxActive=false,assembling=false;const rxSession=new ReceiverSession();
async function onDecoded(decoded){if(!rxActive)return;const p=rxSession.ingest(decoded);if(!p)return;$('#rFrames').textContent=rxSession.frames.size;$('#rRecovered').textContent=p.recovered;$('#rBer').textContent='CRC OK';$('#rxProgress').style.width=`${Math.round(p.ratio*100)}%`;$('#rxHint').textContent=`Frame ${decoded.header.seq+1}/${decoded.header.total} · ${Math.round(p.ratio*100)}%`;if(p.complete&&!assembling){assembling=true;try{const {meta,data}=await rxSession.assemble(),blob=new Blob([data],{type:meta.type}),url=URL.createObjectURL(blob);const box=$('#receivedFile');box.classList.remove('hidden');box.innerHTML=`<strong>${meta.name}</strong><br><span>${humanBytes(data.length)} · SHA-256 OK</span><br><a href="${url}" download="${meta.name}">Guardar archivo recibido</a>`;$('#rxStatus').textContent='COMPLETO';log(`Archivo reconstruido: ${meta.name} (${data.length} B).`);rxActive=false;$('#receiveBtn').textContent='Comenzar recepción';}catch(err){log(`Reconstrucción: ${err.message}`);}finally{assembling=false;}}}
$('#cameraBtn').onclick=async()=>{try{if(media){media.getTracks().forEach(t=>t.stop());media=null;tracker?.stop();$('#cameraBtn').textContent='Iniciar cámara';$('#receiveBtn').disabled=true;return;}media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:60}},audio:false});$('#rxVideo').srcObject=media;await $('#rxVideo').play();tracker=new CameraTracker($('#rxVideo'),$('#rxOverlay'),q=>{$('#rLock').textContent=`${Math.round(q.lock*100)}%`;$('#rxStatus').textContent=q.lock>.85?'LOCK':'BUSCANDO';$('#rxStatus').className=`status-dot ${q.lock>.85?'live':'idle'}`;},onDecoded);tracker.start();$('#cameraBtn').textContent='Apagar cámara';$('#receiveBtn').disabled=false;$('#rxHint').textContent='Busca los cuatro fiduciales de color.';log('Cámara iniciada. Demodulador HXS2 activo.');}catch(err){log(`Cámara: ${err.message}`);alert('No se pudo abrir la cámara. Revisa permisos y HTTPS.');}};
$('#receiveBtn').onclick=()=>{rxActive=!rxActive;$('#receiveBtn').textContent=rxActive?'Detener recepción':'Comenzar recepción';log(rxActive?'Recepción HXS2 armada.':'Recepción detenida.');};$('#resetRxBtn').onclick=()=>{rxSession.reset();assembling=false;$('#rFrames').textContent='0';$('#rRecovered').textContent='0';$('#rBer').textContent='—';$('#rxProgress').style.width='0%';$('#receivedFile').classList.add('hidden');log('Receptor reiniciado.');};window.addEventListener('beforeunload',()=>media?.getTracks().forEach(t=>t.stop()));log('HopperLink X v2: SuperStream + RS-FEC + demodulación óptica adaptativa.');
