import { packFile,buildTransport,buildFrameSchedule,humanBytes } from './src/superstream.js';
import { resolveProfile,renderOpticalFrame,renderDiscoveryFrame,HDP } from './src/optical2.js';
import { CameraTracker,ReceiverSession } from './src/receiver2.js';
const $=s=>document.querySelector(s),logEl=$('#diagnostics');
function log(msg){const t=new Date().toLocaleTimeString();if(logEl)logEl.textContent=`[${t}] ${msg}\n`+(logEl.textContent||'').slice(0,7000);}function fmtRate(n){return `${(n/1024).toFixed(n/1024>=100?0:1)} KB/s`;}
let file=null,packed=null,transport=null,profile=null,primarySchedule=[],rescueSchedules=[];
let tx={running:false,schedule:[],scheduleIndex:0,phaseIndex:0,phaseLabel:'',framesSinceBeacon:0,raf:0,last:0,discoveryUntil:0,beaconUntil:0,phase:0,sent:0,totalPlanned:0};
for(const b of document.querySelectorAll('.tab'))b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab)?.classList.add('active');};
$('#fileInput').onchange=e=>setFile(e.target.files[0]);const dz=$('#dropzone');dz.ondragover=e=>e.preventDefault();dz.ondrop=e=>{e.preventDefault();setFile(e.dataTransfer.files[0]);};
function setFile(f){if(!f)return;file=f;$('#fileState').textContent=`${f.name} · ${humanBytes(f.size)}`;$('#prepareBtn').disabled=false;log(`Archivo seleccionado: ${f.name} (${f.size} B)`);}
function currentProfile(){return resolveProfile($('#profileSelect').value,$('#gridSelect').value);}function updateBench(){const p=currentProfile(),fps=+$('#fpsSelect').value,gross=p.payloadCells*p.bits*fps/8,fec=p.k/(p.k+p.r),net=gross*p.efficiency*fec;$('#bCells').textContent=p.payloadCells.toLocaleString();$('#bBpc').textContent=p.bits;$('#bGross').textContent=fmtRate(gross);$('#bNet').textContent=fmtRate(net);}function syncAspect(){const p=currentProfile();$('#txStage').style.aspectRatio=`${p.cols}/${p.rows}`;}['profileSelect','gridSelect','fpsSelect'].forEach(id=>$('#'+id).onchange=()=>{updateBench();syncAspect();});updateBench();syncAspect();
$('#prepareBtn').onclick=async()=>{if(!file)return;const btn=$('#prepareBtn');btn.disabled=true;btn.textContent='Preparando…';try{profile=currentProfile();packed=await packFile(file);profile.payloadBytes=Math.min(profile.payloadBytes,65535);transport=buildTransport(packed.stream,profile);primarySchedule=buildFrameSchedule(transport,{dataOnly:false,pass:0});const rescuePasses=profile.key==='robust'?2:1;rescueSchedules=Array.from({length:rescuePasses},(_,i)=>buildFrameSchedule(transport,{dataOnly:true,pass:i+1}));const baseline=Math.ceil(packed.originalBytes/profile.payloadBytes);$('#mOriginal').textContent=humanBytes(packed.originalBytes);$('#mPacked').textContent=humanBytes(packed.stream.length);$('#mCompression').textContent=packed.meta.codec==='raw'?'pass-through':`${(packed.originalBytes/packed.packedBytes).toFixed(2)}× gzip`;$('#mCollapse').textContent=`${baseline} → ${transport.dataCount}`;$('#mPayload').textContent=humanBytes(profile.payloadBytes);$('#mFec').textContent=`RS ${profile.k}+${profile.r} · ${rescuePasses} rescate${rescuePasses>1?'s':''}`;$('#startTxBtn').disabled=false;$('#txPlaceholder').classList.add('hidden');renderDiscoveryFrame($('#txCanvas'),profile,0);$('#tGain').textContent=`${(packed.originalBytes/packed.stream.length).toFixed(2)}×`;log(`LIGHTHOUSE listo: ${profile.cols}×${profile.rows}, ${profile.bits} bit/celda, ${profile.payloadBytes} B/frame. Primary interleaved=${primarySchedule.length}; rescates=${rescueSchedules.map(x=>x.length).join('+')}.`);}catch(err){log(`ERROR: ${err.message}`);alert(err.message);}finally{btn.disabled=false;btn.textContent='Analizar y preparar';}};
function renderScheduled(frameIndex){const frame=transport.frames[frameIndex];renderOpticalFrame($('#txCanvas'),frame,transport,profile,frameIndex,transport.frames.length);$('#tFrame').textContent=`${tx.phaseLabel} ${tx.scheduleIndex+1}/${tx.schedule.length}`;tx.sent++;$('#txProgress').style.width=`${Math.min(100,tx.sent/tx.totalPlanned*100)}%`;const fps=+$('#fpsSelect').value,gross=profile.payloadBytes*fps,net=gross*(profile.k/(profile.k+profile.r))*profile.efficiency;$('#tGross').textContent=fmtRate(gross);$('#tRate').textContent=fmtRate(net);}
function enterEmissionMode(){document.body.classList.add('tx-active');$('#txExitBtn').hidden=false;try{screen.orientation?.lock?.('portrait');}catch{}try{if(!document.fullscreenElement)$('#txStage').requestFullscreen?.();}catch{}}
function exitEmissionMode(){document.body.classList.remove('tx-active');$('#txExitBtn').hidden=true;try{if(document.fullscreenElement)document.exitFullscreen?.();}catch{}}
function stopTx(status='DETENIDO'){tx.running=false;cancelAnimationFrame(tx.raf);$('#txStatus').textContent=status;$('#pauseTxBtn').disabled=true;exitEmissionMode();}
function startPhase(index,now){tx.phaseIndex=index;tx.scheduleIndex=0;tx.framesSinceBeacon=0;tx.last=0;if(index===0){tx.schedule=primarySchedule;tx.phaseLabel='P';$('#txStatus').textContent='EMITIENDO';}else{tx.schedule=rescueSchedules[index-1];tx.phaseLabel=`R${index}`;$('#txStatus').textContent=`RESCATE ${index}/${rescueSchedules.length}`;}tx.beaconUntil=now+180;renderDiscoveryFrame($('#txCanvas'),profile,tx.phase++);}
function advancePhase(now){const next=tx.phaseIndex+1;if(next<=rescueSchedules.length){startPhase(next,now);return true;}stopTx('COMPLETO + RESCATE');return false;}
function txLoop(now){if(!tx.running)return;const canvas=$('#txCanvas');if(now<tx.discoveryUntil){if(!tx.last||now-tx.last>75){tx.last=now;renderDiscoveryFrame(canvas,profile,tx.phase++);$('#txStatus').textContent='LIGHTHOUSE';}tx.raf=requestAnimationFrame(txLoop);return;}if(now<tx.beaconUntil){if(!tx.last||now-tx.last>70){tx.last=now;renderDiscoveryFrame(canvas,profile,tx.phase++);}tx.raf=requestAnimationFrame(txLoop);return;}const interval=1000/+$('#fpsSelect').value;if(!tx.last||now-tx.last>=interval){tx.last=now;if(tx.framesSinceBeacon>=HDP.beaconEvery){tx.beaconUntil=now+HDP.beaconHoldMs;tx.framesSinceBeacon=0;renderDiscoveryFrame(canvas,profile,tx.phase++);$('#txStatus').textContent=tx.phaseIndex===0?'RELOCK':`RESCATE ${tx.phaseIndex}/${rescueSchedules.length}`;}else{const frameIndex=tx.schedule[tx.scheduleIndex];renderScheduled(frameIndex);tx.scheduleIndex++;tx.framesSinceBeacon++;if(tx.scheduleIndex>=tx.schedule.length){if(!advancePhase(now))return;}}}tx.raf=requestAnimationFrame(txLoop);}
$('#startTxBtn').onclick=()=>{if(!transport)return;const totalPlanned=primarySchedule.length+rescueSchedules.reduce((n,s)=>n+s.length,0);tx={running:true,schedule:primarySchedule,scheduleIndex:0,phaseIndex:0,phaseLabel:'P',framesSinceBeacon:0,raf:0,last:0,discoveryUntil:performance.now()+HDP.discoveryMs,beaconUntil:0,phase:0,sent:0,totalPlanned};$('#txStatus').className='status-dot live';$('#txStatus').textContent='LIGHTHOUSE';$('#pauseTxBtn').disabled=false;$('#pauseTxBtn').textContent='Pausar';enterEmissionMode();tx.raf=requestAnimationFrame(txLoop);log(`TX iniciado: interleaving slot-major + ${rescueSchedules.length} pasada(s) sistemática(s) de rescate.`);};
$('#pauseTxBtn').onclick=()=>{tx.running=!tx.running;if(tx.running){tx.last=0;$('#pauseTxBtn').textContent='Pausar';tx.raf=requestAnimationFrame(txLoop);}else{cancelAnimationFrame(tx.raf);$('#pauseTxBtn').textContent='Continuar';$('#txStatus').textContent='PAUSA';}};
$('#fullTxBtn').onclick=enterEmissionMode;$('#txExitBtn').onclick=()=>stopTx('DETENIDO');document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&tx.running)document.body.classList.add('tx-active');});
let media=null,tracker=null,rxActive=false,assembling=false;const rxSession=new ReceiverSession();
async function onDecoded(decoded){if(!rxActive)return;const p=rxSession.ingest(decoded);if(!p)return;$('#rFrames').textContent=`${p.have}/${p.total}`;$('#rRecovered').textContent=p.recovered;$('#rBer').textContent=p.complete?'CRC OK · completo':`CRC OK · faltan ${p.missing}`;$('#rxProgress').style.width=`${Math.round(p.ratio*100)}%`;$('#rxHint').textContent=p.complete?'Transferencia completa. Verificando SHA-256…':`LOCK · ${Math.round(p.ratio*100)}% · faltan ${p.missing} bloque${p.missing===1?'':'s'} en ${p.pendingGroups} grupo${p.pendingGroups===1?'':'s'}`;if(p.complete&&!assembling){assembling=true;try{const {meta,data}=await rxSession.assemble(),blob=new Blob([data],{type:meta.type}),url=URL.createObjectURL(blob),box=$('#receivedFile');box.classList.remove('hidden');box.innerHTML=`<strong>${meta.name}</strong><br><span>${humanBytes(data.length)} · SHA-256 OK</span><br><a href="${url}" download="${meta.name}">Guardar archivo recibido</a>`;$('#rxStatus').textContent='COMPLETO';log(`Archivo reconstruido: ${meta.name}; recuperados FEC=${p.recovered}; duplicados útiles de rescate=${p.duplicates}.`);rxActive=false;$('#receiveBtn').textContent='Comenzar recepción';}catch(err){log(`Reconstrucción: ${err.message}`);}finally{assembling=false;}}}
$('#cameraBtn').onclick=async()=>{try{if(media){media.getTracks().forEach(t=>t.stop());media=null;tracker?.stop();rxActive=false;$('#cameraBtn').textContent='Iniciar cámara';$('#receiveBtn').disabled=true;$('#receiveBtn').textContent='Comenzar recepción';return;}media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:60}},audio:false});const v=$('#rxVideo');v.srcObject=media;await v.play();const stage=$('#cameraStage');if(stage)stage.style.aspectRatio=`${v.videoWidth}/${v.videoHeight}`;const track=media.getVideoTracks()[0];try{const caps=track.getCapabilities?.()||{},adv=[];if(caps.focusMode?.includes('continuous'))adv.push({focusMode:'continuous'});if(caps.exposureMode?.includes('continuous'))adv.push({exposureMode:'continuous'});if(caps.whiteBalanceMode?.includes('continuous'))adv.push({whiteBalanceMode:'continuous'});if(adv.length)await track.applyConstraints({advanced:adv});}catch{}tracker=new CameraTracker(v,$('#rxOverlay'),q=>{const pct=Math.round(q.lock*100);$('#rLock').textContent=`${pct}%`;$('#rxStatus').textContent=q.lock>.62?'LIGHTHOUSE LOCK':'BUSCANDO BALIZAS';$('#rxStatus').className=`status-dot ${q.lock>.62?'live':'idle'}`;if(q.lock<=.62&&!rxSession.streamLength)$('#rxHint').textContent='Busca 4 balizas: magenta, cian, amarillo y verde.';},onDecoded);tracker.start();rxActive=true;$('#cameraBtn').textContent='Apagar cámara';$('#receiveBtn').disabled=false;$('#receiveBtn').textContent='Detener recepción';log('Receptor HDP v2 activo. Ahora informa bloques faltantes y aprovecha las pasadas de rescate.');}catch(err){log(`Cámara: ${err.message}`);alert('No se pudo abrir la cámara. Revisa permisos y HTTPS.');}};
$('#receiveBtn').onclick=()=>{rxActive=!rxActive;$('#receiveBtn').textContent=rxActive?'Detener recepción':'Comenzar recepción';};$('#resetRxBtn').onclick=()=>{rxSession.reset();assembling=false;$('#rFrames').textContent='0';$('#rRecovered').textContent='0';$('#rBer').textContent='—';$('#rxProgress').style.width='0%';$('#receivedFile').classList.add('hidden');};window.addEventListener('beforeunload',()=>media?.getTracks().forEach(t=>t.stop()));log('HDP v2.1: Lighthouse + burst-safe interleaving + FEC final-group fix + automatic rescue passes.');
