import { packFile,buildTransport,humanBytes } from './src/superstream.js';
import { resolveProfile,renderOpticalFrame,renderDiscoveryFrame,HDP } from './src/optical2.js';
import { CameraTracker,ReceiverSession } from './src/receiver2.js';
const $=s=>document.querySelector(s),logEl=$('#diagnostics');
function log(msg){const t=new Date().toLocaleTimeString();if(logEl)logEl.textContent=`[${t}] ${msg}\n`+(logEl.textContent||'').slice(0,7000);}function fmtRate(n){return `${(n/1024).toFixed(n/1024>=100?0:1)} KB/s`;}
let file=null,packed=null,transport=null,profile=null;
let tx={running:false,dataIndex:0,framesSinceBeacon:0,raf:0,last:0,discoveryUntil:0,beaconUntil:0,phase:0};
for(const b of document.querySelectorAll('.tab'))b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab)?.classList.add('active');};
$('#fileInput').onchange=e=>setFile(e.target.files[0]);const dz=$('#dropzone');dz.ondragover=e=>e.preventDefault();dz.ondrop=e=>{e.preventDefault();setFile(e.dataTransfer.files[0]);};
function setFile(f){if(!f)return;file=f;$('#fileState').textContent=`${f.name} · ${humanBytes(f.size)}`;$('#prepareBtn').disabled=false;log(`Archivo seleccionado: ${f.name} (${f.size} B)`);}
function currentProfile(){return resolveProfile($('#profileSelect').value,$('#gridSelect').value);}function updateBench(){const p=currentProfile(),fps=+$('#fpsSelect').value,gross=p.payloadCells*p.bits*fps/8,fec=p.k/(p.k+p.r),net=gross*p.efficiency*fec;$('#bCells').textContent=p.payloadCells.toLocaleString();$('#bBpc').textContent=p.bits;$('#bGross').textContent=fmtRate(gross);$('#bNet').textContent=fmtRate(net);}function syncAspect(){const p=currentProfile();$('#txStage').style.aspectRatio=`${p.cols}/${p.rows}`;}['profileSelect','gridSelect','fpsSelect'].forEach(id=>$('#'+id).onchange=()=>{updateBench();syncAspect();});updateBench();syncAspect();
$('#prepareBtn').onclick=async()=>{if(!file)return;const btn=$('#prepareBtn');btn.disabled=true;btn.textContent='Preparando…';try{profile=currentProfile();packed=await packFile(file);profile.payloadBytes=Math.min(profile.payloadBytes,65535);transport=buildTransport(packed.stream,profile);const baseline=Math.ceil(packed.originalBytes/profile.payloadBytes);$('#mOriginal').textContent=humanBytes(packed.originalBytes);$('#mPacked').textContent=humanBytes(packed.stream.length);$('#mCompression').textContent=packed.meta.codec==='raw'?'pass-through':`${(packed.originalBytes/packed.packedBytes).toFixed(2)}× gzip`;$('#mCollapse').textContent=`${baseline} → ${transport.dataCount}`;$('#mPayload').textContent=humanBytes(profile.payloadBytes);$('#mFec').textContent=`RS ${profile.k}+${profile.r}`;$('#startTxBtn').disabled=false;$('#txPlaceholder').classList.add('hidden');renderDiscoveryFrame($('#txCanvas'),profile,0);$('#tGain').textContent=`${(packed.originalBytes/packed.stream.length).toFixed(2)}×`;log(`LIGHTHOUSE listo: ${profile.cols}×${profile.rows}, ${profile.bits} bit/celda, ${profile.payloadBytes} B/frame.`);}catch(err){log(`ERROR: ${err.message}`);alert(err.message);}finally{btn.disabled=false;btn.textContent='Analizar y preparar';}};
function renderData(i){const frame=transport.frames[i];renderOpticalFrame($('#txCanvas'),frame,transport,profile,i,transport.frames.length);$('#tFrame').textContent=`${i+1}/${transport.frames.length}`;$('#txProgress').style.width=`${((i+1)/transport.frames.length)*100}%`;const fps=+$('#fpsSelect').value,gross=profile.payloadBytes*fps,net=gross*(profile.k/(profile.k+profile.r))*profile.efficiency;$('#tGross').textContent=fmtRate(gross);$('#tRate').textContent=fmtRate(net);}
function enterEmissionMode(){document.body.classList.add('tx-active');$('#txExitBtn').hidden=false;try{screen.orientation?.lock?.('portrait');}catch{}try{if(!document.fullscreenElement)$('#txStage').requestFullscreen?.();}catch{}}
function exitEmissionMode(){document.body.classList.remove('tx-active');$('#txExitBtn').hidden=true;try{if(document.fullscreenElement)document.exitFullscreen?.();}catch{}}
function stopTx(status='DETENIDO'){tx.running=false;cancelAnimationFrame(tx.raf);$('#txStatus').textContent=status;$('#pauseTxBtn').disabled=true;exitEmissionMode();}
function txLoop(now){if(!tx.running)return;const canvas=$('#txCanvas');if(now<tx.discoveryUntil){if(!tx.last||now-tx.last>75){tx.last=now;renderDiscoveryFrame(canvas,profile,tx.phase++);$('#txStatus').textContent='LIGHTHOUSE';}tx.raf=requestAnimationFrame(txLoop);return;}if(now<tx.beaconUntil){if(!tx.last||now-tx.last>60){tx.last=now;renderDiscoveryFrame(canvas,profile,tx.phase++);$('#txStatus').textContent='RELOCK';}tx.raf=requestAnimationFrame(txLoop);return;}const interval=1000/+$('#fpsSelect').value;if(!tx.last||now-tx.last>=interval){tx.last=now;if(tx.framesSinceBeacon>=HDP.beaconEvery){tx.beaconUntil=now+HDP.beaconHoldMs;tx.framesSinceBeacon=0;renderDiscoveryFrame(canvas,profile,tx.phase++);$('#txStatus').textContent='RELOCK';}else{renderData(tx.dataIndex);tx.dataIndex++;tx.framesSinceBeacon++;$('#txStatus').textContent='EMITIENDO';if(tx.dataIndex>=transport.frames.length){stopTx('COMPLETO');return;}}}tx.raf=requestAnimationFrame(txLoop);}
$('#startTxBtn').onclick=()=>{if(!transport)return;tx={running:true,dataIndex:0,framesSinceBeacon:0,raf:0,last:0,discoveryUntil:performance.now()+HDP.discoveryMs,beaconUntil:0,phase:0};$('#txStatus').className='status-dot live';$('#pauseTxBtn').disabled=false;$('#pauseTxBtn').textContent='Pausar';enterEmissionMode();tx.raf=requestAnimationFrame(txLoop);};
$('#pauseTxBtn').onclick=()=>{tx.running=!tx.running;if(tx.running){tx.last=0;$('#pauseTxBtn').textContent='Pausar';tx.raf=requestAnimationFrame(txLoop);}else{cancelAnimationFrame(tx.raf);$('#pauseTxBtn').textContent='Continuar';$('#txStatus').textContent='PAUSA';}};
$('#fullTxBtn').onclick=enterEmissionMode;$('#txExitBtn').onclick=()=>stopTx('DETENIDO');document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&tx.running)document.body.classList.add('tx-active');});
let media=null,tracker=null,rxActive=false,assembling=false;const rxSession=new ReceiverSession();
async function onDecoded(decoded){if(!rxActive)return;const p=rxSession.ingest(decoded);if(!p)return;$('#rFrames').textContent=rxSession.frames.size;$('#rRecovered').textContent=p.recovered;$('#rBer').textContent='CRC OK';$('#rxProgress').style.width=`${Math.round(p.ratio*100)}%`;$('#rxHint').textContent=`LOCK · ${Math.round(p.ratio*100)}% recibido`;if(p.complete&&!assembling){assembling=true;try{const {meta,data}=await rxSession.assemble(),blob=new Blob([data],{type:meta.type}),url=URL.createObjectURL(blob),box=$('#receivedFile');box.classList.remove('hidden');box.innerHTML=`<strong>${meta.name}</strong><br><span>${humanBytes(data.length)} · SHA-256 OK</span><br><a href="${url}" download="${meta.name}">Guardar archivo recibido</a>`;$('#rxStatus').textContent='COMPLETO';log(`Archivo reconstruido: ${meta.name}`);rxActive=false;$('#receiveBtn').textContent='Comenzar recepción';}catch(err){log(`Reconstrucción: ${err.message}`);}finally{assembling=false;}}}
$('#cameraBtn').onclick=async()=>{try{if(media){media.getTracks().forEach(t=>t.stop());media=null;tracker?.stop();rxActive=false;$('#cameraBtn').textContent='Iniciar cámara';$('#receiveBtn').disabled=true;$('#receiveBtn').textContent='Comenzar recepción';return;}media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:60}},audio:false});const v=$('#rxVideo');v.srcObject=media;await v.play();const stage=$('#cameraStage');if(stage)stage.style.aspectRatio=`${v.videoWidth}/${v.videoHeight}`;const track=media.getVideoTracks()[0];try{const caps=track.getCapabilities?.()||{},adv=[];if(caps.focusMode?.includes('continuous'))adv.push({focusMode:'continuous'});if(caps.exposureMode?.includes('continuous'))adv.push({exposureMode:'continuous'});if(caps.whiteBalanceMode?.includes('continuous'))adv.push({whiteBalanceMode:'continuous'});if(adv.length)await track.applyConstraints({advanced:adv});}catch{}tracker=new CameraTracker(v,$('#rxOverlay'),q=>{const pct=Math.round(q.lock*100);$('#rLock').textContent=`${pct}%`;$('#rxStatus').textContent=q.lock>.62?'LIGHTHOUSE LOCK':'BUSCANDO BALIZAS';$('#rxStatus').className=`status-dot ${q.lock>.62?'live':'idle'}`;$('#rxHint').textContent=q.lock>.62?'Balizas detectadas. Mantén los teléfonos estables.':'Busca 4 balizas: magenta, cian, amarillo y verde.';},onDecoded);tracker.start();rxActive=true;$('#cameraBtn').textContent='Apagar cámara';$('#receiveBtn').disabled=false;$('#receiveBtn').textContent='Detener recepción';log('Receptor HDP v2 activo: detección por 4 balizas grandes, no por el borde del teléfono.');}catch(err){log(`Cámara: ${err.message}`);alert('No se pudo abrir la cámara. Revisa permisos y HTTPS.');}};
$('#receiveBtn').onclick=()=>{rxActive=!rxActive;$('#receiveBtn').textContent=rxActive?'Detener recepción':'Comenzar recepción';};$('#resetRxBtn').onclick=()=>{rxSession.reset();assembling=false;$('#rFrames').textContent='0';$('#rRecovered').textContent='0';$('#rBer').textContent='—';$('#rxProgress').style.width='0%';$('#receivedFile').classList.add('hidden');};window.addEventListener('beforeunload',()=>media?.getTracks().forEach(t=>t.stop()));log('HDP v2 LIGHTHOUSE cargado. Perfil inicial conservador para validar hardware real.');
