(() => {
'use strict';

// HAC5 Reliable Control
// Receiver speaker -> sender microphone, with optional rear torch -> sender selfie sync.
// Voice-band DTMF carries the exact NACK/COMPLETE message in CRC-protected fixed blocks.
const VERSION=5, MAGIC=[0x48,0x41,0x43,0x35]; // HAC5
const TYPE={NACK:1,COMPLETE:2};
const LOW=[697,770,852,941], HIGH=[1209,1336,1477,1633];
const MARK_NIBBLE=0x3; // 697 + 1633, held much longer than a normal symbol.
const SYMBOL_MS=56, TONE_MS=38, MARK_MS=280, MARK_GAP_MS=150, BLOCK_GAP_MS=190, LEAD_MS=700;
const BLOCK_PAYLOAD=64, BLOCK_BYTES=78, PARITY_INDEX=255;
let outCtx=null,micCtx=null,micStream=null,micSource=null,analyser=null,silentGain=null,listenToken=0,selfieAllowed=false;

const $=id=>document.getElementById(id);
function setStatus(text,kind=''){const e=$('controlChannelStatus');if(e){e.textContent=text;e.className='chip '+kind;}}
function setOverlay(text){const o=$('streamOverlay'),e=$('streamBottom');if(e&&o&&o.style.display!=='none')e.textContent=text;}
function alog(msg){const e=$('sendLog');if(!e)return;const t=new Date().toLocaleTimeString();e.textContent=`[${t}] HAC5 · ${msg}\n`+e.textContent.slice(0,8500);}
function emit(name,detail={}){try{window.dispatchEvent(new CustomEvent('hopper:acoustic-'+name,{detail}));}catch{}}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function u16(n){return[(n>>>8)&255,n&255];} function u32(n){return[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255];}
function readU16(a,o){return(a[o]<<8)|a[o+1];} function readU32(a,o){return((((a[o]<<24)>>>0)|(a[o+1]<<16)|(a[o+2]<<8)|a[o+3])>>>0);}
function concat(...arrs){const n=arrs.reduce((s,a)=>s+a.length,0),o=new Uint8Array(n);let p=0;for(const a of arrs){o.set(a,p);p+=a.length;}return o;}

const crcTable=(()=>{const t=new Uint32Array(256);for(let i=0;i<256;i++){let c=i;for(let k=0;k<8;k++)c=(c&1)?0xEDB88320^(c>>>1):c>>>1;t[i]=c>>>0;}return t;})();
function crc32(bytes){let c=0xFFFFFFFF;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xFFFFFFFF)>>>0;}
function crc16(bytes){let c=0xFFFF;for(const b of bytes){c^=b<<8;for(let i=0;i<8;i++)c=(c&0x8000)?((c<<1)^0x1021)&0xFFFF:(c<<1)&0xFFFF;}return c;}

function putVar(out,n){n>>>=0;while(n>=128){out.push((n&127)|128);n>>>=7;}out.push(n);}
function getVar(a,st){let n=0,s=0;while(st.p<a.length&&s<=28){const b=a[st.p++];n|=(b&127)<<s;if(!(b&128))return n>>>0;s+=7;}throw new Error('varint');}
function encodeDelta(list){const out=[0];putVar(out,list.length);let prev=-1;for(const idx of list){putVar(out,idx-prev-1);prev=idx;}return new Uint8Array(out);}
function encodeRanges(list){const runs=[];for(let i=0;i<list.length;){let s=list[i],e=s;i++;while(i<list.length&&list[i]===e+1)e=list[i++];runs.push([s,e-s+1]);}const out=[1];putVar(out,runs.length);let prev=-1;for(const [s,len] of runs){putVar(out,s-prev-1);putVar(out,len);prev=s+len-1;}return new Uint8Array(out);}
function bitsToBytes(bits){const out=new Uint8Array(Math.ceil(bits.length/8));for(let i=0;i<bits.length;i++)if(bits[i])out[i>>3]|=1<<(7-(i&7));return out;}
function bytesToBits(a,offset=0){const out=[];for(let i=offset;i<a.length;i++)for(let k=7;k>=0;k--)out.push((a[i]>>k)&1);return out;}
function encodeRice(list,k){const bits=[];let prev=-1;for(const idx of list){const d=idx-prev-1,q=d>>k,r=d&((1<<k)-1);for(let i=0;i<q;i++)bits.push(1);bits.push(0);for(let b=k-1;b>=0;b--)bits.push((r>>b)&1);prev=idx;}const head=[2,k];putVar(head,list.length);return concat(new Uint8Array(head),bitsToBytes(bits));}
function decodeRice(a,total){const st={p:2},count=getVar(a,st),bits=bytesToBits(a,st.p),out=[];let bp=0,prev=-1,k=a[1];for(let i=0;i<count;i++){let q=0;while(bp<bits.length&&bits[bp++]===1)q++;if(bp>bits.length)throw new Error('rice');let r=0;for(let b=0;b<k;b++){if(bp>=bits.length)throw new Error('rice');r=(r<<1)|bits[bp++];}const idx=prev+1+(q<<k)+r;if(idx>=total)throw new Error('rice index');out.push(idx);prev=idx;}return out;}
function compressMissing(list){const s=Array.from(new Set(list)).sort((a,b)=>a-b),candidates=[encodeDelta(s),encodeRanges(s)];for(let k=2;k<=7;k++)candidates.push(encodeRice(s,k));return candidates.reduce((a,b)=>b.length<a.length?b:a);}
function decompressMissing(payload,total){if(!payload.length)return[];if(payload[0]===2)return decodeRice(payload,total);const st={p:1},out=[];if(payload[0]===0){const n=getVar(payload,st);let prev=-1;for(let i=0;i<n;i++){const idx=prev+1+getVar(payload,st);if(idx>=total)throw new Error('missing index');out.push(idx);prev=idx;}}else if(payload[0]===1){const n=getVar(payload,st);let prev=-1;for(let i=0;i<n;i++){const s=prev+1+getVar(payload,st),len=getVar(payload,st);if(s+len>total)throw new Error('missing range');for(let j=0;j<len;j++)out.push(s+j);prev=s+len-1;}}else throw new Error('codec');return out;}

function makePacket(type,{session,round=0,bits=3,total=0,fileCrc=0,missing=[]}){const payload=type===TYPE.NACK?compressMissing(missing):new Uint8Array(0),h=new Uint8Array(23);h.set(MAGIC,0);h[4]=VERSION;h[5]=type;h.set(u32(session>>>0),6);h.set(u16(round),10);h[12]=bits;h.set(u32(total>>>0),13);h.set(u32(fileCrc>>>0),17);h.set(u16(payload.length),21);const body=concat(h,payload);return concat(body,new Uint8Array(u32(crc32(body))));}
function parsePacket(a,off=0){if(a.length-off<27)return null;for(let i=0;i<4;i++)if(a[off+i]!==MAGIC[i])return null;if(a[off+4]!==VERSION)return null;const type=a[off+5],session=readU32(a,off+6),round=readU16(a,off+10),bits=a[off+12],total=readU32(a,off+13),fileCrc=readU32(a,off+17),len=readU16(a,off+21),need=27+len;if(type!==TYPE.NACK&&type!==TYPE.COMPLETE)return null;if(a.length-off<need)return{pending:true,need};const body=a.slice(off,off+23+len),expected=readU32(a,off+23+len);if(crc32(body)!==expected)return{bad:true,need};let missing=[];try{if(type===TYPE.NACK)missing=decompressMissing(a.slice(off+23,off+23+len),total);}catch{return{bad:true,need};}return{ok:true,need,type,session,round,bits,total,fileCrc,missing,payloadBytes:len};}

function sessionTag(session,round,fileCrc){return(((session>>>16)^(session&0xFFFF)^(fileCrc>>>16)^(fileCrc&0xFFFF)^round)&0xFFFF);}
function buildBlocks(message,{session,round,fileCrc}){const count=Math.ceil(message.length/BLOCK_PAYLOAD);if(count>254)throw new Error('NACK acústico demasiado grande');const tag=sessionTag(session,round,fileCrc),blocks=[],xor=new Uint8Array(BLOCK_PAYLOAD);for(let i=0;i<count;i++){const part=message.slice(i*BLOCK_PAYLOAD,Math.min(message.length,(i+1)*BLOCK_PAYLOAD)),b=new Uint8Array(BLOCK_BYTES);b[0]=0xB5;b[1]=0x5B;b.set(u16(tag),2);b.set(u16(round),4);b[6]=i;b[7]=count;b[8]=part.length;b.set(u16(message.length),9);b[11]=0; b.set(part,12);for(let j=0;j<BLOCK_PAYLOAD;j++)xor[j]^=b[12+j];const c=crc16(b.slice(0,76));b.set(u16(c),76);blocks.push(b);}if(count>1){const p=new Uint8Array(BLOCK_BYTES);p[0]=0xB5;p[1]=0x5B;p.set(u16(tag),2);p.set(u16(round),4);p[6]=PARITY_INDEX;p[7]=count;p[8]=BLOCK_PAYLOAD;p.set(u16(message.length),9);p[11]=1;p.set(xor,12);p.set(u16(crc16(p.slice(0,76))),76);blocks.push(p);}return blocks;}
function parseBlock(b,{session,round,fileCrc}){if(b.length!==BLOCK_BYTES||b[0]!==0xB5||b[1]!==0x5B)return null;if(readU16(b,2)!==sessionTag(session,round,fileCrc)||readU16(b,4)!==round)return null;if(readU16(b,76)!==crc16(b.slice(0,76)))return null;const idx=b[6],count=b[7],len=b[8],totalLen=readU16(b,9),flags=b[11];if(!count||len>BLOCK_PAYLOAD||totalLen<27||totalLen>count*BLOCK_PAYLOAD)return null;if(idx!==PARITY_INDEX&&idx>=count)return null;return{idx,count,len,totalLen,parity:!!(flags&1),payload:b.slice(12,12+BLOCK_PAYLOAD)};}
function assembleBlocks(map,parity,meta){if(!meta)return null;const missing=[];for(let i=0;i<meta.count;i++)if(!map.has(i))missing.push(i);if(missing.length===1&&parity){const rec=parity.payload.slice();for(let i=0;i<meta.count;i++)if(i!==missing[0]&&map.has(i)){const p=map.get(i).payload;for(let j=0;j<BLOCK_PAYLOAD;j++)rec[j]^=p[j];}const idx=missing[0],len=Math.min(BLOCK_PAYLOAD,meta.totalLen-idx*BLOCK_PAYLOAD);map.set(idx,{idx,count:meta.count,len,totalLen:meta.totalLen,payload:rec});missing.length=0;}if(missing.length)return null;const parts=[];for(let i=0;i<meta.count;i++){const b=map.get(i);parts.push(b.payload.slice(0,Math.min(b.len,meta.totalLen-i*BLOCK_PAYLOAD)));}return concat(...parts).slice(0,meta.totalLen);}

async function unlockSpeaker(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw new Error('Web Audio no disponible');if(!outCtx)outCtx=new AC({latencyHint:'interactive'});if(outCtx.state==='suspended')await outCtx.resume();return outCtx;}
function micTrackLive(){const t=micStream?.getAudioTracks?.()[0];return!!t&&t.readyState==='live';}
async function preflightSelfie(){if(selfieAllowed||!navigator.mediaDevices?.getUserMedia)return selfieAllowed;try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'user'},width:{ideal:320},height:{ideal:240},frameRate:{ideal:10}},audio:false});s.getTracks().forEach(t=>t.stop());selfieAllowed=true;alog('selfie autorizada para FlashSync.');}catch(e){alog(`FlashSync selfie no disponible: ${e.message}`);}return selfieAllowed;}
async function ensureSenderMic(){if(micStream&&analyser&&micCtx&&micTrackLive()){if(micCtx.state!=='running')try{await micCtx.resume();}catch{};if(micCtx.state==='running'){await preflightSelfie();setStatus('HAC5 · MIC LISTO','on');return true;}stopMic();}if(!navigator.mediaDevices?.getUserMedia)throw new Error('Micrófono no disponible');setStatus('HAC5 · PIDIENDO MIC…','mid');micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false,channelCount:1},video:false});const AC=window.AudioContext||window.webkitAudioContext;micCtx=new AC({latencyHint:'interactive'});if(micCtx.state==='suspended')await micCtx.resume();micSource=micCtx.createMediaStreamSource(micStream);analyser=micCtx.createAnalyser();analyser.fftSize=1024;analyser.smoothingTimeConstant=0;analyser.minDecibels=-100;analyser.maxDecibels=-10;silentGain=micCtx.createGain();silentGain.gain.value=1e-7;micSource.connect(analyser);analyser.connect(silentGain);silentGain.connect(micCtx.destination);await preflightSelfie();setStatus('HAC5 · MIC LISTO','on');alog(`micrófono HAC5 listo · ${micCtx.sampleRate} Hz`);return true;}
function stopMic(){listenToken++;try{micStream?.getTracks?.().forEach(t=>t.stop());}catch{}try{micSource?.disconnect?.();analyser?.disconnect?.();silentGain?.disconnect?.();}catch{}micStream=null;micSource=null;analyser=null;silentGain=null;try{micCtx?.close?.();}catch{}micCtx=null;}

function dbAt(data,f,sr,fft){const bin=Math.round(f*fft/sr);return data[Math.max(0,Math.min(data.length-1,bin))]??-120;}
function top2(a){let a1=0,a2=1;if(a[1]>a[0]){a1=1;a2=0;}for(let i=2;i<a.length;i++){if(a[i]>a[a1]){a2=a1;a1=i;}else if(a[i]>a[a2])a2=i;}return[a1,a2];}
function classifyNibble(freq,sr,fft){const l=LOW.map(f=>dbAt(freq,f,sr,fft)),h=HIGH.map(f=>dbAt(freq,f,sr,fft)),[li,l2]=top2(l),[hi,h2]=top2(h),lm=l[li]-l[l2],hm=h[hi]-h[h2],strength=Math.min(l[li],h[hi]),active=strength>-72&&lm>2.0&&hm>2.0;return{active,nibble:(li<<2)|hi,strength,margin:Math.min(lm,hm)};}
function isMarker(d){return d.active&&d.nibble===MARK_NIBBLE;}

function blockToNibbles(b){const out=[];for(const x of b)out.push((x>>>4)&15,x&15);return out;}
function addTone(d,sr,start,dur,fl,fh,amp=.18){const fade=Math.max(8,Math.round(sr*.002)),nmax=Math.round(sr*dur/1000);for(let n=0;n<nmax;n++){const t=n/sr,env=Math.min(1,n/fade,(nmax-1-n)/fade),p=start+n;if(p>=d.length)break;d[p]+=(amp*Math.sin(2*Math.PI*fl*t)+amp*Math.sin(2*Math.PI*fh*t))*env;}}
function buildAudio(blocks,repeats=1){const ctx=outCtx,sr=ctx.sampleRate,sym=Math.round(sr*SYMBOL_MS/1000),tone=Math.round(sr*TONE_MS/1000),mark=Math.round(sr*MARK_MS/1000),mgap=Math.round(sr*MARK_GAP_MS/1000),bgap=Math.round(sr*BLOCK_GAP_MS/1000),lead=Math.round(sr*LEAD_MS/1000),per=mark+mgap+BLOCK_BYTES*2*sym+bgap,total=lead+blocks.length*per*repeats+Math.round(sr*.2),buf=ctx.createBuffer(1,total,sr),d=buf.getChannelData(0);let cur=lead;for(let r=0;r<repeats;r++)for(const b of blocks){const mr=(MARK_NIBBLE>>>2)&3,mc=MARK_NIBBLE&3;addTone(d,sr,cur,MARK_MS,LOW[mr],HIGH[mc],.20);cur+=mark+mgap;for(const nib of blockToNibbles(b)){const row=(nib>>>2)&3,col=nib&3;addTone(d,sr,cur,TONE_MS,LOW[row],HIGH[col],.18);cur+=sym;}cur+=bgap;}return buf;}
async function torchSync(pulses=3){const track=$('video')?.srcObject?.getVideoTracks?.()[0];if(!track)return false;try{const cap=track.getCapabilities?.()||{};if(!cap.torch)return false;for(let i=0;i<pulses;i++){await track.applyConstraints({advanced:[{torch:true}]});await sleep(120);await track.applyConstraints({advanced:[{torch:false}]});await sleep(100);}emit('flash-tx',{pulses});return true;}catch(e){try{await track.applyConstraints({advanced:[{torch:false}]});}catch{}return false;}}
async function monitorFlash(token){if(!selfieAllowed||!navigator.mediaDevices?.getUserMedia)return;let s=null;try{s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'user'},width:{ideal:320},height:{ideal:240},frameRate:{ideal:12}},audio:false});const v=document.createElement('video');v.playsInline=true;v.muted=true;v.srcObject=s;await v.play();const c=document.createElement('canvas');c.width=64;c.height=48;const x=c.getContext('2d',{willReadFrequently:true});let base=null,pulses=0,high=false;while(token===listenToken){x.drawImage(v,0,0,c.width,c.height);const a=x.getImageData(0,0,c.width,c.height).data;let sum=0;for(let i=0;i<a.length;i+=16)sum+=(a[i]+a[i+1]+a[i+2])/3;const avg=sum/(a.length/16);if(base==null)base=avg;else base=base*.97+avg*.03;const bright=avg>Math.max(base+28,base*1.45);if(bright&&!high){pulses++;high=true;if(pulses>=2){setOverlay(`HAC5 · FLASHSYNC ${pulses} · escuchando bloques…`);emit('flash-rx',{pulses});}}if(!bright)high=false;await sleep(45);}}catch{}finally{try{s?.getTracks?.().forEach(t=>t.stop());}catch{}}}
async function playMessage(packet,args,label){await unlockSpeaker();const blocks=buildBlocks(packet,args),repeats=blocks.length<=3?2:1;torchSync(label==='COMPLETE'?4:3).catch(()=>{});const buf=buildAudio(blocks,repeats),src=outCtx.createBufferSource();src.buffer=buf;src.connect(outCtx.destination);setStatus(`HAC5 · TX ${label}`,'mid');alog(`TX ${label} · mensaje ${packet.length} B · ${blocks.length} bloque(s) · ${repeats}x · ${buf.duration.toFixed(1)} s`);emit('tx-start',{label,messageBytes:packet.length,blocks:blocks.length,repeats,durationMs:buf.duration*1000});return new Promise((resolve,reject)=>{src.onended=()=>{setStatus('HAC5 · TX OK','on');resolve();};try{src.start();}catch(e){reject(e);}});}
async function sendNack(args){const packet=makePacket(TYPE.NACK,args);return playMessage(packet,args,`NACK ${args.missing?.length||0}`);}
async function sendComplete(args){const packet=makePacket(TYPE.COMPLETE,args);return playMessage(packet,args,'COMPLETE');}

async function listenControl({session,round=null,timeoutMs=150000}={}){await ensureSenderMic();if(!analyser||!micCtx||micCtx.state!=='running')throw new Error('DSP HAC5 no disponible');const token=++listenToken;monitorFlash(token);const sr=micCtx.sampleRate,fft=analyser.fftSize,freq=new Float32Array(analyser.frequencyBinCount),blocks=new Map();let parity=null,meta=null,markerSince=0,markerLocked=false,markerQuiet=0,collecting=false,armed=true,quiet=0,nibs=[],validBlocks=0,badBlocks=0,lastUi=0;setStatus('HAC5 · ESCUCHANDO','mid');setOverlay('HAC5 · esperando FlashSync / marcador acústico…');emit('listen-start',{session,round});return new Promise((resolve,reject)=>{let timer=null,timeout=null;const clean=()=>{if(timer)clearInterval(timer);if(timeout)clearTimeout(timeout);};const tryMessage=()=>{const msg=assembleBlocks(blocks,parity,meta);if(!msg)return false;const r=parsePacket(msg);if(!r?.ok)return false;if(r.session!==(session>>>0)||(round!=null&&r.round!==round))return false;clean();setStatus(`HAC5 · RX ${r.type===TYPE.NACK?'NACK':'COMPLETE'} OK`,'on');setOverlay(`HAC5 · ${r.type===TYPE.NACK?'NACK':'COMPLETE'} CRC OK · ${validBlocks} bloques`);alog(`RX ${r.type===TYPE.NACK?'NACK':'COMPLETE'} OK · ${validBlocks} bloques · ${badBlocks} descartados`);emit('rx-ok',{type:r.type,validBlocks,badBlocks,payloadBytes:r.payloadBytes});resolve(r);return true;};const acceptBlock=()=>{if(nibs.length!==BLOCK_BYTES*2)return;nibs=nibs.slice(0,BLOCK_BYTES*2);const b=new Uint8Array(BLOCK_BYTES);for(let i=0;i<b.length;i++)b[i]=(nibs[i*2]<<4)|nibs[i*2+1];const p=parseBlock(b,{session,round:round??readU16(b,4),fileCrc:0});/* retry with packet fileCrc unknown below */let pb=p;if(!pb){ // session tag includes file CRC; infer by accepting structure+CRC first, message CRC/session validates later.
  if(b[0]===0xB5&&b[1]===0x5B&&readU16(b,4)===(round??readU16(b,4))&&readU16(b,76)===crc16(b.slice(0,76))){pb={idx:b[6],count:b[7],len:b[8],totalLen:readU16(b,9),parity:!!(b[11]&1),payload:b.slice(12,76)};} }
if(!pb||!pb.count||pb.totalLen<27||pb.totalLen>pb.count*BLOCK_PAYLOAD){badBlocks++;return;}if(!meta)meta={count:pb.count,totalLen:pb.totalLen};if(meta.count!==pb.count||meta.totalLen!==pb.totalLen){badBlocks++;return;}if(pb.idx===PARITY_INDEX)parity=pb;else if(pb.idx<pb.count&&!blocks.has(pb.idx))blocks.set(pb.idx,pb);validBlocks++;tryMessage();};const scan=()=>{if(token!==listenToken){clean();return;}analyser.getFloatFrequencyData(freq);const d=classifyNibble(freq,sr,fft),now=performance.now();if(isMarker(d)){if(!markerSince)markerSince=now;if(now-markerSince>150)markerLocked=true;markerQuiet=0;}else{markerSince=0;if(markerLocked){markerQuiet++;if(markerQuiet>=2){markerLocked=false;markerQuiet=0;collecting=true;armed=true;quiet=0;nibs=[];setOverlay('HAC5 · marcador OK · recibiendo bloque…');}}}
if(collecting&&!markerLocked){if(!d.active){quiet++;if(quiet>=2)armed=true;}else{quiet=0;if(armed){armed=false;setTimeout(()=>{if(token!==listenToken||!analyser||!collecting)return;analyser.getFloatFrequencyData(freq);const q=classifyNibble(freq,sr,fft);if(q.active){nibs.push(q.nibble);if(nibs.length===BLOCK_BYTES*2){collecting=false;acceptBlock();}}},7);}}}
if(now-lastUi>220){lastUi=now;setOverlay(`HAC5 · ${d.active?'TONO':'silencio'} · bloque ${nibs.length}/${BLOCK_BYTES*2} · válidos ${validBlocks} · malos ${badBlocks}`);}};timer=setInterval(scan,7);timeout=setTimeout(()=>{clean();setStatus('HAC5 · TIMEOUT','off');reject(new Error(`Timeout HAC5 · ${validBlocks} bloques válidos · ${badBlocks} descartados`));},timeoutMs);});}

document.addEventListener('change',e=>{if(e.target?.id==='controlMode')setStatus(e.target.value==='acoustic'?'HAC5 · AUDIO + FLASHSYNC':'NACK MANUAL',e.target.value==='acoustic'?'mid':'on');});
document.addEventListener('click',e=>{if(e.target?.id==='cameraBtn')unlockSpeaker().catch(()=>{});},{capture:true});
window.addEventListener('pagehide',()=>stopMic());
window.HopperAcoustic={VERSION,TYPE,ensureSenderMic,stopMic,sendNack,sendComplete,listenControl,compressMissing,decompressMissing,makePacket,parsePacket,buildBlocks,assembleBlocks,crc16};
window.__hopperAcoustic={version:'0.9.7',protocol:'HAC5 Reliable DTMF + FlashSync',symbolMs:SYMBOL_MS,blockPayload:BLOCK_PAYLOAD};
})();