(() => {
'use strict';
const $=id=>document.getElementById(id);
const enc=new TextEncoder(),dec=new TextDecoder();
const LEVELS=[26,92,164,236];
const MAGIC=[0x48,0x50,0x53,0x34]; // HPS4
const VERSION=4;
const PILOT_CELLS=32;
const DATA_MIN=.12,DATA_MAX=.88;
const MARKER_NORM={tl:[.06,.06],tr:[.94,.06],bl:[.06,.94],br:[.94,.94]};
const MARKER_KEYS=['tl','tr','bl','br'];
const TARGET_HUES={tl:180,tr:300,bl:60,br:144};
const TYPE={DATA:1,PASS_END:2,CONTROL:3};
const CTRL={NACK:1,COMPLETE:2};
const CONTROL_EMIT_MS=6000;
const CONTROL_SETTLE_MS=550;
const SPEED_PROFILES={
 slow:{label:'Lenta',mult:1,fps:3,repeat:3,uniqueFps:1,hint:'Lenta: máxima estabilidad · 1 frame nuevo/segundo.'},
 normal:{label:'Normal',mult:2,fps:6,repeat:3,uniqueFps:2,hint:'Normal: 2× · equilibrio entre velocidad y estabilidad.'},
 fast:{label:'Rápida',mult:4,fps:12,repeat:3,uniqueFps:4,hint:'Rápida: 4× · requiere AutoLock estable.'},
 ultra:{label:'Experimental',mult:8,fps:24,repeat:3,uniqueFps:8,hint:'Experimental: 8× · puede perder más frames; HPS4 los solicita al final de cada pasada.'}
};
let tx=null,txTimer=null,txWake=null;
let cameraStream=null,scanTimer=null,cameraMode='idle';
let trackedH=null,trackAge=0;
let rx={session:null,total:0,chunks:new Map(),errors:0,roundHandled:-1,fileMeta:null,startedAt:0,lastCount:0,lastTs:0,emaRate:0};
let controlRx={session:null,round:0,total:0,parts:new Map(),firstAt:0};
let controlEmitTimer=null,controlEndTimer=null;

function log(el,msg){if(!el)return;const t=new Date().toLocaleTimeString();el.textContent=`[${t}] ${msg}\n`+el.textContent.slice(0,6000)}
function slog(msg){log($('sendLog'),msg)} function rlog(msg){log($('rxLog'),msg)}
function fmtBytes(n){if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(2)+' MB'}
function fmtTime(sec){if(!Number.isFinite(sec)||sec<0)return '—';sec=Math.round(sec);const m=Math.floor(sec/60),s=sec%60;return m?`${m}m ${String(s).padStart(2,'0')}s`:`${s}s`}
function u32(n){return[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255]}
function u16(n){return[(n>>>8)&255,n&255]}
function readU32(a,o){return((((a[o]<<24)>>>0)|(a[o+1]<<16)|(a[o+2]<<8)|a[o+3])>>>0)}
function readU16(a,o){return(a[o]<<8)|a[o+1]}
function concat(...arrs){const n=arrs.reduce((s,a)=>s+a.length,0),o=new Uint8Array(n);let p=0;for(const a of arrs){o.set(a,p);p+=a.length}return o}
const crcTable=(()=>{const t=new Uint32Array(256);for(let i=0;i<256;i++){let c=i;for(let k=0;k<8;k++)c=(c&1)?0xEDB88320^(c>>>1):c>>>1;t[i]=c>>>0}return t})();
function crc32(bytes){let c=0xFFFFFFFF;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xFFFFFFFF)>>>0}
function randomId(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]>>>0}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function speedProfile(){return SPEED_PROFILES[$('speedMode')?.value]||SPEED_PROFILES.slow}
function setPhase(text,cls=''){const el=$('phaseStatus');if(el){el.textContent=text;el.className='chip '+cls}}
function updateSpeedHint(){if($('speedHint'))$('speedHint').textContent=speedProfile().hint}

function pilotEntries(grid){const out=[];const add=(row,colStart,p)=>{for(let i=0;i<8;i++)out.push([row*grid+colStart+i,p[i]])};add(0,0,[0,1,2,3,0,1,2,3]);add(0,grid-8,[3,2,1,0,3,2,1,0]);add(grid-1,0,[1,3,0,2,1,3,0,2]);add(grid-1,grid-8,[2,0,3,1,2,0,3,1]);return out}
function pilotMap(grid){return new Map(pilotEntries(grid))}
function rawCapacity(grid){return Math.floor((grid*grid-PILOT_CELLS)*2/8)}
function payloadCapacity(grid){return rawCapacity(grid)-28}
function makePacket(type,session,round,index,total,payload,grid){const h=new Uint8Array(28);h.set(MAGIC,0);h[4]=VERSION;h[5]=type;h[6]=grid;h[7]=0;h.set(u32(session),8);h.set(u16(round),12);h.set(u32(index),14);h.set(u32(total),18);h.set(u16(payload.length),22);h.set(u32(crc32(payload)),24);return concat(h,payload)}
function parsePacket(bytes){if(bytes.length<28)return null;for(let i=0;i<4;i++)if(bytes[i]!==MAGIC[i])return null;if(bytes[4]!==VERSION)return null;const type=bytes[5],grid=bytes[6],session=readU32(bytes,8),round=readU16(bytes,12),index=readU32(bytes,14),total=readU32(bytes,18),len=readU16(bytes,22),expected=readU32(bytes,24);if(len>bytes.length-28)return null;const payload=bytes.slice(28,28+len);if(crc32(payload)!==expected)return{bad:true};return{type,grid,session,round,index,total,payload}}
function rawToGridSymbols(raw,grid){const total=grid*grid,out=new Uint8Array(total),pilots=pilotMap(grid);for(const[idx,s]of pilots)out[idx]=s;let bp=0,shift=6;for(let i=0;i<total;i++){if(pilots.has(i))continue;if(bp<raw.length){out[i]=(raw[bp]>>shift)&3;shift-=2;if(shift<0){shift=6;bp++}}else out[i]=0}return out}
function dataSymbolsToBytes(sym,grid){const pilots=pilotMap(grid),data=[];for(let i=0;i<sym.length;i++)if(!pilots.has(i))data.push(sym[i]);const n=Math.floor(data.length/4),out=new Uint8Array(n);for(let i=0;i<n;i++)out[i]=(data[i*4]<<6)|(data[i*4+1]<<4)|(data[i*4+2]<<2)|data[i*4+3];return out}
function renderRaw(raw,grid){const c=$('pixelCanvas');if(!c)throw new Error('Canvas del emisor no encontrado');c.width=grid;c.height=grid;const ctx=c.getContext('2d',{alpha:false}),sym=rawToGridSymbols(raw,grid),img=ctx.createImageData(grid,grid);for(let i=0;i<sym.length;i++){const v=LEVELS[sym[i]],p=i*4;img.data[p]=v;img.data[p+1]=v;img.data[p+2]=v;img.data[p+3]=255}ctx.putImageData(img,0,0)}

async function prepareTransfer(){try{stopTransmit(false);const f=$('fileInput')?.files?.[0];if(!f){alert('Selecciona un archivo.');return}const grid=Number($('gridSize')?.value||32),cap=payloadCapacity(grid);if(cap<32)throw new Error('Grid demasiado pequeño');const fileBytes=new Uint8Array(await f.arrayBuffer());const meta=enc.encode(JSON.stringify({name:f.name,type:f.type||'application/octet-stream',size:f.size,lastModified:f.lastModified}));const packageBytes=concat(new Uint8Array(u16(meta.length)),meta,fileBytes);const chunks=[];for(let p=0;p<packageBytes.length;p+=cap)chunks.push(packageBytes.slice(p,Math.min(packageBytes.length,p+cap)));tx={session:randomId(),grid,cap,f,fileBytes,fileCrc:crc32(fileBytes),chunks,total:chunks.length,round:0,waiting:false};$('fileSize').textContent=fmtBytes(f.size);$('frameCount').textContent=tx.total;$('capacity').textContent=cap+' B';$('sendBtn').disabled=false;slog(`Preparado · ${f.name} · ${tx.total} frames · HPS4`);setPhase('LISTO','on')}catch(e){slog('ERROR preparando: '+(e?.message||e));alert('No se pudo preparar: '+(e?.message||e))}}
function buildDataPacket(index,round){return makePacket(TYPE.DATA,tx.session,round,index,tx.total,tx.chunks[index],tx.grid)}
function buildPassEnd(round,sentCount){return makePacket(TYPE.PASS_END,tx.session,round,sentCount,tx.total,new Uint8Array(0),tx.grid)}
function openOverlay(){const o=$('streamOverlay');if(o)o.style.display='flex';document.body.style.overflow='hidden'}
function stopTransmit(hide=true){if(txTimer){clearInterval(txTimer);txTimer=null}if(controlEmitTimer){clearInterval(controlEmitTimer);controlEmitTimer=null}if(controlEndTimer){clearTimeout(controlEndTimer);controlEndTimer=null}if(hide&&$('streamOverlay'))$('streamOverlay').style.display='none';document.body.style.overflow='';if(txWake){Promise.resolve(txWake.release?.()).catch(()=>{});txWake=null}}
function maybeWake(){if(navigator.wakeLock?.request)navigator.wakeLock.request('screen').then(l=>txWake=l).catch(()=>{})}
function emitIndices(indices,round){if(!tx||!indices.length){slog('No hay frames para emitir.');return}stopCamera();stopTransmit(false);openOverlay();maybeWake();const sp=speedProfile();let pos=0,rep=0,endTicks=0,inEnd=false;const endRaw=buildPassEnd(round,indices.length);const tick=()=>{try{if(!inEnd){const idx=indices[pos];renderRaw(buildDataPacket(idx,round),tx.grid);if($('streamMeta'))$('streamMeta').textContent=`Ronda ${round+1} · Frame ${idx+1}/${tx.total} · ${sp.label} ${sp.mult}×`;rep++;if(rep>=sp.repeat){rep=0;pos++;if(pos>=indices.length){inEnd=true;setPhase('FIN DE PASADA','mid')}}}else{renderRaw(endRaw,tx.grid);if($('streamMeta'))$('streamMeta').textContent=`Fin de pasada ${round+1} · cambiando a cámara…`;endTicks++;if(endTicks>=Math.max(3,Math.ceil(sp.fps*1.2))){clearInterval(txTimer);txTimer=null;setTimeout(()=>{stopTransmit(true);startCamera('senderAck').catch(e=>slog('ERROR cámara ACK: '+e.message))},120)}}}catch(e){slog('ERROR emisión: '+(e?.message||e));stopTransmit()}};setPhase(round?'REPARANDO':'EMITIENDO','on');tick();txTimer=setInterval(tick,Math.max(30,Math.round(1000/sp.fps)));slog(`${round?'REPARACIÓN':'PRIMERA PASADA'} · ${indices.length} frames · ${sp.label} ${sp.mult}×`)}
function startFirstPass(){if(!tx){slog('Primero prepara un archivo.');return}tx.round=0;emitIndices(Array.from({length:tx.total},(_,i)=>i),0)}

function makeMissingBitmap(){const n=Math.ceil(rx.total/8),bits=new Uint8Array(n);let missing=0;for(let i=0;i<rx.total;i++)if(!rx.chunks.has(i)){bits[i>>3]|=1<<(i&7);missing++}return{bits,missing}}
function parseMissingBitmap(bits,total){const out=[];for(let i=0;i<total;i++)if(bits[i>>3]&(1<<(i&7)))out.push(i);return out}
function buildControlPayload(kind){if(kind===CTRL.COMPLETE){const assembled=assembleFile(false);const fileCrc=assembled?crc32(assembled.data):0;return concat(new Uint8Array([CTRL.COMPLETE]),new Uint8Array(u32(rx.total)),new Uint8Array(u32(fileCrc)))}const {bits}=makeMissingBitmap();return concat(new Uint8Array([CTRL.NACK]),new Uint8Array(u32(rx.total)),new Uint8Array(u32(0)),bits)}
function parseControlPayload(payload){if(payload.length<9)return null;const kind=payload[0],total=readU32(payload,1),fileCrc=readU32(payload,5);return{kind,total,fileCrc,bits:payload.slice(9)}}
function buildControlFrames(kind,session,round,grid){const payload=buildControlPayload(kind),cap=payloadCapacity(grid),parts=[];for(let p=0;p<payload.length;p+=cap)parts.push(payload.slice(p,Math.min(payload.length,p+cap)));return parts.map((part,i)=>makePacket(TYPE.CONTROL,session,round,i,parts.length,part,grid))}
function emitControl(kind,session,round){stopCamera();stopTransmit(false);openOverlay();const grid=Number($('gridSize')?.value||32),frames=buildControlFrames(kind,session,round,grid);let i=0;setPhase(kind===CTRL.COMPLETE?'ENVIANDO COMPLETE':'ENVIANDO FALTANTES','mid');const render=()=>{renderRaw(frames[i],grid);if($('streamMeta'))$('streamMeta').textContent=kind===CTRL.COMPLETE?`COMPLETE · sesión ${session.toString(16)}`:`NACK · ronda ${round+1} · parte ${i+1}/${frames.length}`;i=(i+1)%frames.length};render();controlEmitTimer=setInterval(render,140);controlEndTimer=setTimeout(()=>{stopTransmit(true);if(kind===CTRL.NACK){setPhase('ESPERANDO REPARACIÓN','mid');startCamera('receiverData').catch(e=>rlog('ERROR reabriendo cámara: '+e.message))}else setPhase('TRANSFERENCIA COMPLETA','on')},CONTROL_EMIT_MS);rlog(kind===CTRL.COMPLETE?'Confirmación COMPLETE enviada.':`Lista de faltantes enviada en ${frames.length} frame(s) de control.`)}

function captureFrame(){const v=$('video'),c=$('capture');if(!v.videoWidth||!v.clientWidth)return null;const w=Math.max(1,Math.round(v.clientWidth)),h=Math.max(1,Math.round(v.clientHeight));c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(v,0,0,w,h);return{w,h,data:ctx.getImageData(0,0,w,h).data}}
function rgbToHsv(r,g,b){r/=255;g/=255;b/=255;const mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn;let h=0;if(d){if(mx===r)h=60*(((g-b)/d)%6);else if(mx===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4);if(h<0)h+=360}return{h,s:mx?d/mx:0,v:mx}}
function hueDistance(a,b){const d=Math.abs(a-b);return Math.min(d,360-d)}
function classifyMarker(r,g,b){const hsv=rgbToHsv(r,g,b);if(hsv.s<.48||hsv.v<.42)return 0;let best=0,bd=999;for(let i=0;i<MARKER_KEYS.length;i++){const d=hueDistance(hsv.h,TARGET_HUES[MARKER_KEYS[i]]);if(d<bd){bd=d;best=i+1}}return bd<=24?best:0}
function detectFiducials(frame){const stride=Math.max(2,Math.floor(Math.min(frame.w,frame.h)/180)),gw=Math.ceil(frame.w/stride),gh=Math.ceil(frame.h/stride),mask=new Uint8Array(gw*gh);for(let gy=0;gy<gh;gy++){const y=Math.min(frame.h-1,gy*stride+Math.floor(stride/2));for(let gx=0;gx<gw;gx++){const x=Math.min(frame.w-1,gx*stride+Math.floor(stride/2)),p=(y*frame.w+x)*4;mask[gy*gw+gx]=classifyMarker(frame.data[p],frame.data[p+1],frame.data[p+2])}}const seen=new Uint8Array(mask.length),best={};for(let idx=0;idx<mask.length;idx++){const type=mask[idx];if(!type||seen[idx])continue;const stack=[idx];seen[idx]=1;let count=0,sumX=0,sumY=0,minX=1e9,maxX=-1,minY=1e9,maxY=-1;while(stack.length){const cur=stack.pop(),cy=Math.floor(cur/gw),cx=cur-cy*gw;count++;sumX+=cx;sumY+=cy;minX=Math.min(minX,cx);maxX=Math.max(maxX,cx);minY=Math.min(minY,cy);maxY=Math.max(maxY,cy);for(const ni of[cur-1,cur+1,cur-gw,cur+gw]){if(ni<0||ni>=mask.length||seen[ni]||mask[ni]!==type)continue;const ny=Math.floor(ni/gw),nx=ni-ny*gw;if(Math.abs(nx-cx)+Math.abs(ny-cy)!==1)continue;seen[ni]=1;stack.push(ni)}}if(count<6)continue;const key=MARKER_KEYS[type-1],cand={x:(sumX/count+.5)*stride,y:(sumY/count+.5)*stride,count};if(!best[key]||cand.count>best[key].count)best[key]=cand}const found=MARKER_KEYS.filter(k=>best[k]).length;if(found<4)return{found,markers:best};const counts=MARKER_KEYS.map(k=>best[k].count),ratio=Math.max(...counts)/Math.max(1,Math.min(...counts)),poly=[best.tl,best.tr,best.br,best.bl];let area=0;for(let i=0;i<4;i++){const a=poly[i],b=poly[(i+1)%4];area+=a.x*b.y-b.x*a.y}area=Math.abs(area)/2;const areaRatio=area/(frame.w*frame.h),minSide=Math.min(dist(best.tl,best.tr),dist(best.tr,best.br),dist(best.br,best.bl),dist(best.bl,best.tl));if(areaRatio<.018||minSide<Math.min(frame.w,frame.h)*.12||ratio>8)return{found,markers:best,invalid:true};const src=MARKER_KEYS.map(k=>({x:MARKER_NORM[k][0],y:MARKER_NORM[k][1]})),dst=MARKER_KEYS.map(k=>({x:best[k].x,y:best[k].y})),H=computeHomography(src,dst);if(!H)return{found,markers:best,invalid:true};const quality=Math.max(0,Math.min(100,Math.round(50+Math.min(35,areaRatio*220)+Math.max(0,15-(ratio-1)*5))));return{found,markers:best,H,quality}}
function solveLinear(A,b){const n=b.length,M=A.map((r,i)=>r.concat([b[i]]));for(let c=0;c<n;c++){let pivot=c;for(let r=c+1;r<n;r++)if(Math.abs(M[r][c])>Math.abs(M[pivot][c]))pivot=r;if(Math.abs(M[pivot][c])<1e-10)return null;[M[c],M[pivot]]=[M[pivot],M[c]];const div=M[c][c];for(let j=c;j<=n;j++)M[c][j]/=div;for(let r=0;r<n;r++){if(r===c)continue;const f=M[r][c];for(let j=c;j<=n;j++)M[r][j]-=f*M[c][j]}}return M.map(r=>r[n])}
function computeHomography(src,dst){const A=[],b=[];for(let i=0;i<4;i++){const x=src[i].x,y=src[i].y,u=dst[i].x,v=dst[i].y;A.push([x,y,1,0,0,0,-u*x,-u*y]);b.push(u);A.push([0,0,0,x,y,1,-v*x,-v*y]);b.push(v)}const h=solveLinear(A,b);return h?[h[0],h[1],h[2],h[3],h[4],h[5],h[6],h[7],1]:null}
function mapPoint(H,x,y){const d=H[6]*x+H[7]*y+H[8];return{x:(H[0]*x+H[1]*y+H[2])/d,y:(H[3]*x+H[4]*y+H[5])/d}}
function luminanceAt(frame,x,y,rad){const xi=Math.round(x),yi=Math.round(y);if(xi<0||yi<0||xi>=frame.w||yi>=frame.h)return 0;let sum=0,n=0;for(let yy=Math.max(0,yi-rad);yy<=Math.min(frame.h-1,yi+rad);yy++)for(let xx=Math.max(0,xi-rad);xx<=Math.min(frame.w-1,xi+rad);xx++){const p=(yy*frame.w+xx)*4;sum+=(frame.data[p]+frame.data[p+1]+frame.data[p+2])/3;n++}return sum/Math.max(1,n)}
function sampleGrid(frame,grid,H){const p00=mapPoint(H,DATA_MIN,DATA_MIN),p10=mapPoint(H,DATA_MAX,DATA_MIN),p01=mapPoint(H,DATA_MIN,DATA_MAX),p11=mapPoint(H,DATA_MAX,DATA_MAX),cellPx=(dist(p00,p10)+dist(p01,p11)+dist(p00,p01)+dist(p10,p11))/(4*grid),rad=Math.max(0,Math.min(2,Math.floor(cellPx*.12))),samples=new Float32Array(grid*grid);let k=0;for(let y=0;y<grid;y++)for(let x=0;x<grid;x++){const nx=DATA_MIN+(x+.5)*(DATA_MAX-DATA_MIN)/grid,ny=DATA_MIN+(y+.5)*(DATA_MAX-DATA_MIN)/grid,p=mapPoint(H,nx,ny);samples[k++]=luminanceAt(frame,p.x,p.y,rad)}return samples}
function decodeSamples(samples,grid){const pilots=pilotEntries(grid),sums=[0,0,0,0],counts=[0,0,0,0];for(const[idx,s]of pilots){sums[s]+=samples[idx];counts[s]++}const means=sums.map((v,i)=>v/Math.max(1,counts[i]));if(!(means[0]+6<means[1]&&means[1]+6<means[2]&&means[2]+6<means[3]))return null;let err=0;for(const[idx,s]of pilots)err+=Math.abs(samples[idx]-means[s]);err/=pilots.length;const sep=Math.min(means[1]-means[0],means[2]-means[1],means[3]-means[2]),quality=Math.max(0,Math.min(100,Math.round(100-err*2-Math.max(0,22-sep)))),sym=new Uint8Array(samples.length);for(let i=0;i<samples.length;i++){let best=0,bd=Infinity;for(let s=0;s<4;s++){const d=Math.abs(samples[i]-means[s]);if(d<bd){bd=d;best=s}}sym[i]=best}return{bytes:dataSymbolsToBytes(sym,grid),quality}}
function drawGuide(markers,H,state){const c=$('guideCanvas'),v=$('video');if(!c||!v.clientWidth)return;c.width=Math.round(v.clientWidth);c.height=Math.round(v.clientHeight);const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);if(markers){const colors={tl:'#00ffff',tr:'#ff00ff',bl:'#ffff00',br:'#00ff66'};for(const k of MARKER_KEYS){const m=markers[k];if(!m)continue;ctx.beginPath();ctx.arc(m.x,m.y,8,0,Math.PI*2);ctx.strokeStyle=colors[k];ctx.lineWidth=3;ctx.stroke()}}if(H){const pts=[[DATA_MIN,DATA_MIN],[DATA_MAX,DATA_MIN],[DATA_MAX,DATA_MAX],[DATA_MIN,DATA_MAX]].map(([x,y])=>mapPoint(H,x,y));ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)ctx.lineTo(pts[i].x,pts[i].y);ctx.closePath();ctx.strokeStyle=state==='LOCK'?'#34d399':'#67e8f9';ctx.lineWidth=3;ctx.stroke()}}
function setQuality(q,label){const el=$('lockQuality');if(el){el.textContent=`${label} · ${q||0}%`;el.className='lock '+(label.startsWith('LOCK')?'good':q>=45?'mid':'')}}
function decodeWithH(frame,grid,H){const d=decodeSamples(sampleGrid(frame,grid,H),grid);if(!d)return null;const p=parsePacket(d.bytes);if(p?.bad)return{bad:true,quality:d.quality};if(p)return{packet:p,quality:d.quality};return{quality:d.quality}}
function tryDecode(){const frame=captureFrame();if(!frame)return false;const det=detectFiducials(frame);if(!det.H){drawGuide(det.markers||null,null,'SEARCH');setQuality((det.found||0)*18,`BUSCANDO ${det.found||0}/4`);return false}const grids=[Number($('gridSize')?.value||32),32,40,48,56].filter((v,i,a)=>a.indexOf(v)===i);for(const g of grids){const r=decodeWithH(frame,g,det.H);if(r?.packet){trackedH=det.H;trackAge=0;drawGuide(det.markers,det.H,'LOCK');setQuality(Math.round((r.quality+det.quality)/2),'LOCK');handlePacket(r.packet);return true}if(r?.bad){rx.errors++;$('rxErrors').textContent=rx.errors}}drawGuide(det.markers,det.H,'AUTOLOCK');setQuality(det.quality||55,'AUTOLOCK');return false}

function updateMetrics(){const count=rx.chunks.size,total=rx.total,now=performance.now();if(!count||!total){if($('rxElapsed'))$('rxElapsed').textContent='—';if($('rxEta'))$('rxEta').textContent='—';if($('rxRate'))$('rxRate').textContent='—';return}if(!rx.startedAt){rx.startedAt=now;rx.lastTs=now;rx.lastCount=count}const elapsed=(now-rx.startedAt)/1000;if(count>rx.lastCount&&now>rx.lastTs){const inst=(count-rx.lastCount)/((now-rx.lastTs)/1000);rx.emaRate=rx.emaRate?rx.emaRate*.68+inst*.32:inst;rx.lastCount=count;rx.lastTs=now}const avg=count/Math.max(.25,elapsed),rate=rx.emaRate||avg;if($('rxElapsed'))$('rxElapsed').textContent=fmtTime(elapsed);if($('rxRate'))$('rxRate').textContent=rate?`${rate.toFixed(rate<10?1:0)} fr/s`:'—';if($('rxEta'))$('rxEta').textContent=count>=total?'0s':rate?`≈ ${fmtTime((total-count)/rate)}`:'Calculando…'}
function resetReceiver(session,total){rx={session,total,chunks:new Map(),errors:rx.errors,roundHandled:-1,fileMeta:null,startedAt:0,lastCount:0,lastTs:0,emaRate:0};$('rxFrames').textContent='0';$('rxTotal').textContent=total;$('rxBar').style.width='0%';if($('rxMissing'))$('rxMissing').textContent=total}
function acceptData(p){if(rx.session!==null&&rx.session!==p.session)resetReceiver(p.session,p.total);if(rx.session===null)resetReceiver(p.session,p.total);if(!rx.chunks.has(p.index)){rx.chunks.set(p.index,p.payload);$('rxFrames').textContent=rx.chunks.size;$('rxTotal').textContent=rx.total;$('rxBar').style.width=((rx.chunks.size/rx.total)*100).toFixed(1)+'%';if($('rxMissing'))$('rxMissing').textContent=Math.max(0,rx.total-rx.chunks.size);updateMetrics()}setPhase(`RECIBIENDO · ronda ${p.round+1}`,'on')}
function handlePassEnd(p){if(cameraMode!=='receiverData')return;if(rx.session!==p.session||rx.roundHandled>=p.round)return;rx.roundHandled=p.round;const {missing}=makeMissingBitmap();rlog(`Fin de pasada ${p.round+1}. Faltan ${missing} frame(s).`);setPhase(missing?'PREPARANDO NACK':'PREPARANDO COMPLETE','mid');setTimeout(()=>{if(missing===0){assembleFile(true);emitControl(CTRL.COMPLETE,p.session,p.round)}else emitControl(CTRL.NACK,p.session,p.round)},CONTROL_SETTLE_MS)}
function acceptControlPart(p){if(cameraMode!=='senderAck'||!tx||p.session!==tx.session)return;if(controlRx.session!==p.session||controlRx.round!==p.round){controlRx={session:p.session,round:p.round,total:p.total,parts:new Map(),firstAt:performance.now()}}if(!controlRx.parts.has(p.index))controlRx.parts.set(p.index,p.payload);setPhase(`ACK ${controlRx.parts.size}/${controlRx.total}`,'mid');if(controlRx.parts.size===controlRx.total){const parts=[];for(let i=0;i<controlRx.total;i++){if(!controlRx.parts.has(i))return;parts.push(controlRx.parts.get(i))}const msg=parseControlPayload(concat(...parts));if(!msg)return;slog(msg.kind===CTRL.COMPLETE?'COMPLETE recibido.':`NACK recibido · procesando faltantes…`);if(msg.kind===CTRL.COMPLETE){stopCamera();const ok=msg.fileCrc===tx.fileCrc;slog(ok?'Transferencia confirmada por CRC.':'ADVERTENCIA: COMPLETE recibido pero CRC final no coincide.');setPhase(ok?'COMPLETADO':'CRC NO COINCIDE',ok?'on':'mid');return}const missing=parseMissingBitmap(msg.bits,msg.total);slog(`Receptor solicita ${missing.length} frame(s).`);stopCamera();const wait=Math.max(500,CONTROL_EMIT_MS-(performance.now()-controlRx.firstAt)+700);setPhase(`REPARACIÓN EN ${Math.ceil(wait/1000)}s`,'mid');setTimeout(()=>{tx.round=p.round+1;emitIndices(missing,tx.round)},wait)}}
function handlePacket(p){if(p.type===TYPE.DATA)acceptData(p);else if(p.type===TYPE.PASS_END)handlePassEnd(p);else if(p.type===TYPE.CONTROL)acceptControlPart(p)}
function assembleFile(show){if(!rx.total||rx.chunks.size!==rx.total)return null;const parts=[];for(let i=0;i<rx.total;i++){if(!rx.chunks.has(i))return null;parts.push(rx.chunks.get(i))}const pkg=concat(...parts),ml=readU16(pkg,0);if(ml<=0||ml>pkg.length-2){rlog('Metadata inválida.');return null}let meta;try{meta=JSON.parse(dec.decode(pkg.slice(2,2+ml)))}catch{rlog('No se pudo leer metadata.');return null}const data=pkg.slice(2+ml,2+ml+meta.size);if(show){const blob=new Blob([data],{type:meta.type||'application/octet-stream'}),url=URL.createObjectURL(blob),box=$('receivedBox');box.style.display='block';box.innerHTML=`<b>✓ Archivo reconstruido</b><br><span class="mono">${escapeHtml(meta.name)}</span><br><span class="small">${fmtBytes(data.length)} · ${escapeHtml(meta.type)}</span><br><br><a class="btn good" style="display:inline-block;text-decoration:none" href="${url}" download="${escapeAttr(meta.name)}">Guardar archivo</a>`;rlog(`COMPLETO: ${meta.name} · ${fmtBytes(data.length)}`)}return{meta,data}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escapeAttr(s){return String(s).replace(/"/g,'')}

async function startCamera(mode='receiverData'){stopTransmit(true);stopCamera();cameraMode=mode;cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:1280}},audio:false});$('video').srcObject=cameraStream;await $('video').play();$('cameraBtn').disabled=true;$('stopCameraBtn').disabled=false;trackedH=null;trackAge=0;scanTimer=setInterval(tryDecode,90);if(mode==='senderAck'){setPhase('EMISOR · ESPERANDO ACK/NACK','mid');slog('Cámara activa esperando PixelStream de control del receptor.')}else{setPhase(rx.session?'RECEPTOR · ESPERANDO REPARACIÓN':'RECEPTOR · RECIBIENDO','on');rlog('Cámara activa. HPS4 AutoLock esperando datos.')}setTimeout(()=>$('receiverPanel')?.scrollIntoView({behavior:'smooth',block:'center'}),100)}
function stopCamera(){if(scanTimer){clearInterval(scanTimer);scanTimer=null}if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null}if($('video'))$('video').srcObject=null;if($('cameraBtn'))$('cameraBtn').disabled=false;if($('stopCameraBtn'))$('stopCameraBtn').disabled=true;cameraMode='idle'}

$('prepareBtn').onclick=prepareTransfer;$('sendBtn').onclick=startFirstPass;$('closeStream').onclick=()=>stopTransmit(true);$('cameraBtn').onclick=()=>startCamera('receiverData').catch(e=>{rlog('ERROR cámara: '+e.message);alert('No se pudo abrir la cámara: '+e.message)});$('stopCameraBtn').onclick=stopCamera;
$('gridSize').onchange=()=>{$('capacity').textContent=payloadCapacity(Number($('gridSize').value))+' B';$('sendBtn').disabled=true};$('speedMode').onchange=updateSpeedHint;updateSpeedHint();$('capacity').textContent=payloadCapacity(Number($('gridSize').value||32))+' B';
$('cameraChip').textContent=navigator.mediaDevices?.getUserMedia?'● Cámara: disponible':'○ Cámara: no disponible';$('cameraChip').className='chip '+(navigator.mediaDevices?.getUserMedia?'on':'off');$('wakeChip').textContent='wakeLock'in navigator?'● Wake Lock: disponible':'○ Wake Lock: no disponible';$('wakeChip').className='chip '+('wakeLock'in navigator?'on':'off');setPhase('HPS4 LISTO','on');setInterval(updateMetrics,500);window.addEventListener('pagehide',()=>{stopTransmit(false);stopCamera()});if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});slog('HPS4 Bidirectional ARQ cargado.');
})();
