(() => {
'use strict';

const $=id=>document.getElementById(id),F=window.__hopperHPS8Fountain,Sonic=window.__hopperHPS8Sonic;
if(!F||!Sonic){console.error('HPS8 dependencies missing');return;}
const VERSION='0.10.0',MAGIC=[0x48,0x50,0x53,0x38],PROTO=1,HEADER=32,GRID=56,BITS=2,PILOTS=32,CHUNK=700,DATA_MIN=.12,DATA_MAX=.88;
const TYPE={HELLO:1,SYSTEMATIC:2,FOUNTAIN:3};
const LEVELS=[[26,26,26],[92,92,92],[164,164,164],[236,236,236]];
const MARKER_KEYS=['tl','tr','bl','br'],MARKER_NORM={tl:[.06,.06],tr:[.94,.06],bl:[.06,.94],br:[.94,.94]};
const enc=new TextEncoder();
let hps7Handlers=null,installed=false,currentOverlayAction=null,tx=null,rx=null,runToken=0,cameraStream=null,scanHandle=null,scanMode='none',scanGen=0;

const crcTable=(()=>{const t=new Uint32Array(256);for(let i=0;i<256;i++){let c=i;for(let k=0;k<8;k++)c=(c&1)?0xEDB88320^(c>>>1):c>>>1;t[i]=c>>>0;}return t;})();
function crc32(bytes){let c=0xFFFFFFFF;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xFFFFFFFF)>>>0;}
function u16(n){return[(n>>>8)&255,n&255];}function u32(n){return[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255];}
function readU16(a,o){return(a[o]<<8)|a[o+1];}function readU32(a,o){return((((a[o]<<24)>>>0)|(a[o+1]<<16)|(a[o+2]<<8)|a[o+3])>>>0);}
function concat(...xs){const n=xs.reduce((s,a)=>s+a.length,0),o=new Uint8Array(n);let p=0;for(const a of xs){o.set(a,p);p+=a.length;}return o;}
function randomId(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]||1;}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
function fmtBytes(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KiB`;return`${(n/1048576).toFixed(2)} MiB`;}
function fmtTime(sec){if(!Number.isFinite(sec)||sec<0)return'—';sec=Math.round(sec);const m=Math.floor(sec/60),s=sec%60;return m?`${m}m ${String(s).padStart(2,'0')}s`:`${s}s`;}
function opticalHold(ms){return new Promise(resolve=>{const st=performance.now(),step=t=>t-st>=ms-1?resolve():requestAnimationFrame(step);requestAnimationFrame(step);});}
function log(msg){const e=$('sendLog');if(e)e.textContent=`[${new Date().toLocaleTimeString()}] HPS8 · ${msg}\n`+e.textContent.slice(0,8500);}
function rlog(msg){const e=$('rxLog');if(e)e.textContent=`[${new Date().toLocaleTimeString()}] HPS8 · ${msg}\n`+e.textContent.slice(0,8500);}
function setPhase(text,kind=''){const e=$('phaseStatus');if(e){e.textContent=text;e.className='chip '+kind;}}
function mode(){return $('protocolMode')?.value==='hps8'?'hps8':'hps7';}
function hps8Active(){return mode()==='hps8';}
function emit(name,detail={}){try{window.dispatchEvent(new CustomEvent('hopper:hps8-'+name,{detail}));}catch{}}

function pilotPositions(grid){const out=[],add=(r,c)=>{for(let i=0;i<8;i++)out.push(r*grid+c+i);};add(0,0);add(0,grid-8);add(grid-1,0);add(grid-1,grid-8);return out;}
function pilotEntries(grid){return pilotPositions(grid).map((idx,i)=>[idx,i&3]);}
function pilotMap(grid){return new Map(pilotEntries(grid));}
function rawCapacity(grid=GRID){return Math.floor((grid*grid-PILOTS)*BITS/8);}
function payloadCapacity(grid=GRID){return rawCapacity(grid)-HEADER;}
function makePacket(type,session,symbolId,sourceCount,payload,seed=0,chunkSize=CHUNK){payload=payload instanceof Uint8Array?payload:new Uint8Array(payload);if(payload.length>payloadCapacity())throw new Error(`HPS8 payload ${payload.length}>${payloadCapacity()}`);const h=new Uint8Array(HEADER);h.set(MAGIC,0);h[4]=PROTO;h[5]=type;h[6]=GRID;h[7]=BITS;h.set(u32(session),8);h.set(u32(symbolId),12);h.set(u32(sourceCount),16);h.set(u16(chunkSize),20);h.set(u16(payload.length),22);h.set(u32(seed),24);h.set(u32(crc32(concat(h.slice(0,28),payload))),28);return concat(h,payload);}
function parsePacket(bytes){if(bytes.length<HEADER)return null;for(let i=0;i<4;i++)if(bytes[i]!==MAGIC[i])return null;if(bytes[4]!==PROTO||bytes[6]!==GRID||bytes[7]!==BITS)return null;const type=bytes[5],session=readU32(bytes,8),symbolId=readU32(bytes,12),sourceCount=readU32(bytes,16),chunkSize=readU16(bytes,20),len=readU16(bytes,22),seed=readU32(bytes,24),expected=readU32(bytes,28);if(!Object.values(TYPE).includes(type)||!session||!sourceCount||!chunkSize||len>payloadCapacity()||HEADER+len>bytes.length)return null;const payload=bytes.slice(HEADER,HEADER+len),actual=crc32(concat(bytes.slice(0,28),payload));if(actual!==expected)return{bad:true};return{type,session,symbolId,sourceCount,chunkSize,seed,payload};}
function rawToSymbols(raw,grid=GRID){const out=new Uint8Array(grid*grid),pm=pilotMap(grid);for(const[i,s]of pm)out[i]=s;let bit=0,total=raw.length*8;for(let i=0;i<out.length;i++){if(pm.has(i))continue;let v=0;for(let k=0;k<2;k++){v<<=1;if(bit<total){const bi=bit>>3,sh=7-(bit&7);v|=(raw[bi]>>sh)&1;}bit++;}out[i]=v;}return out;}
function symbolsToBytes(sym,grid=GRID){const pm=pilotMap(grid),out=new Uint8Array(rawCapacity(grid));let bit=0;for(let i=0;i<sym.length;i++){if(pm.has(i))continue;for(let k=1;k>=0;k--){if(bit>=out.length*8)break;const bi=bit>>3,sh=7-(bit&7);out[bi]|=((sym[i]>>k)&1)<<sh;bit++;}}return out;}
function renderSquare(raw){document.documentElement.classList.remove('stream-tall');const c=$('pixelCanvas');c.width=GRID;c.height=GRID;const ctx=c.getContext('2d',{alpha:false}),sym=rawToSymbols(raw),img=ctx.createImageData(GRID,GRID);for(let i=0;i<sym.length;i++){const rgb=LEVELS[sym[i]],p=i*4;img.data[p]=rgb[0];img.data[p+1]=rgb[1];img.data[p+2]=rgb[2];img.data[p+3]=255;}ctx.putImageData(img,0,0);}
function renderDual(rawA,rawB){document.documentElement.classList.add('stream-tall');const c=$('pixelCanvas');c.width=GRID;c.height=GRID*2;const ctx=c.getContext('2d',{alpha:false}),a=rawToSymbols(rawA),b=rawToSymbols(rawB),sym=new Uint8Array(GRID*GRID*2);sym.set(a);sym.set(b,GRID*GRID);const img=ctx.createImageData(GRID,GRID*2);for(let i=0;i<sym.length;i++){const rgb=LEVELS[sym[i]],p=i*4;img.data[p]=rgb[0];img.data[p+1]=rgb[1];img.data[p+2]=rgb[2];img.data[p+3]=255;}ctx.putImageData(img,0,0);}

function openOverlay(meta,bottom,actionLabel=null,action=null){const o=$('streamOverlay');if(!o)return;o.style.display='flex';document.body.style.overflow='hidden';$('streamMeta').textContent=meta;$('streamBottom').textContent=bottom;const b=$('overlayActionBtn');if(b){b.textContent=actionLabel||'';b.style.display=actionLabel?'inline-flex':'none';}currentOverlayAction=action;}
function closeOverlay(){if($('streamOverlay'))$('streamOverlay').style.display='none';document.body.style.overflow='';currentOverlayAction=null;document.documentElement.classList.remove('stream-tall');}
function speedProfile(){const v=$('speedMode')?.value||'maxcal';if(v==='compatible')return{fps:8,label:'Compatible'};if(v==='balanced')return{fps:12,label:'Balanceado'};if(v==='optical')return{fps:18,label:'Experimental 18'};return{fps:15,label:'Photon 15'};}

function setHps8PanelVisible(on){const p=$('hps8ProgressPanel');if(p)p.style.display=on?'block':'none';const s=$('hps8SonicStatus');if(s)s.style.display=on?'inline-flex':'none';}
function updateProgress({name=null,bytes=0,total=0,speed=0,eta=Infinity,known=0,sourceCount=0,status='',autoRepair=''}){if(name!=null&&$('hps8FileName'))$('hps8FileName').textContent=name;const pct=total?clamp(bytes/total*100,0,100):0;if($('hps8Percent'))$('hps8Percent').textContent=`${pct.toFixed(pct<10?1:0)}%`;if($('hps8Bytes'))$('hps8Bytes').textContent=`${fmtBytes(bytes)} de ${fmtBytes(total)}`;if($('hps8FileBar'))$('hps8FileBar').style.width=`${pct.toFixed(2)}%`;if($('hps8Speed'))$('hps8Speed').textContent=speed>0?`${fmtBytes(speed)}/s`:'—';if($('hps8Eta'))$('hps8Eta').textContent=speed>0?fmtTime(eta):'—';if($('hps8Fountain'))$('hps8Fountain').textContent=sourceCount?`${known}/${sourceCount}`:'—';if($('hps8ProgressStatus')&&status)$('hps8ProgressStatus').textContent=status;if($('hps8AutoRepair'))$('hps8AutoRepair').textContent=autoRepair||'Fountain activo';}
function clearProgress(name='Sin transferencia'){updateProgress({name,bytes:0,total:0,speed:0,known:0,sourceCount:0,status:'HPS8 listo',autoRepair:'Auto-Repair transparente'});}

function chunksFor(bytes){const count=Math.max(1,Math.ceil(bytes.length/CHUNK)),blocks=[];for(let i=0;i<count;i++){const b=new Uint8Array(CHUNK),start=i*CHUNK;b.set(bytes.slice(start,Math.min(bytes.length,start+CHUNK)));blocks.push(b);}return blocks;}
async function prepare(){if(!hps8Active())return;cancelHps8(false);const f=$('fileInput')?.files?.[0];if(!f){alert('Selecciona un archivo.');return;}const btn=$('prepareBtn');btn.disabled=true;btn.textContent='Preparando HPS8…';setPhase('EMISOR · HPS8 PREPARANDO','mid');try{const fileBytes=new Uint8Array(await f.arrayBuffer()),blocks=chunksFor(fileBytes),fileCrc=crc32(fileBytes),session=randomId(),meta={name:f.name,type:f.type||'application/octet-stream',size:f.size,lastModified:f.lastModified||0,fileCrc,sourceCount:blocks.length,chunkSize:CHUNK,layout:'dual',bits:2,codec:'PhotonFountain',sonic:'Sonic8'};const hello=enc.encode(JSON.stringify(meta));if(hello.length>payloadCapacity())throw new Error('Metadata HPS8 demasiado grande');tx={session,f,fileBytes,fileCrc,blocks,sourceCount:blocks.length,meta,hello,sysIndex:0,paritySeed:(randomId()|1)>>>0,repairQueue:[],running:false,completed:false,sonicReady:false,lastControlAt:0,receiverPermille:0,receiverMissing:blocks.length,framesSent:0,paritySent:0,startedAt:0};$('fileSize').textContent=fmtBytes(f.size);$('frameCount').textContent=blocks.length;$('capacity').textContent=`${CHUNK} B fuente`;$('sendBtn').disabled=false;$('sendBtn').style.display='inline-flex';$('sendBtn').textContent='Mostrar HELLO HPS8';$('txRepairBtn').style.display='none';if($('hps7Projection'))$('hps7Projection').style.display='none';updateProgress({name:f.name,bytes:0,total:f.size,known:0,sourceCount:blocks.length,status:'Preparado · esperando receptor',autoRepair:'Systematic + Fountain'});setPhase('EMISOR · HPS8 PREPARADO','on');log(`Preparado ${f.name} · ${fmtBytes(f.size)} · ${blocks.length} bloques × ${CHUNK} B · CRC ${fileCrc.toString(16)}.`);}catch(e){setPhase('ERROR HPS8 PREPARE','off');log(`ERROR prepare: ${e.message}`);alert(`No se pudo preparar HPS8: ${e.message}`);}finally{btn.disabled=false;btn.textContent=tx?'Repreparar HPS8':'Preparar HPS8';}}

async function showHello(){if(!hps8Active()||!tx)return;stopCamera();try{await Sonic.startListener(handleSonicMessage);tx.sonicReady=true;log('Sonic8 sender RX listo; esperando ACK/PROGRESS/BLOOM/COMPLETE.');}catch(e){tx.sonicReady=false;log(`Sonic8 no disponible: ${e.message}. HPS8 seguirá con redundancia óptica.`);if($('hps8SonicStatus')){$('hps8SonicStatus').textContent='SONIC · FALLBACK';$('hps8SonicStatus').className='chip mid';}}const raw=makePacket(TYPE.HELLO,tx.session,0,tx.sourceCount,tx.hello,0,CHUNK);renderSquare(raw);openOverlay('HPS8 HELLO · PhotonFountain','Apunta el receptor. Sonic8 intentará iniciar DATA automáticamente al confirmar LOCK.','Iniciar HPS8',()=>startData());setPhase('EMISOR · HPS8 HELLO','mid');log('HELLO HPS8 fijo · control óptico 2-bit.');}

function nextSeed(){tx.paritySeed=(tx.paritySeed+0x9e3779b9)>>>0;return tx.paritySeed||1;}
function systematicPacket(idx){return makePacket(TYPE.SYSTEMATIC,tx.session,idx,tx.sourceCount,tx.blocks[idx],0,CHUNK);}
function fountainPacket(){const seed=nextSeed(),symbol=F.makeParity(tx.blocks,seed);tx.paritySent++;return makePacket(TYPE.FOUNTAIN,tx.session,tx.paritySent,tx.sourceCount,symbol.data,seed,CHUNK);}
function chooseTopPacket(){if(tx.repairQueue.length){const idx=tx.repairQueue.shift();return{raw:systematicPacket(idx),label:`AUTO-REPAIR ${idx}`};}if(tx.sysIndex<tx.sourceCount){const idx=tx.sysIndex++;return{raw:systematicPacket(idx),label:`DATA ${idx+1}/${tx.sourceCount}`};}return{raw:fountainPacket(),label:'FOUNTAIN'};}
async function startData(){if(!tx||tx.running||tx.completed)return;currentOverlayAction=null;$('overlayActionBtn').style.display='none';tx.running=true;tx.startedAt=performance.now();const token=++runToken,sp=speedProfile(),frameMs=Math.max(48,Math.round(1000/sp.fps));setPhase('EMISOR · HPS8 PHOTONFOUNTAIN','on');document.documentElement.classList.add('stream-tall');log(`PhotonFountain inicia · ${sp.fps} streams/s · lane A sistemático/repair · lane B fountain.`);emit('data-start',{session:tx.session,sourceCount:tx.sourceCount,fps:sp.fps});let warm=true;while(tx.running&&!tx.completed&&token===runToken){const top=chooseTopPacket(),bottom=fountainPacket();renderDual(top.raw,bottom);tx.framesSent++;$('streamMeta').textContent=`HPS8 · ${top.label} · F${tx.paritySent}`;$('streamBottom').textContent=`2-bit · DualLane · ${sp.fps} stream/s · Fountain ${tx.receiverPermille/10}% · faltan≈${tx.receiverMissing}`;if(warm){warm=false;await opticalHold(520);}else await opticalHold(frameMs);if(!tx.sonicReady&&tx.sysIndex>=tx.sourceCount&&tx.framesSent>=Math.ceil(tx.sourceCount*1.8)){tx.running=false;log('Sonic8 no disponible: burst redundante 1.8× terminado. El receptor puede completar/guardar si obtuvo suficiente información.');setPhase('EMISOR · HPS8 BURST TERMINADO','mid');$('streamBottom').textContent='Burst HPS8 terminado · revisa el receptor · Sonic8 no disponible.';break;}}
if(tx.completed){closeOverlay();setPhase('EMISOR · HPS8 COMPLETADO','on');updateProgress({name:tx.f.name,bytes:tx.f.size,total:tx.f.size,speed:0,known:tx.sourceCount,sourceCount:tx.sourceCount,status:'✓ Receptor confirmó CRC',autoRepair:'Completado sin intervención'});log(`COMPLETE Sonic8 confirmado · ${tx.framesSent} streams físicos.`);setTimeout(()=>Sonic.stopListener(),800);}tx.running=false;}

function handleSonicMessage(msg){if(!tx||msg.session!==tx.session)return;tx.lastControlAt=performance.now();const T=Sonic.type;if(msg.type===T.ACK){log('ACK Sonic8 recibido · iniciando DATA automáticamente.');tx.sonicReady=true;if(!tx.running&&!tx.completed)setTimeout(()=>startData(),120);return;}if(msg.type===T.PROGRESS){const p=Sonic.parseProgress(msg.payload);if(!p)return;tx.receiverPermille=p.permille;tx.receiverMissing=p.missing;const bytes=Math.round(tx.f.size*p.permille/1000);updateProgress({name:tx.f.name,bytes,total:tx.f.size,known:tx.sourceCount-p.missing,sourceCount:tx.sourceCount,status:`Receptor ${p.permille/10}% · Fountain en vivo`,autoRepair:(p.flags&1)?'Decoder estancado · esperando Bloom-NACK':'Fountain absorbiendo pérdidas'});return;}if(msg.type===T.BLOOM){const p=Sonic.parseBloom(msg.payload);if(!p)return;const candidates=F.candidatesFromBloom(tx.sourceCount,p.bloom).slice(0,Math.max(64,Math.min(700,p.missing*10))),seen=new Set(tx.repairQueue);for(const i of candidates)if(!seen.has(i)){tx.repairQueue.push(i);seen.add(i);}tx.receiverMissing=p.missing;log(`Bloom-NACK Sonic8 · ${p.missing} faltantes · ${candidates.length} candidatos → Auto-Repair transparente.`);updateProgress({name:tx.f.name,bytes:Math.round(tx.f.size*tx.receiverPermille/1000),total:tx.f.size,known:tx.sourceCount-p.missing,sourceCount:tx.sourceCount,status:'Auto-Repair activo',autoRepair:`Bloom-NACK · ${candidates.length} candidatos`});return;}if(msg.type===T.COMPLETE){const p=Sonic.parseComplete(msg.payload);if(p?.fileCrc===tx.fileCrc){tx.completed=true;tx.running=false;runToken++;log('COMPLETE válido por Sonic8 + CRC.');}}}

function solveLinear(A,b){const n=b.length,M=A.map((r,i)=>r.concat([b[i]]));for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(M[r][c])>Math.abs(M[p][c]))p=r;if(Math.abs(M[p][c])<1e-10)return null;[M[c],M[p]]=[M[p],M[c]];const d=M[c][c];for(let j=c;j<=n;j++)M[c][j]/=d;for(let r=0;r<n;r++){if(r===c)continue;const f=M[r][c];for(let j=c;j<=n;j++)M[r][j]-=f*M[c][j];}}return M.map(r=>r[n]);}
function computeH(src,dst){const A=[],b=[];for(let i=0;i<4;i++){const x=src[i].x,y=src[i].y,u=dst[i].x,v=dst[i].y;A.push([x,y,1,0,0,0,-u*x,-u*y]);b.push(u);A.push([0,0,0,x,y,1,-v*x,-v*y]);b.push(v);}const h=solveLinear(A,b);return h?[h[0],h[1],h[2],h[3],h[4],h[5],h[6],h[7],1]:null;}
function mapPoint(H,x,y){const d=H[6]*x+H[7]*y+H[8];return{x:(H[0]*x+H[1]*y+H[2])/d,y:(H[3]*x+H[4]*y+H[5])/d};}
function rgbAt(frame,x,y,rad=1){const xi=Math.round(x),yi=Math.round(y),rs=[],gs=[],bs=[];for(let yy=Math.max(0,yi-rad);yy<=Math.min(frame.h-1,yi+rad);yy++)for(let xx=Math.max(0,xi-rad);xx<=Math.min(frame.w-1,xi+rad);xx++){const p=(yy*frame.w+xx)*4;rs.push(frame.data[p]);gs.push(frame.data[p+1]);bs.push(frame.data[p+2]);}rs.sort((a,b)=>a-b);gs.sort((a,b)=>a-b);bs.sort((a,b)=>a-b);const m=Math.floor(rs.length/2);return[rs[m]||0,gs[m]||0,bs[m]||0];}
function sampleGrid(frame,H,lane=-1){const yr=lane===0?[DATA_MIN,.5]:lane===1?[.5,DATA_MAX]:[DATA_MIN,DATA_MAX],y0=yr[0],y1=yr[1],a=mapPoint(H,DATA_MIN,y0),b=mapPoint(H,DATA_MAX,y0),c=mapPoint(H,DATA_MIN,y1),d=mapPoint(H,DATA_MAX,y1),cell=(dist(a,b)+dist(c,d)+dist(a,c)+dist(b,d))/(4*GRID),rad=Math.max(0,Math.min(2,Math.floor(cell*.16))),out=new Float32Array(GRID*GRID*3);let k=0;for(let y=0;y<GRID;y++)for(let x=0;x<GRID;x++){const nx=DATA_MIN+(x+.5)*(DATA_MAX-DATA_MIN)/GRID,ny=y0+(y+.5)*(y1-y0)/GRID,p=mapPoint(H,nx,ny),rgb=rgbAt(frame,p.x,p.y,rad);out[k++]=rgb[0];out[k++]=rgb[1];out[k++]=rgb[2];}return window.__hopperOpticalDockV3?.normalizeSamples?window.__hopperOpticalDockV3.normalizeSamples(out,lane):out;}
function decodeGray(samples){const pilots=pilotEntries(GRID),sum=[0,0,0,0],cnt=[0,0,0,0];for(const[idx,s]of pilots){const p=idx*3,v=(samples[p]+samples[p+1]+samples[p+2])/3;sum[s]+=v;cnt[s]++;}const means=sum.map((v,i)=>v/Math.max(1,cnt[i]));if(!(means[0]+3<means[1]&&means[1]+3<means[2]&&means[2]+3<means[3]))return null;const sym=new Uint8Array(GRID*GRID);let err=0;for(let i=0;i<sym.length;i++){const p=i*3,v=(samples[p]+samples[p+1]+samples[p+2])/3;let best=0,bd=1e9;for(let s=0;s<4;s++){const dd=Math.abs(v-means[s]);if(dd<bd){bd=dd;best=s;}}sym[i]=best;}for(const[idx,s]of pilots){const p=idx*3,v=(samples[p]+samples[p+1]+samples[p+2])/3;err+=Math.abs(v-means[s]);}return{bytes:symbolsToBytes(sym),quality:clamp(Math.round(100-(err/pilots.length)*1.4),0,100)};}
function captureFrame(){const v=$('video'),c=$('capture');if(!v?.videoWidth)return null;const maxW=860,scale=Math.min(1,maxW/v.videoWidth),w=Math.max(320,Math.round(v.videoWidth*scale)),h=Math.max(240,Math.round(v.videoHeight*scale));c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(v,0,0,w,h);const img=ctx.getImageData(0,0,w,h);return{w,h,data:img.data};}
function geometry(){const b=window.__hopperBinaryTagBridge?.last;if(!b?.valid||!b.markers||!MARKER_KEYS.every(k=>b.markers[k]))return null;const src=MARKER_KEYS.map(k=>({x:MARKER_NORM[k][0],y:MARKER_NORM[k][1]})),dst=MARKER_KEYS.map(k=>b.markers[k]);return computeH(src,dst);}
function tryDecode(){if(!rx||!cameraStream)return;const frame=captureFrame();if(!frame)return;const H=geometry();if(!H)return;const lanes=rx.session?[0,1]:[-1];for(const lane of lanes){const ds=decodeGray(sampleGrid(frame,H,lane));if(!ds)continue;const p=parsePacket(ds.bytes);if(p?.bad){rx.rejected++;continue;}if(!p)continue;if(lane>=0&&p.type===TYPE.HELLO)continue;if(lane<0&&p.type!==TYPE.HELLO)continue;handleRxPacket(p,ds.quality,lane);}}
function scheduleScan(gen){const v=$('video');if(gen!==scanGen||!cameraStream)return;if(typeof v.requestVideoFrameCallback==='function'){scanMode='rvfc';scanHandle=v.requestVideoFrameCallback(()=>{if(gen!==scanGen)return;tryDecode();scheduleScan(gen);});}else{scanMode='timeout';scanHandle=setTimeout(()=>{if(gen!==scanGen)return;tryDecode();scheduleScan(gen);},45);}}
async function tuneCamera(track){try{const cap=track?.getCapabilities?.()||{},adv={};if(Array.isArray(cap.focusMode)&&cap.focusMode.includes('continuous'))adv.focusMode='continuous';if(Array.isArray(cap.exposureMode)&&cap.exposureMode.includes('continuous'))adv.exposureMode='continuous';if(Array.isArray(cap.whiteBalanceMode)&&cap.whiteBalanceMode.includes('continuous'))adv.whiteBalanceMode='continuous';if(Object.keys(adv).length)await track.applyConstraints({advanced:[adv]});}catch{}}
async function startCamera(){stopCamera();cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,min:15}},audio:false});const v=$('video');v.srcObject=cameraStream;await v.play();$('cameraBtn').disabled=true;$('stopCameraBtn').disabled=false;await tuneCamera(cameraStream.getVideoTracks()[0]);const gen=++scanGen;scheduleScan(gen);}
function stopCamera(){scanGen++;const v=$('video');if(scanHandle!==null){if(scanMode==='rvfc'&&v?.cancelVideoFrameCallback)try{v.cancelVideoFrameCallback(scanHandle);}catch{}else clearTimeout(scanHandle);scanHandle=null;}if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;}if(v)v.srcObject=null;if($('cameraBtn'))$('cameraBtn').disabled=false;if($('stopCameraBtn'))$('stopCameraBtn').disabled=true;}

function freshRx(){return{session:null,meta:null,decoder:null,knownBytes:0,startedAt:0,lastRateTs:0,lastRateBytes:0,rate:0,lastGainTs:0,lastBloomTs:0,lastProgressTx:0,sonicBusy:false,rejected:0,valid:0,complete:false,receivedSeeds:new Set()};}
async function startReceiver(){if(!hps8Active())return;rx=freshRx();clearProgress('Esperando archivo HPS8');try{await Sonic.ensureOutput();}catch{}try{await startCamera();setPhase('RECEPTOR · HPS8 BUSCANDO HELLO','on');rlog('Cámara HPS8 activa · esperando HELLO PhotonFountain.');}catch(e){setPhase('ERROR CÁMARA HPS8','off');alert(`No se pudo abrir cámara: ${e.message}`);}}
function blockRealBytes(idx){if(!rx?.meta)return 0;const start=idx*rx.meta.chunkSize;return Math.max(0,Math.min(rx.meta.chunkSize,rx.meta.size-start));}
function onKnown(idx){rx.knownBytes+=blockRealBytes(idx);const now=performance.now();rx.lastGainTs=now;if(!rx.startedAt){rx.startedAt=now;rx.lastRateTs=now;rx.lastRateBytes=rx.knownBytes;}if(now-rx.lastRateTs>=350){const inst=(rx.knownBytes-rx.lastRateBytes)/((now-rx.lastRateTs)/1000);rx.rate=rx.rate?rx.rate*.72+inst*.28:inst;rx.lastRateTs=now;rx.lastRateBytes=rx.knownBytes;}updateRxProgress();}
function updateRxProgress(status='Recibiendo PhotonFountain',autoRepair='Fountain absorbiendo pérdidas'){if(!rx?.meta)return;const snap=rx.decoder?.snapshot?.()||{known:0,total:rx.meta.sourceCount,missing:rx.meta.sourceCount},remain=Math.max(0,rx.meta.size-rx.knownBytes),eta=rx.rate>0?remain/rx.rate:Infinity;updateProgress({name:rx.meta.name,bytes:rx.knownBytes,total:rx.meta.size,speed:rx.rate,eta,known:snap.known,sourceCount:snap.total,status,autoRepair});$('rxFrames').textContent=snap.known;$('rxTotal').textContent=snap.total;$('rxMissing').textContent=snap.missing;$('rxBar').style.width=`${rx.meta.size?rx.knownBytes/rx.meta.size*100:100}%`;$('rxRate').textContent=rx.rate>0?`${fmtBytes(rx.rate)}/s`:'—';$('rxEta').textContent=rx.rate>0?fmtTime(eta):'—';$('rxElapsed').textContent=rx.startedAt?fmtTime((performance.now()-rx.startedAt)/1000):'—';$('rxErrors').textContent=rx.rejected;}
async function sendRxControl(type,payload,repeats=2,label='CTRL'){if(rx.sonicBusy||!rx.session)return false;rx.sonicBusy=true;try{await Sonic.send(type,rx.session,payload,{repeats,label});return true;}catch(e){rlog(`Sonic8 TX falló: ${e.message}`);return false;}finally{rx.sonicBusy=false;}}
function maybeSendProgress(){if(!rx?.session||rx.complete)return;const now=performance.now(),snap=rx.decoder.snapshot();if(now-rx.lastProgressTx>2600&&!rx.sonicBusy){rx.lastProgressTx=now;const permille=rx.meta.size?Math.round(rx.knownBytes/rx.meta.size*1000):1000,stalled=now-rx.lastGainTs>4800?1:0;sendRxControl(Sonic.type.PROGRESS,Sonic.progressPayload(permille,snap.missing,stalled),1,'PROGRESS');}if(snap.missing>0&&snap.missing<=Math.min(512,Math.max(32,Math.floor(snap.total*.25)))&&now-rx.lastGainTs>5200&&now-rx.lastBloomTs>7800&&!rx.sonicBusy){rx.lastBloomTs=now;const missing=rx.decoder.missingIndices(),bloom=F.makeBloom(missing,16,3);updateRxProgress('Auto-Repair solicitado','Bloom-NACK acústico · transparente');sendRxControl(Sonic.type.BLOOM,Sonic.bloomPayload(missing.length,bloom),2,`BLOOM ${missing.length}`);}}
function handleRxPacket(p,quality,lane){if(p.type===TYPE.HELLO){if(rx.session&&rx.session!==p.session)return;let meta;try{meta=JSON.parse(new TextDecoder().decode(p.payload));}catch{return;}if(meta.sourceCount!==p.sourceCount||meta.chunkSize!==p.chunkSize||meta.chunkSize!==CHUNK)return;if(!rx.session){rx.session=p.session;rx.meta=meta;rx.decoder=F.createDecoder(meta.sourceCount,meta.chunkSize,onKnown);rx.startedAt=performance.now();rx.lastGainTs=performance.now();rx.lastProgressTx=0;setPhase('RECEPTOR · HPS8 LOCK · AUTO','on');updateProgress({name:meta.name,bytes:0,total:meta.size,known:0,sourceCount:meta.sourceCount,status:'LOCK · esperando DATA',autoRepair:'Sonic8 ACK automático'});rlog(`HELLO HPS8 · ${meta.name} · ${meta.sourceCount} bloques · CRC ${meta.fileCrc.toString(16)}.`);sendRxControl(Sonic.type.ACK,new Uint8Array([1]),2,'ACK');}return;}if(!rx.session||p.session!==rx.session||p.sourceCount!==rx.meta.sourceCount||p.chunkSize!==rx.meta.chunkSize){rx.rejected++;return;}rx.valid++;if(p.type===TYPE.SYSTEMATIC){rx.decoder.addSystematic(p.symbolId,p.payload);}else if(p.type===TYPE.FOUNTAIN){if(rx.receivedSeeds.has(p.seed))return;rx.receivedSeeds.add(p.seed);rx.decoder.addParity(p.seed,p.payload);}updateRxProgress();maybeSendProgress();if(rx.decoder.complete&&!rx.complete)finishRx();}
function assembleRx(){const blocks=rx.decoder.blocks(),out=new Uint8Array(rx.meta.size);let p=0;for(let i=0;i<blocks.length&&p<out.length;i++){const n=Math.min(blocks[i].length,out.length-p);out.set(blocks[i].slice(0,n),p);p+=n;}return out;}
async function finishRx(){rx.complete=true;stopCamera();const data=assembleRx(),crc=crc32(data);if(crc!==rx.meta.fileCrc){rx.complete=false;rx.rejected++;rlog(`CRC final incorrecto ${crc.toString(16)} != ${rx.meta.fileCrc.toString(16)}; solicitando más Fountain.`);try{await startCamera();}catch{}return;}rx.knownBytes=rx.meta.size;updateRxProgress('✓ Archivo reconstruido · CRC verificado','Sin Repair manual');setPhase('RECEPTOR · HPS8 COMPLETE','on');const blob=new Blob([data],{type:rx.meta.type||'application/octet-stream'}),url=URL.createObjectURL(blob),box=$('receivedBox');box.style.display='block';box.innerHTML=`<b>✓ HPS8 PhotonFountain reconstruido</b><br><span class="mono">${escapeHtml(rx.meta.name)}</span><br><span class="small">${fmtBytes(data.length)} · CRC ${crc.toString(16)} · ${rx.valid} paquetes ópticos válidos</span><br><br><a class="btn good" style="display:inline-block;text-decoration:none" href="${url}" download="${escapeAttr(rx.meta.name)}">Guardar archivo</a>`;await sendRxControl(Sonic.type.COMPLETE,Sonic.completePayload(crc),3,'COMPLETE');rlog('COMPLETE Sonic8 enviado · transferencia finalizada automáticamente.');}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}function escapeAttr(s){return String(s).replace(/"/g,'');}

function cancelHps8(reset=true){runToken++;if(tx)tx.running=false;stopCamera();Sonic.stopListener();closeOverlay();if(reset){tx=null;rx=null;if($('sendBtn')){$('sendBtn').disabled=true;$('sendBtn').style.display='none';}clearProgress();setPhase('HPS8 PHOTONFOUNTAIN LISTO','on');}}
function applyMode(){if(!hps7Handlers)return;const h8=hps8Active();cancelHps8(false);try{hps7Handlers.stop?.call($('stopCameraBtn'));}catch{}for(const id of ['gridSize','streamShape','modulationMode'])if($(id))$(id).disabled=h8;if(h8){$('gridSize').value='56';$('streamShape').value='tall2';$('modulationMode').value='gray2';$('prepareBtn').onclick=prepare;$('sendBtn').onclick=showHello;$('cameraBtn').onclick=startReceiver;$('stopCameraBtn').onclick=stopCamera;$('overlayActionBtn').onclick=()=>currentOverlayAction?.();$('closeStream').onclick=()=>{if(confirm('¿Cancelar HPS8?'))cancelHps8(true);};$('prepareBtn').disabled=false;$('prepareBtn').textContent='Preparar HPS8';$('sendBtn').disabled=true;$('sendBtn').style.display='none';$('txRepairBtn').style.display='none';setHps8PanelVisible(true);clearProgress();setPhase('HPS8 PHOTONFOUNTAIN LISTO','on');if($('speedHint'))$('speedHint').textContent='HPS8 usa 2-bit DualLane. Auto Max inicia a 15 streams/s; Sonic8 elimina el Repair manual.';if($('modulationHint'))$('modulationHint').textContent='Lane A = sistemático/Auto-Repair · Lane B = símbolos Fountain XOR.';if($('layoutHint'))$('layoutHint').textContent='HPS8 PhotonFountain · Grid 56 × DualLane · 700 B por símbolo fuente.';if($('throughputHint'))$('throughputHint').textContent='Objetivo inicial: mejorar goodput eliminando NACK/Repair manual antes de subir a LightBurst 30/60.';}else{$('prepareBtn').onclick=hps7Handlers.prepare;$('sendBtn').onclick=hps7Handlers.send;$('cameraBtn').onclick=hps7Handlers.camera;$('stopCameraBtn').onclick=hps7Handlers.stop;$('overlayActionBtn').onclick=hps7Handlers.overlay;$('closeStream').onclick=hps7Handlers.close;$('txRepairBtn').onclick=hps7Handlers.repair;$('prepareBtn').disabled=false;$('prepareBtn').textContent='Preparar HPS7';$('sendBtn').disabled=true;$('sendBtn').style.display='none';setHps8PanelVisible(false);setPhase('HPS7 ADAPTIVE OPTICAL MODEM LISTO','on');}}
function install(){if(installed)return;const need=['prepareBtn','sendBtn','cameraBtn','stopCameraBtn','overlayActionBtn','closeStream','txRepairBtn'];if(need.some(id=>typeof $(id)?.onclick!=='function'))return;installed=true;hps7Handlers={prepare:$('prepareBtn').onclick,send:$('sendBtn').onclick,camera:$('cameraBtn').onclick,stop:$('stopCameraBtn').onclick,overlay:$('overlayActionBtn').onclick,close:$('closeStream').onclick,repair:$('txRepairBtn').onclick};$('protocolMode')?.addEventListener('change',applyMode);applyMode();log('HPS8 PhotonFountain instalado en paralelo; HPS7 preservado como fallback.');}
window.addEventListener('hopper:runtime-ready',()=>setTimeout(install,0));if(window.__hopperRuntimeReady)setTimeout(install,0);else setTimeout(install,1200);
window.addEventListener('pagehide',()=>cancelHps8(false));
window.__hopperHPS8={version:VERSION,active:true,protocol:'PhotonFountain',chunkSize:CHUNK,grid:GRID,bits:BITS,dualLane:true,sonicAutoRepair:true,bloomNack:true,fileProgress:true,prepare,startReceiver,cancel:cancelHps8,parsePacket,makePacket};
})();
