(() => {
'use strict';
const $=id=>document.getElementById(id);
const BASE=367,HEADER=28,PILOT=32;
let lastStep=1,runtimeReady=!!window.__hopperRuntimeReady;
function hps8Mode(){return $('protocolMode')?.value==='hps8';}
function bits(){const v=$('modulationMode')?.value||'color3';return v==='gray2'?2:v==='color3'?3:4;}
function dual(){return $('streamShape')?.value==='tall2';}
function fpsFor(b){const m=$('speedMode')?.value||'maxcal';if(m==='maxcal')return b===2?15:b===3?12:10;if(m==='compatible')return 8;if(m==='balanced')return 12;if(m==='turbo')return 15;if(m==='optical')return 18;return 12;}
function repeatFor(){return ($('speedMode')?.value||'maxcal')==='compatible'?2:1;}
function payload(grid,b){return Math.floor((grid*grid-PILOT)*b/8)-HEADER;}
function blocksLane(grid,b){return Math.max(1,Math.floor((payload(grid,b)-1)/(BASE+6)));}
function fmt(sec){sec=Math.max(0,Math.round(sec));const m=Math.floor(sec/60),s=sec%60;return m?`${m}m ${String(s).padStart(2,'0')}s`:`${s}s`;}
function setDisplay(el,value){if(el&&el.style.display!==value)el.style.display=value;}
function setText(el,value){if(el&&el.textContent!==value)el.textContent=value;}
function setCoach(title,detail,step=lastStep){lastStep=step;setText($('flowCoachTitle'),title);setText($('flowCoachDetail'),detail);document.querySelectorAll('.flowStep').forEach((e,i)=>{const n=i+1;e.classList.toggle('active',n===step);e.classList.toggle('done',n<step);});}
function syncHints(){if(hps8Mode())return;const b=bits(),grid=Number($('gridSize')?.value||56),lanes=dual()?2:1,perLane=blocksLane(grid,b),perPhysical=perLane*lanes,fps=fpsFor(b),repeat=repeatFor(),bps=perPhysical*BASE*fps/repeat,six=6*1024*1024/Math.max(1,bps);setText($('speedHint'),`${$('speedMode')?.selectedOptions?.[0]?.textContent||'Velocidad'} · ${fps} streams/s · repeat ${repeat}.`);setText($('modulationHint'),`${b}-bit · ${1<<b} símbolos · ${perLane} bloques/lane × ${lanes} lane${lanes>1?'s':''} = ${perPhysical} bloques/stream físico.`);setText($('layoutHint'),dual()?`DualLane · 2 grids ${grid}×${grid} simultáneos · misma escala física por celda.`:`Square · 1 grid ${grid}×${grid} · ${perPhysical} bloques/stream físico.`);setText($('throughputHint'),`Teórico perfecto: ${(bps/1024).toFixed(1)} KiB/s · 6 MiB ≈ ${fmt(six)} · antes de pérdidas/NACK/Repair.`);}
function syncMainButtons(){if(hps8Mode())return;const prep=$('prepareBtn'),send=$('sendBtn');if(!prep||!send)return;if(!runtimeReady){if(!prep.disabled)prep.disabled=true;setText(prep,'Inicializando HPS7…');prep.classList.add('primary');prep.classList.remove('action-secondary');setDisplay(send,'none');return;}const busy=!!window.__hopperPrepareBusy,ready=!send.disabled;if(prep.disabled!==busy)prep.disabled=busy;setText(prep,busy?'Preparando HPS7…':ready?'Repreparar':'Preparar HPS7');prep.classList.toggle('action-secondary',ready&&!busy);prep.classList.toggle('primary',!ready||busy);setDisplay(send,ready?'inline-flex':'none');if(!send.classList.contains('grow'))send.classList.add('grow');}
function syncOpticalActions(){const phase=$('phaseStatus')?.textContent||'',finish=$('finishRepairBtn');if(!finish)return;const active=!hps8Mode()&&/EMISOR · REPAIR(?! TARGET)/i.test(phase);setDisplay(finish,active?'inline-flex':'none');}
function installDocks(){const sender=$('senderActionDock');if(sender){for(const id of ['prepareBtn','sendBtn','txRepairBtn']){const b=$(id);if(b&&!sender.contains(b))sender.appendChild(b);}}const receiver=$('receiverActionDock');if(receiver){for(const id of ['cameraBtn','stopCameraBtn']){const b=$(id);if(b&&!receiver.contains(b))receiver.appendChild(b);}}}
function installFinishRepair(){const dock=$('streamActions');if(!dock||$('finishRepairBtn'))return;const b=document.createElement('button');b.id='finishRepairBtn';b.className='btn good';b.textContent='Finalizar ronda';b.style.display='none';b.title='HPS7: finaliza temprano un Repair si el receptor ya llegó a 0.';b.onclick=()=>{window.__hopperFinishRepairEarly=true;b.disabled=true;b.textContent='Finalizando…';setTimeout(()=>{b.disabled=false;b.textContent='Finalizar ronda';},1500);};dock.insertBefore(b,$('closeStream')||null);}
function coachFromPhase(){syncOpticalActions();const s=$('phaseStatus')?.textContent||'';if(/HPS8/i.test(s)){if(/ERROR/.test(s))setCoach('HPS8 encontró un error','Abre el diagnóstico y comparte el mensaje. HPS7 sigue disponible en el selector.',1);else if(/PREPARADO/.test(s))setCoach('Inicia el receptor','Después muestra HELLO HPS8. Sonic8 intentará iniciar DATA al confirmar LOCK.',2);else if(/HELLO/.test(s))setCoach('Alinea el Optical Dock','El receptor enviará ACK por Sonic8; “Iniciar HPS8” queda como fallback.',2);else if(/PHOTONFOUNTAIN|DATA/.test(s))setCoach('PhotonFountain en curso','No persigas frames perdidos: Fountain y Auto-Repair continúan acumulando información.',3);else if(/BURST TERMINADO/.test(s))setCoach('Burst terminado','Sonic8 no confirmó COMPLETE; revisa si el receptor ya reconstruyó el archivo.',4);else if(/COMPLETE|COMPLETADO/.test(s))setCoach('✓ Transferencia HPS8 completada','CRC confirmado y Auto-Repair finalizado sin intervención.',5);return;}if(/ERROR/.test(s))setCoach('HPS7 encontró un error','Recarga esta versión. Si persiste, abre Detalles técnicos.',1);else if(/PREPARADO/.test(s))setCoach('Ahora inicia la cámara del receptor','Cuando esté lista, vuelve al emisor y pulsa “Mostrar HELLO”.',2);else if(/HELLO/.test(s))setCoach('Alinea el HELLO con la cámara receptora','Espera a que el receptor confirme que la sesión quedó bloqueada antes de iniciar DATA.',2);else if(/DATA|SENDING/.test(s))setCoach('Transferencia DATA en curso','Mantén ambos teléfonos quietos y el rectángulo completo dentro de cámara.',3);else if(/PASS_END/.test(s))setCoach('Ronda terminada','El receptor calculará si falta información. Si hay NACK, léelo desde el emisor.',4);else if(/REPAIR TARGET/.test(s))setCoach('Recupera LOCK antes del Repair','Vuelve el receptor a cámara, espera LOCK y pulsa el botón inferior.',4);else if(/REPAIR/.test(s))setCoach('Repair en curso','Si el receptor llega a 0 faltantes antes de terminar, puedes finalizar la ronda.',4);else if(/DONE|COMPLET/.test(s))setCoach('Transferencia completada','Verifica el CRC y descarga el archivo reconstruido.',5);}
function observe(){const phase=$('phaseStatus');if(phase)new MutationObserver(coachFromPhase).observe(phase,{childList:true,characterData:true,subtree:true});const send=$('sendBtn');if(send)new MutationObserver(syncMainButtons).observe(send,{attributes:true,attributeFilter:['disabled']});}
window.addEventListener('hopper:runtime-ready',()=>{runtimeReady=true;window.__hopperRuntimeReady=true;if(!hps8Mode()){syncMainButtons();syncHints();setCoach('HPS7 listo para preparar','Selecciona un archivo y pulsa “Preparar HPS7”.',1);}});
window.addEventListener('hopper:runtime-error',e=>{runtimeReady=false;window.__hopperRuntimeReady=false;if(!hps8Mode()){syncMainButtons();setCoach('No se pudo iniciar HPS7',e.detail?.message||'Error del runtime. Recarga la página.',1);}});
window.addEventListener('hopper:prepare-start',()=>{if(!hps8Mode()){syncMainButtons();setCoach('Preparando HPS7','Leyendo el archivo, calculando CRC y creando bloques lógicos…',1);}});
window.addEventListener('hopper:prepare-complete',()=>{if(!hps8Mode()){syncMainButtons();setCoach('HPS7 preparado','Inicia la cámara del receptor y después muestra HELLO.',2);}});
window.addEventListener('hopper:prepare-error',e=>{if(!hps8Mode()){syncMainButtons();setCoach('No se pudo preparar el archivo',e.detail?.message||'Revisa el archivo e inténtalo de nuevo.',1);}});
window.addEventListener('hopper:hello',()=>{if(!hps8Mode())setCoach('Sesión sincronizada','La siguiente fase es DATA.',3);});
window.addEventListener('hopper:nack',e=>{if(!hps8Mode()){const m=e.detail?.missing,c=e.detail?.cycles;setCoach(`NACK recibido · ${m} faltantes`,c>1?`El Repair hará ${c} ciclos internos.`:'Se hará una pasada de Repair.',4);}});
window.addEventListener('hopper:repair-target',e=>{if(!hps8Mode())setCoach('Target de Repair listo',`Espera LOCK. Plan: ${e.detail?.cycles||1} ciclo(s).`,4);});
window.addEventListener('hopper:complete',()=>{if(!hps8Mode())setCoach('✓ Archivo reconstruido y verificado','CRC confirmado.',5);});
window.addEventListener('hopper:passend',()=>{window.__hopperFinishRepairEarly=false;syncOpticalActions();});
function install(){installDocks();installFinishRepair();syncHints();syncMainButtons();syncOpticalActions();observe();for(const id of ['gridSize','streamShape','modulationMode','speedMode'])$(id)?.addEventListener('change',()=>setTimeout(syncHints,0));$('protocolMode')?.addEventListener('change',()=>setTimeout(()=>{syncHints();syncMainButtons();coachFromPhase();},0));$('prepareBtn')?.addEventListener('click',()=>{if(!runtimeReady||hps8Mode())return;setTimeout(()=>{syncHints();syncMainButtons();},120);});if(hps8Mode())setCoach('Inicializando HPS8','PhotonFountain se habilitará cuando HPS7 termine de registrar el fallback.',1);else if(runtimeReady)setCoach('HPS7 listo para preparar','Selecciona el archivo y pulsa “Preparar HPS7”.',1);else setCoach('Inicializando HPS7','Espera un instante mientras se carga el módem óptico.',1);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
window.__hopperPremiumFlow={version:'0.10.0',guided:true,bottomDocks:true,dualAwareHints:true,earlyRepairFinish:true,runtimeGate:true,idempotentButtonSync:true,protocolAware:true};
})();
