import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {P,CURW,MX,MXP} from './three-data.js';

const svg=document.getElementById('plan2d');
let showStruct=false;
const SITE=P.o0;
const PIVOT_Z=SITE.pivot[2];
const SITE_X=Math.min(MXP(SITE.pivot[0]),MXP(SITE.pivot[1]));
const MAIN_Z=PIVOT_Z+4;
const KEEP_IDS=new Set(['a','k','b','x']);

const physItem=a=>({id:a[0],name:a[1],sub:a[2],x:MX(a[3],a[5]),z:a[4],w:a[5],d:a[6],type:a[7]});
const siteContext=()=>SITE.items.map(physItem);
const keptContext=()=>siteContext().filter(a=>KEEP_IDS.has(a.id));

function draw2Current(p){
  const S=45,ox=150,by=1690;
  const Xp=x=>ox+x*S,Y=z=>by-z*S;
  const X=x=>Xp(MXP(x));
  const tx=(x,z,t,cl='lab')=>`<text x="${Xp(x)}" y="${Y(z)}" class="${cl}">${t}</text>`;
  const pts=p.site.map(([x,z])=>`${X(x)},${Y(z)}`).join(' ');
  let s=`<style>.lot{fill:#f8fafc;stroke:#111827;stroke-width:5}.lab{font:700 17px system-ui;fill:#0f172a;text-anchor:middle}.sm{font:600 12px system-ui;fill:#475569;text-anchor:middle}.zone{stroke:#475569;stroke-width:2}.pivot{stroke:#dc2626;stroke-width:4;stroke-dasharray:12 8}.cut{fill:#fecaca;stroke:#ef4444;stroke-width:3;stroke-dasharray:7 5}.dim{font:700 13px system-ui;fill:#0369a1}</style><rect x="20" y="20" width="1160" height="2060" rx="20" fill="#fff"/><text x="600" y="55" class="lab" style="font-size:24px">${p.name}</text><polygon points="${pts}" class="lot"/>`;
  const C={existing:'#ddd6c7',porchfloor:'#e5e7eb',roof:'#d6c5a4',house:'#f7ead7',bath:'#e6f2fb',tank:'#bfdbfe'};
  for(const a of p.items){const x=MX(a[3],a[5]),cx=x+a[5]/2,cz=a[4]+a[6]/2;s+=`<rect x="${Xp(x)}" y="${Y(a[4]+a[6])}" width="${a[5]*S}" height="${a[6]*S}" fill="${C[a[7]]}" class="zone"/>`;s+=tx(cx,cz+.12,a[1])+tx(cx,cz-.20,a[2],'sm')}
  const cutX=MX(1.72,1.94);s+=`<rect x="${Xp(cutX)}" y="${Y(32.39)}" width="${1.94*S}" height="${4.88*S}" class="cut"/>${tx(cutX+.97,29.95,'SRA. MARÍA','sm')}`;
  const px1=Math.min(MXP(p.pivot[0]),MXP(p.pivot[1])),px2=Math.max(MXP(p.pivot[0]),MXP(p.pivot[1]));
  s+=`<line x1="${Xp(px1)}" y1="${Y(p.pivot[2])}" x2="${Xp(px2)}" y2="${Y(p.pivot[2])}" class="pivot"/>${tx((px1+px2)/2,p.pivot[2]-.45,'PIVOTE NUEVO PROYECTO','sm')}${tx(CURW/2,-.62,'FRENTE 17.73 m · OESTE','dim')}<text x="70" y="110" class="dim">IZQUIERDA FÍSICA</text><text x="1130" y="110" class="dim" text-anchor="end">DERECHA FÍSICA</text><text x="600" y="2030" class="sm">Estado actual · frente abajo · croquis orientado para conservar izquierda/derecha físicas.</text>`;
  svg.innerHTML=s;
}

function draw2Mounted(p){
  const S=45,ox=150,by=1690;
  const X=x=>ox+x*S,Y=z=>by-z*S;
  const tx=(x,z,t,cl='lab')=>`<text x="${X(x)}" y="${Y(z)}" class="${cl}">${t}</text>`;
  const rc=(x,z,w,d,c,cl='zone')=>`<rect x="${X(x)}" y="${Y(z+d)}" width="${w*S}" height="${d*S}" fill="${c}" class="${cl}"/>`;
  const pts=SITE.site.map(([x,z])=>`${X(MXP(x))},${Y(z)}`).join(' ');
  const C={existing:'#ddd6c7',bath:'#e6f2fb',tank:'#bfdbfe',room:'#fff',social:'#eef8ef',kitchen:'#fff6df',hall:'#d1fae5',closet:'#f2e9fb',utility:'#f7eee6'};
  let s=`<style>.lot{fill:#f8fafc;stroke:#111827;stroke-width:5}.lab{font:700 16px system-ui;fill:#0f172a;text-anchor:middle}.sm{font:600 11px system-ui;fill:#475569;text-anchor:middle}.zone{stroke:#64748b;stroke-width:2}.wall{stroke:#111827;stroke-width:6}.door{stroke:#9a5f3b;stroke-width:4;fill:none}.win{stroke:#0ea5e9;stroke-width:8;stroke-linecap:round}.pivot{stroke:#dc2626;stroke-width:4;stroke-dasharray:12 8}.cut{fill:#fecaca;stroke:#ef4444;stroke-width:3;stroke-dasharray:7 5}.beam{stroke:#d97706;stroke-width:3;stroke-dasharray:12 8;opacity:.7}.foot{fill:#f59e0b22;stroke:#d97706;stroke-width:2;stroke-dasharray:7 5}.col{fill:#9a3412;stroke:#7c2d12;stroke-width:2}.dim{font:700 13px system-ui;fill:#0369a1}</style><rect x="20" y="20" width="1160" height="2060" rx="20" fill="#fff"/><text x="600" y="55" class="lab" style="font-size:24px">${p.name} · sobre terreno real</text><polygon points="${pts}" class="lot"/>`;
  for(const a of keptContext()){s+=rc(a.x,a.z,a.w,a.d,C[a.type]||C.existing);s+=tx(a.x+a.w/2,a.z+a.d/2+.12,a.name)+tx(a.x+a.w/2,a.z+a.d/2-.20,a.sub,'sm')}
  const cutX=MX(1.72,1.94);s+=`<rect x="${X(cutX)}" y="${Y(32.39)}" width="${1.94*S}" height="${4.88*S}" class="cut"/>${tx(cutX+.97,29.95,'SRA. MARÍA','sm')}`;
  s+=rc(SITE_X,PIVOT_Z,8,4,'#eadfc9')+tx(SITE_X+4,PIVOT_Z+2,'PORCHE FRONTAL 8×4');
  s+=rc(SITE_X,MAIN_Z,8,16,'#fff');
  s+=rc(SITE_X,MAIN_Z+16,8,2,'#eadfc9')+tx(SITE_X+4,MAIN_Z+17,'PORCHE TRASERO 8×2');
  for(const a of p.spaces){if(a[0]==='a')continue;const x=SITE_X+a[3],z=MAIN_Z+a[4];s+=rc(x,z,a[5],a[6],C[a[7]]||'#fff')}
  const wallLine=w=>w.o==='h'?`<line x1="${X(SITE_X+w.a)}" y1="${Y(MAIN_Z+w.z)}" x2="${X(SITE_X+w.b)}" y2="${Y(MAIN_Z+w.z)}" class="wall"/>`:`<line x1="${X(SITE_X+w.x)}" y1="${Y(MAIN_Z+w.a)}" x2="${X(SITE_X+w.x)}" y2="${Y(MAIN_Z+w.b)}" class="wall"/>`;
  for(const w of p.walls){if((w.o==='h'&&w.a>=8)||(w.o==='v'&&w.x>8))continue;s+=wallLine(w)}
  const annexDoor=p.doors?.find(d=>d.id==='a'&&d.w==='v');if(annexDoor)s+=`<line x1="${X(SITE_X+annexDoor.x)}" y1="${Y(MAIN_Z+annexDoor.z)}" x2="${X(SITE_X+annexDoor.x)}" y2="${Y(MAIN_Z+annexDoor.z+annexDoor.l)}" class="wall"/>`;
  for(const d of p.doors||[]){if(d.id==='a')continue;const x=X(SITE_X+d.x),y=Y(MAIN_Z+d.z),r=d.l*S;if(d.w==='h')s+=`<path d="M${x} ${y}h${r}" class="door"/>`;else s+=`<path d="M${x} ${y}v${-r}" class="door"/>`}
  for(const w of p.windows||[]){if(w[0]==='h')s+=`<line x1="${X(SITE_X+w[1])}" y1="${Y(MAIN_Z+w[2])}" x2="${X(SITE_X+w[1]+w[3])}" y2="${Y(MAIN_Z+w[2])}" class="win"/>`;else s+=`<line x1="${X(SITE_X+w[1])}" y1="${Y(MAIN_Z+w[2])}" x2="${X(SITE_X+w[1])}" y2="${Y(MAIN_Z+w[2]+w[3])}" class="win"/>`}
  if(p.columns&&showStruct){for(const x of [0,4,8])s+=`<line x1="${X(SITE_X+x)}" y1="${Y(MAIN_Z)}" x2="${X(SITE_X+x)}" y2="${Y(MAIN_Z+16)}" class="beam"/>`;for(const z of [0,4,8,12,16])s+=`<line x1="${X(SITE_X)}" y1="${Y(MAIN_Z+z)}" x2="${X(SITE_X+8)}" y2="${Y(MAIN_Z+z)}" class="beam"/>`;const fs=1.5*S,cs=.3*S;for(const q of p.columns){const cx=X(SITE_X+q[1]),cy=Y(MAIN_Z+q[2]);s+=`<rect x="${cx-fs/2}" y="${cy-fs/2}" width="${fs}" height="${fs}" class="foot"/><rect x="${cx-cs/2}" y="${cy-cs/2}" width="${cs}" height="${cs}" class="col"/>`}}
  for(const a of p.spaces){if(a[0]==='a')continue;s+=tx(SITE_X+a[3]+a[5]/2,MAIN_Z+a[4]+a[6]/2+.1,a[1])+tx(SITE_X+a[3]+a[5]/2,MAIN_Z+a[4]+a[6]/2-.18,a[2],'sm')}
  s+=`<line x1="${X(SITE_X)}" y1="${Y(PIVOT_Z)}" x2="${X(SITE_X+8)}" y2="${Y(PIVOT_Z)}" class="pivot"/>${tx(SITE_X+4,PIVOT_Z-.45,'INICIO DEL PORCHE / PIVOTE','sm')}${tx(CURW/2,-.62,'FRENTE 17.73 m · OESTE','dim')}<text x="70" y="110" class="dim">IZQUIERDA FÍSICA</text><text x="1130" y="110" class="dim" text-anchor="end">DERECHA FÍSICA</text><text x="600" y="2030" class="sm">Terreno y elementos existentes conservados · solo se reemplaza el volumen central por la propuesta seleccionada.</text>`;
  svg.innerHTML=s;
}
function draw2(p){p.current?draw2Current(p):draw2Mounted(p)}

const c=document.getElementById('scene3d'),sc=new THREE.Scene();sc.background=new THREE.Color(0x0a1020);const rr=new THREE.WebGLRenderer({canvas:c,antialias:true});rr.setPixelRatio(Math.min(devicePixelRatio,2));rr.shadowMap.enabled=true;const cam=new THREE.PerspectiveCamera(48,1,.1,300),ctl=new OrbitControls(cam,c);ctl.enableDamping=true;sc.add(new THREE.HemisphereLight(0xffffff,0x223344,1.7));const sun=new THREE.DirectionalLight(0xffffff,1);sun.position.set(16,24,14);sc.add(sun);const root=new THREE.Group();sc.add(root);
const M={wall:new THREE.MeshStandardMaterial({color:0xf3efe7}),floor:new THREE.MeshStandardMaterial({color:0xc9d4df}),porch:new THREE.MeshStandardMaterial({color:0xb8aa92}),glass:new THREE.MeshStandardMaterial({color:0x67c8ef,transparent:true,opacity:.42,roughness:.12,metalness:.05}),frame:new THREE.MeshStandardMaterial({color:0x303842,roughness:.45,metalness:.35}),bed:new THREE.MeshStandardMaterial({color:0xf8fafc}),closet:new THREE.MeshStandardMaterial({color:0xc9b6db}),column:new THREE.MeshStandardMaterial({color:0x8f3b21,roughness:.65}),beam:new THREE.MeshStandardMaterial({color:0xb86f25,roughness:.65}),footing:new THREE.MeshStandardMaterial({color:0xd99b45,transparent:true,opacity:.5,roughness:.8}),ground:new THREE.MeshStandardMaterial({color:0x8fa07e,roughness:1}),existing:new THREE.MeshStandardMaterial({color:0xd7c5aa}),roof:new THREE.MeshStandardMaterial({color:0x806345}),tank:new THREE.MeshStandardMaterial({color:0x86bcd4})};
function box(x,z,w,d,h,m,y=h/2,g=root){const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);q.position.set(x+w/2,y,-(z+d/2));q.castShadow=true;q.receiveShadow=true;g.add(q);return q}
function clear(){while(root.children.length)root.remove(root.children[0])}
function lab(t,x,z){const cn=document.createElement('canvas'),x2=cn.getContext('2d');cn.width=420;cn.height=90;x2.fillStyle='#08101ed9';x2.fillRect(0,10,420,70);x2.fillStyle='#fff';x2.font='600 23px system-ui';x2.textAlign='center';x2.fillText(t,210,53);const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(cn),transparent:true,depthTest:false}));sp.position.set(x,.18,-z);sp.scale.set(2.9,.65,1);root.add(sp)}
const WALL_H=2.8,FRAME=.055;
function win3At(w,dx,dz){const o=w[0],x=dx+w[1],z=dz+w[2],l=w[3],h=w[4],s=w[5],top=Math.max(0,WALL_H-s-h);if(o==='h'){if(s>0)box(x,z-.06,l,.12,s,M.wall,s/2);if(top>0)box(x,z-.06,l,.12,top,M.wall,s+h+top/2);box(x,z-.08,FRAME,.16,h,M.frame,s+h/2);box(x+l-FRAME,z-.08,FRAME,.16,h,M.frame,s+h/2);box(x,z-.08,l,.16,FRAME,M.frame,s+FRAME/2);box(x,z-.08,l,.16,FRAME,M.frame,s+h-FRAME/2);box(x+FRAME,z-.045,Math.max(.02,l-2*FRAME),.09,Math.max(.02,h-2*FRAME),M.glass,s+h/2)}else{if(s>0)box(x-.06,z,.12,l,s,M.wall,s/2);if(top>0)box(x-.06,z,.12,l,top,M.wall,s+h+top/2);box(x-.08,z,.16,FRAME,h,M.frame,s+h/2);box(x-.08,z+l-FRAME,.16,FRAME,h,M.frame,s+h/2);box(x-.08,z,.16,l,FRAME,M.frame,s+FRAME/2);box(x-.08,z,.16,l,FRAME,M.frame,s+h-FRAME/2);box(x-.045,z+FRAME,.09,Math.max(.02,l-2*FRAME),Math.max(.02,h-2*FRAME),M.glass,s+h/2)}}
function doorHeadAt(d,dx,dz){const dh=2.1,head=WALL_H-dh;if(head<=0||d.id==='a')return;if(d.w==='h')box(dx+d.x,dz+d.z-.06,d.l,.12,head,M.wall,dh+head/2);else box(dx+d.x-.06,dz+d.z,.12,d.l,head,M.wall,dh+head/2)}
function drawSiteGround(){const shape=new THREE.Shape(),pts=SITE.site.map(([x,z])=>[MXP(x),z]);shape.moveTo(pts[0][0],pts[0][1]);for(let i=1;i<pts.length;i++)shape.lineTo(pts[i][0],pts[i][1]);shape.closePath();const floor=new THREE.Mesh(new THREE.ShapeGeometry(shape),M.ground);floor.rotation.x=-Math.PI/2;floor.position.y=.01;floor.receiveShadow=true;root.add(floor)}
function drawExistingItems(items){for(const a of items){const {x,z,w,d,type,name}=a;if(type==='porchfloor'){box(x,z,w,d,.08,M.porch,.04);lab(name,x+w/2,z+d/2)}else if(type==='roof'){box(x,z,w,d,.12,M.roof,2.65);for(const xx of [x+.15,x+w-.15])for(const zz of [z+.15,z+d-.15])box(xx-.04,zz-.04,.08,.08,2.6,M.roof,1.3);lab(name,x+w/2,z+d/2)}else if(type==='tank'){box(x,z,w,d,1.6,M.tank,.8);lab(name,x+w/2,z+d/2)}else{const h=type==='bath'?2.4:2.8;box(x,z,w,d,h,type==='bath'?M.floor:M.existing,h/2);lab(name,x+w/2,z+d/2)}}}
function struct3At(p,dx,dz){if(!p.columns||!showStruct)return;for(const q of p.columns){box(dx+q[1]-.75,dz+q[2]-.75,1.5,1.5,.45,M.footing,-.18);box(dx+q[1]-.15,dz+q[2]-.15,.3,.3,WALL_H,M.column,WALL_H/2)}for(const x of [0,4,8])box(dx+x-.125,dz,.25,16,.4,M.beam,WALL_H-.2);for(const z of [0,4,8,12,16])box(dx,dz+z-.125,8,.25,.4,M.beam,WALL_H-.2)}
function draw3Current(){drawSiteGround();drawExistingItems(siteContext());lab('FRENTE · OESTE',CURW/2,-1.2);const gr=new THREE.GridHelper(50,50);gr.position.set(CURW/2,.005,-16);root.add(gr)}
function draw3Mounted(p){drawSiteGround();drawExistingItems(keptContext());box(SITE_X,PIVOT_Z,8,4,.08,M.porch,.04);box(SITE_X,MAIN_Z,8,16,.08,M.floor,.04);box(SITE_X,MAIN_Z+16,8,2,.08,M.porch,.04);for(const w of p.walls){if((w.o==='h'&&w.a>=8)||(w.o==='v'&&w.x>8))continue;if(w.o==='h')box(SITE_X+w.a,MAIN_Z+w.z-.06,w.b-w.a,.12,WALL_H,M.wall,WALL_H/2);else box(SITE_X+w.x-.06,MAIN_Z+w.a,.12,w.b-w.a,WALL_H,M.wall,WALL_H/2)}const annexDoor=p.doors?.find(d=>d.id==='a'&&d.w==='v');if(annexDoor)box(SITE_X+annexDoor.x-.06,MAIN_Z+annexDoor.z,.12,annexDoor.l,WALL_H,M.wall,WALL_H/2);for(const d of p.doors||[])doorHeadAt(d,SITE_X,MAIN_Z);for(const w of p.windows||[])win3At(w,SITE_X,MAIN_Z);struct3At(p,SITE_X,MAIN_Z);for(const a of p.spaces){if(a[0]==='a')continue;const x=SITE_X+a[3],z=MAIN_Z+a[4];if(a[7]==='room'){const g=new THREE.Group();box(-.75,-.9,1.5,1.8,.22,M.bed,.16,g);if(a[5]<a[6])g.rotation.y=Math.PI/2;g.position.set(x+a[5]/2,0,-(z+a[6]/2));root.add(g)}if(a[7]==='closet')box(x+.08,z+.08,Math.max(.2,a[5]-.16),Math.max(.2,a[6]-.16),1.4,M.closet,.7);lab(a[1],x+a[5]/2,z+a[6]/2)}lab('PORCHE FRONTAL · INICIO DEL PROYECTO',SITE_X+4,PIVOT_Z+2);lab('PORCHE TRASERO',SITE_X+4,MAIN_Z+17);lab('FRENTE · OESTE',CURW/2,-1.2);const gr=new THREE.GridHelper(50,50);gr.position.set(CURW/2,.005,-16);root.add(gr)}
function draw3(p){clear();p.current?draw3Current():draw3Mounted(p)}

const vw={p:[[8.865,24,26],[8.865,0,-16],'Vista 3D · terreno real'],f:[[8.865,14,44],[8.865,1,-16],'Frente · Oeste'],r:[[8.865,14,-62],[8.865,1,-16],'Fondo · Este'],l:[[-40,14,-16],[8.865,1,-16],'Lado izquierdo físico'],d:[[58,14,-16],[8.865,1,-16],'Lado derecho físico']};
let cur='o0',mode='3',cv='p';
function setCam(k){cv=k;const v=vw[k];cam.position.set(...v[0]);ctl.target.set(...v[1]);ctl.update();document.querySelectorAll('[data-cam]').forEach(b=>b.classList.toggle('active',b.dataset.cam===k));document.getElementById('mp').textContent=mode==='2'?'Vista 2D':v[2]}
function info(){const p=P[cur];document.getElementById('sum').innerHTML=`<span>Habitaciones</span><b>${p.rooms}</b><span>Área / dormitorio</span><b>${p.room}</b><span>Baños</span><b>${p.baths}</b><span>Vestidores</span><b>${p.vest}</b>${p.windows?`<span>Ventanas</span><b>${p.windows.length} aperturas</b>`:''}${p.structure?`<span>Estructura base</span><b style="text-align:right">${p.structure}</b>`:''}`;document.getElementById('note').textContent=p.current?p.note:`${p.note} Esta propuesta está montada sobre el terreno real: se conservan construcción frontal, tanque, baño anexo existente, bloque lateral y recorte de la Sra. María; se reemplaza únicamente el volumen central.`;document.getElementById('hp').textContent=p.name;document.getElementById('bS').disabled=cur!=='o3';document.getElementById('bS').classList.toggle('active',cur==='o3'&&showStruct);document.getElementById('bt').textContent=p.current?'Opción 0 · Estado construido actual.':cur==='o3'?(showStruct?'Opción 3 sobre terreno real · estructura ON.':'Opción 3 sobre terreno real · estructura OFF.'):`${p.name} · montada desde el pivote real del porche delantero.`}
function apply(){draw2(P[cur]);draw3(P[cur]);info();setCam(cv)}
function setMode(m){mode=m;const two=m==='2';document.getElementById('planWrap').classList.toggle('hidden',!two);c.classList.toggle('hidden',two);b2.classList.toggle('active',two);b3.classList.toggle('active',!two);if(!two){resize();setCam(cv)}else document.getElementById('mp').textContent='Vista 2D'}
const design=document.getElementById('design'),b2=document.getElementById('b2'),b3=document.getElementById('b3'),bS=document.getElementById('bS'),menu=document.getElementById('menu'),panel=document.getElementById('panel');design.onchange=e=>{cur=e.target.value;apply()};b2.onclick=()=>setMode('2');b3.onclick=()=>setMode('3');bS.onclick=()=>{if(cur!=='o3')return;showStruct=!showStruct;apply()};document.querySelectorAll('[data-cam]').forEach(b=>b.onclick=()=>{setMode('3');setCam(b.dataset.cam)});menu.onclick=()=>panel.classList.toggle('open');function resize(){rr.setSize(c.clientWidth,c.clientHeight,false);cam.aspect=c.clientWidth/c.clientHeight;cam.updateProjectionMatrix()}addEventListener('resize',resize);resize();apply();setCam('p');rr.setAnimationLoop(()=>{ctl.update();rr.render(sc,cam)});