import test from 'node:test';import assert from 'node:assert/strict';
import {profile,PROFILES,headerBytes,parseHeader,randomBytes,decodeReport,encodeReport,CATALOG_HASH,fourOpportunitySchedules} from '../protocol.js';
import {render,AdaptiveTracker} from '../optics.js';import {RasterCanvas} from './raster.mjs';
import {createTrial,TrialResult,CalibrationSender,CalibrationReceiver,reportFor} from '../calibration.js';
import {AudioDecoder,synthesize,spectralFeatures,packAudio,unpackAudio,AUDIO,decodeHamming,encodeHamming} from '../audio-codec.js';
import {prepareTransfer,DownloadSession} from '../../src/transfer-metrics.js';import {buildTransport} from '../../src/superstream.js';
import {crc32} from '../../src/crc32.js';
const tracker=()=>{const t=Object.create(AdaptiveTracker.prototype);t.lastProfile=0;t.stats={headers:0,valid:0,crcFailed:0,motion:0};return t;};
function decodeFrame(f,p,sid,seq,t){const h=parseHeader(headerBytes(f,p,sid,seq,t.frames.length,t.streamLength));return{header:h,payload:f.payload,crcOK:true,motion:0};}
test('all 11 catalog profiles have disjoint reserved pilots, enough header and payload capacity',()=>{for(const p of PROFILES){assert(p.headerCells.length>=320);assert(p.payloadBytes>100);assert(p.cells.length*p.bits>=p.payloadBytes*8);const keys=new Set([...p.cells,...p.pilots,...p.headerCells].map(a=>a[0]+','+a[1]));assert.equal(keys.size,p.cells.length+p.pilots.length+p.headerCells.length);}});
test('Lighthouse -> geometric refinement -> per-region colour classifier -> CRC for every profile',()=>{for(const p of PROFILES){const c=new RasterCanvas(),t=createTrial(44,p.id,1).transport,f={...t.frames[0],kind:3,round:1};render(c,f,p,44,0,t.frames.length,t.streamLength);const rx=tracker(),found=rx.detectBeacons(c.data,c.width,c.height,null);assert(found);const q=rx.refine(c.data,c.width,c.height,found.quad),d=rx.decodeAdaptive(c.data,c.width,c.height,q);assert(d?.crcOK,'profile '+p.id);assert.deepEqual(d.payload,f.payload);assert.equal(d.header.round,1);}});
test('header CRC rejects corrupted profile, session and sequence before allocation',()=>{const {p,transport:t}=createTrial(45,1,0),h=headerBytes(t.frames[0],p,45,0,t.frames.length,t.streamLength);assert(parseHeader(h));for(const i of [5,8,12,25,27]){const b=h.slice();b[i]^=2;assert.equal(parseHeader(b),null);}});
test('held-out trial rounds reject previous probes and account for completely missed headers',()=>{const r=new TrialResult(9,1,1),t=r.transport;for(let i=0;i<t.frames.length;i++){const f={...t.frames[i],kind:3,round:0};assert.equal(r.ingest(decodeFrame(f,r.p,9,i,t),i*60),false);}const out=r.finish(2000);assert.equal(out.expected,t.frames.length);assert.equal(out.valid,0);assert.equal(out.pass,false);});
test('trial recovery runs the real RS decoder and compares reconstructed known bytes',()=>{const r=new TrialResult(9,1,1),t=r.transport;for(let i=0;i<t.frames.length;i++){const f={...t.frames[i],kind:3,round:1};if(f.slot===1)continue;r.ingest(decodeFrame(f,r.p,9,i,t),i*60);}const out=r.finish(2200);assert(out.pass);assert.equal(out.recoveredBytes,r.source.length);assert(out.valid<out.expected);});
test('QR reports bind session, epoch, catalogue and CRC; no profile from foreign input',()=>{const r={sid:88,epoch:2,catalog:CATALOG_HASH,chosen:2,fallback:1,fingerprint:433};const s=encodeReport(r);assert.deepEqual(decodeReport(s,88),r);assert.equal(decodeReport(s,89),null);assert.equal(decodeReport(s.replace('433','434'),88),null);assert.equal(decodeReport(encodeReport({...r,chosen:999}),88),null);});
test('four offset opportunities preserve block IDs and include each systematic block exactly four times',()=>{const t=createTrial(33,1,0).transport,s=fourOpportunitySchedules(t).flat();for(let i=0;i<t.frames.length;i++)assert.equal(s.filter(x=>x===i).length,t.frames[i].kind===0?4:1);});
test('audio packet CRC + Hamming survive one error per codeword and reject corrupted commands',()=>{const a={type:AUDIO.COMPLETE,band:1,sid:12345,seq:2,arg0:2,arg1:123456789,token:5},bytes=packAudio(a),bits=encodeHamming(bytes);for(let i=0;i<bits.length;i+=12)bits[i+5]^=1;assert.deepEqual(unpackAudio(decodeHamming(bits)),a);bytes[6]^=1;assert.equal(unpackAudio(bytes),null);});
test('real 4-FSK waveform and production Goertzel decoder at 44.1/48 kHz with noise and arbitrary phase',()=>{for(const sr of [44100,48000])for(const band of [0,1,2]){const a={type:1,band,sid:1234,seq:2,arg0:2,arg1:777,token:0},source=synthesize(a,sr,.10),input=new Float32Array(source.length+Math.round(sr*.35)),offset=Math.round(sr*.057);input.set(source,offset);let x=31;for(let i=0;i<input.length;i++){x=(Math.imul(x,1664525)+1013904223)>>>0;input[i]+=(x/4294967296-.5)*.005;}const window=Math.round(sr*.010),hop=Math.round(sr*.005),got=[],d=new AudioDecoder(p=>got.push(p));for(let i=0;i+window<=input.length;i+=hop)d.push((i+window/2)/sr,spectralFeatures(input.subarray(i,i+window),sr));assert(got.some(p=>p.sid===a.sid&&p.arg1===a.arg1),'band '+band+' sr '+sr);}});
test('silence and unrelated tone never produce COMPLETE',()=>{const sr=48000,input=new Float32Array(sr*4);for(let i=0;i<input.length;i++)input[i]=.1*Math.sin(2*Math.PI*1700*i/sr);const got=[],d=new AudioDecoder(p=>got.push(p));for(let i=0;i+480<=input.length;i+=240)d.push((i+240)/sr,spectralFeatures(input.subarray(i,i+480),sr));assert.equal(got.length,0);});
test('full state-machine handshake includes audio direction, independent validation and final recheck',()=>{
 let now=0,sender,receiver,pending=[],ready=false;receiver=new CalibrationReceiver(e=>{if(e.type==='play-training')pending.push({at:now+3000,p:e.packet});if(e.type==='report')pending.push({at:now+3000,p:{type:AUDIO.REPORT,band:0,sid:e.report.sid,seq:e.report.epoch,arg0:e.report.chosen,arg1:e.report.fingerprint,token:e.report.fallback}});if(e.type==='offer')pending.push({at:now+3000,p:{type:AUDIO.READY,band:0,sid:e.report.sid,seq:e.report.epoch,arg0:e.report.chosen,arg1:e.report.fingerprint}});});
 sender=new CalibrationSender({sid:77,audio:true,mode:'quick',onEvent:e=>{if(e.type==='control')receiver.control(e.c,now);if(e.type==='probe'){const d=decodeFrame(e.f,e.p,77,e.seq,e.t);receiver.ingest(d,now);}if(e.type==='ready')ready=true;}});sender.start(now);for(now=0;now<120000&&!ready;now+=10){sender.tick(now);for(let i=pending.length-1;i>=0;i--)if(pending[i].at<=now){sender.receiveAudio({...pending[i].p,margin:20},now);pending.splice(i,1);}}assert(ready,'state '+sender.state);assert.equal(sender.round,2);assert(receiver.results.some(r=>r.round===1));assert(receiver.results.some(r=>r.round===2));assert.equal(sender.selected.chosen,receiver.report.chosen);
});
test('stale or foreign READY cannot finish negotiation; loss of all probes produces no report',()=>{const s=new CalibrationSender({sid:13});s.state='offer';s.selected={chosen:1,fingerprint:123};assert.equal(s.receiveAudio({type:AUDIO.READY,sid:14,arg0:1,arg1:123,seq:s.epoch},100),false);assert.equal(s.ended,false);assert.equal(reportFor(3,1,[{id:1,pass:false,score:0}]),null);});
test('negotiated DATA still reconstructs the original file, including missing frames and Unicode filename',async()=>{const source=randomBytes(18000,453),packed=await prepareTransfer(new File([source],'archivo 🪐.png')),p=profile(2),t=buildTransport(packed.stream,p),d=new DownloadSession();for(let seq=0;seq<t.frames.length;seq++){const f=t.frames[seq];if(f.slot===1)continue;d.ingest(decodeFrame(f,p,packed.meta.linkId,seq,t));}assert(d.progress().complete);const verified=await d.verify();assert.deepEqual(verified.data,source);assert.equal(verified.meta.name,'archivo 🪐.png');assert.equal(d.metrics().percent,100);});
