/* Rendering and interaction. Game state comes only from engine.js. */
(function(){'use strict';
const E=window.FlowLab,$=id=>document.getElementById(id);
let state=E.init(),busy=false,epoch=0,history=[],demoSnapshot=null,selectedLane=1,trackingId=-1,routes=true,speed=1,audioEnabled=false,audio=null,hoverIndex=-1;
const palette={cyan:['#24dcee','#0c5f9b'],green:['#67ec91','#176b59'],pink:['#fa71c2','#a0298c'],orange:['#ffa158','#a94b32'],yellow:['#ffe570','#aa8126']};
const names={cyan:'Cian',green:'Verde',pink:'Rosa',orange:'Naranja',yellow:'Amarillo',normal:'Normal',seeker:'Seeker',slash:'Slash',beam:'Beam',burst:'Burst',prism:'Prism',relic:'Core Relic',block:'Bloqueo'};
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const xy=i=>({x:160+E.col(i)*64,y:214+E.row(i)*64+(E.row(i)>=state.split?88:0)});
const gateY=()=>xy(E.at(state.split,0)).y-42;
const outY=()=>172,inY=()=>793;
function defs(){return `<defs>${Object.entries(palette).map(([k,a])=>`<linearGradient id="tile-${k}" x2=".2" y2="1"><stop stop-color="${a[0]}"/><stop offset="1" stop-color="${a[1]}"/></linearGradient>`).join('')}<linearGradient id="metal" x2=".3" y2="1"><stop stop-color="#7790a7"/><stop offset=".22" stop-color="#263d53"/><stop offset="1" stop-color="#0c182c"/></linearGradient><linearGradient id="gold" x2=".5" y2="1"><stop stop-color="#fff0b3"/><stop offset=".45" stop-color="#d7a867"/><stop offset="1" stop-color="#684224"/></linearGradient><linearGradient id="crystal" x2=".8" y2="1"><stop stop-color="#d9ffff"/><stop offset=".45" stop-color="#4debe2"/><stop offset="1" stop-color="#a26ef3"/></linearGradient><radialGradient id="plasma"><stop stop-color="#ffffff"/><stop offset=".35" stop-color="#ffe8b1"/><stop offset="1" stop-color="#fb8e6450"/></radialGradient><filter id="glow" x="-80%" y="-80%" width="260%" height="260%"><feGaussianBlur stdDeviation="2.2"/></filter></defs>`;}
function symbol(kind,color){const h=palette[color]?.[0]||'#67ede1';
 if(kind==='seeker')return `<path d="M-8-3L-23 1-26 10-9 5M8-3L23 1 26 10 9 5" fill="#98dbe4" stroke="#fff" stroke-opacity=".6"/><path d="M0-20L10-7 7 13 0 20-7 13-10-7Z" fill="url(#metal)" stroke="#8ee7ed" stroke-width="1.6"/><circle cy="-4" r="4.5" fill="#b6fff5"/><path d="M-4 14L0 25 4 14" fill="#48e0ed"/><path d="M-20 8V14M20 8V14" stroke="#61ffff" stroke-width="2.5"/>`;
 if(kind==='slash'||kind==='beam')return `<g transform="rotate(${kind==='beam'?90:0})"><path d="M-24-4H24V4H-24Z" fill="#ebfbff"/><path d="M-22-9L-29 0-22 9M22-9L29 0 22 9" fill="none" stroke="${h}" stroke-width="3"/><rect x="-10" y="-8" width="20" height="16" rx="4" fill="url(#metal)" stroke="#c2f5fc"/><path d="M-5 0H5" stroke="#fff" stroke-width="3"/></g>`;
 if(kind==='burst')return `<circle r="21" fill="#321e28" stroke="#a68c8a" stroke-width="3"/>${Array.from({length:8},(_,k)=>`<path d="M0-21V-15" transform="rotate(${k*45})" stroke="#ffcb9c" stroke-width="4"/>`).join('')}<circle r="12" fill="url(#plasma)"/><circle r="5" fill="#fff3cf"/>`;
 if(kind==='prism')return `<path d="M0-25L20-7 14 15 0 25-14 15-20-7Z" fill="url(#crystal)" stroke="#e7dcff" stroke-width="1.6"/><path d="M0-25L-5-5 0 25 12-4Z" fill="#f1deff" fill-opacity=".55"/><path d="M-20-7L12-4 20-7M-5-5L-14 15" stroke="#fff" stroke-opacity=".7"/><circle cy="-4" r="4" fill="${h}" stroke="#172844" stroke-width="2"/>`;
 if(kind==='relic')return `<ellipse rx="24" ry="17" transform="rotate(-28)" fill="none" stroke="#bb9658" stroke-width="4" stroke-dasharray="31 10"/><path d="M0-27L11-7 8 12 0 26-9 10-11-8Z" fill="url(#crystal)" stroke="#b5f9f1" stroke-width="1.2"/><path d="M0-27L-2-5 0 26 7-5Z" fill="#edffff" fill-opacity=".56"/><path d="M-21-1L-24-7-18-12M21 0L24 7 18 12" fill="none" stroke="#ffe5a0" stroke-width="3"/><circle cy="-5" r="3" fill="#fff"/>`;
 return `<path d="M-7-3H7M-3-7V7" fill="none" stroke="#fff" stroke-opacity=".3" stroke-width="1.5"/>`;
}
function tile(p,x=0,y=0,scale=1,opacity=1){if(!p)return'';const color=p.color||'cyan',sp=E.special(p.kind),block=p.kind==='block',rel=p.kind==='relic';let s=`<g transform="translate(${x} ${y}) scale(${scale})" opacity="${opacity}">`;
 if(!rel){s+=`<rect x="-28" y="-25" width="56" height="57" rx="10" fill="#020915"/><path class="tile-body" d="M-20-28H20L28-20V20L20 28H-20L-28 20V-20Z" fill="${sp?'url(#metal)':block?'#384452':`url(#tile-${color})`}" stroke="${sp?'#799cae':block?'#81909f':palette[color][0]}" stroke-width="1.2"/><path d="M-19-24H19L24-19M-24-18V17" fill="none" stroke="#fff" stroke-opacity=".42" stroke-width="1.2"/><path d="M-20 23H20L24 19" fill="none" stroke="#000" stroke-opacity=".27" stroke-width="3"/>`;}
 else s+=`<ellipse cy="25" rx="20" ry="4" fill="#040a17"/>`;
 if(block)s+=`<path d="M-19-16L-5-10-10 0 3 6 0 21M-5-10L5-21M3 6L20 0" stroke="#ffa574" stroke-width="2" fill="none"/><path d="M-21-18L-18-21M18 20L21 17" stroke="#d3dae4"/><g fill="#fbd8a8">${Array.from({length:p.hp},(_,i)=>`<circle cx="${(i-(p.hp-1)/2)*9}" cy="15" r="2.5"/>`).join('')}</g>`;
 else s+=symbol(p.kind,color);
 if(p.id===trackingId)s+=`<rect x="-31" y="-31" width="62" height="64" rx="11" stroke="#fff3b0" stroke-width="2.5" fill="none"/><circle cy="-33" r="4" fill="#fff5bc"/>`;
 return s+'</g>';
}
function portalPath(c){const x=160+c*64,side=c<3?65-c*16:575+(c-3)*16;return `M${x},779 V793 Q${x},811 ${side},811 V177 Q${side},155 ${x},155 V187`;}
function staticBoard(){const gy=gateY(),topEnd=xy(E.at(state.split-1,0)).y+32;
 let a=defs()+`<g id="back"><rect x="118" y="22" width="404" height="115" rx="14" fill="#0e192b" stroke="#35465c"/><text x="136" y="41" class="svg-label">INCOMING</text><text x="506" y="41" text-anchor="end" class="svg-label" style="font-size:8px;fill:#76e3c8">3 VISIBLES / CARRIL</text><path d="M523 100H620V${gy}H520" stroke="#456474" stroke-width="1.5" stroke-dasharray="3 4" fill="none"/><text x="632" y="${(gy+100)/2}" fill="#87adb9" font-size="8" transform="rotate(90 632 ${(gy+100)/2})" text-anchor="middle">TRANSFERENCIA INCOMING</text>`;
 for(let c=0;c<6;c++){let active=c===selectedLane,stroke=active?'#5fe7de':'#637eaa';a+=`<path d="${portalPath(c)}" class="route-path ${routes?'animated-route':''}" stroke="${stroke}" opacity="${routes?(active?.8:.2):.05}"/>`;}
 a+=`<rect x="117" y="181" width="406" height="${topEnd-173}" rx="13" fill="#172438" stroke="#3c4c65"/><rect x="117" y="${gy+15}" width="406" height="${784-(gy+15)}" rx="13" fill="#142839" stroke="#356069"/><text x="25" y="222" fill="#90bccd" font-size="10" font-weight="700">A</text><text x="25" y="${gy+55}" fill="#6feddd" font-size="10" font-weight="700">B</text><text x="320" y="${topEnd+24}" text-anchor="middle" class="svg-label" style="font-size:9px;fill:#f4cf91">FIN DE RUTA · TERMINAL DE RELIQUIAS</text><path d="M124 ${topEnd+9}H516" stroke="#b89660" stroke-width="2"/><text x="320" y="${gy-24}" text-anchor="middle" class="svg-label" style="fill:#6defd9">COMPUERTAS · ENTRADA FILA ${state.split+1}</text>`;
 for(let r=0;r<8;r++){const p=xy(E.at(r,0));a+=`<text x="102" y="${p.y+4}" text-anchor="end" class="svg-label" style="font-size:10px;fill:${r===state.split?'#82fbe3':'#8c9db7'}">${r+1}</text>`;}
 for(let c=0;c<6;c++){const x=160+c*64,accent=state.gates[c].mixed?'#ffd391':'#70d5d0';a+=`<g data-lane="${c}" class="gate" role="button" tabindex="0" aria-label="Inspeccionar carril ${c+1}"><rect x="${x-29}" y="${gy-13}" width="58" height="28" rx="5" fill="#172e3a" stroke="${accent}" stroke-width="${c===selectedLane?2:1}"/><path d="M${x-22} ${gy-8}h15v14h-15ZM${x+7} ${gy-8}h15v14h-15Z" fill="#4d6775"/><path d="M${x-6} ${gy-9}h12v17h-12" fill="#051b26" stroke="${accent}"/><path d="M${x-4} ${gy+5}l4 4 4-4" stroke="${accent}" stroke-width="1.5" fill="none"/><text x="${x+22}" y="${gy+8}" fill="${accent}" font-size="7" text-anchor="end">${state.gates[c].mixed?'✦':c+1}</text></g>`;
  for(const [py,label] of[[outY(),'P'+(c+1)+' ↓'],[inY(),'P'+(c+1)+' ↑']]){a+=`<g data-lane="${c}" class="gate"><ellipse cx="${x}" cy="${py}" rx="24" ry="8" fill="#171327" stroke="#bd8fff" stroke-width="2"/><ellipse cx="${x}" cy="${py}" rx="16" ry="3" fill="#9264eb" fill-opacity=".45"/><text x="${x}" y="${py===outY()?py-15:py+25}" text-anchor="middle" font-size="8" fill="#c5aff0" font-family="monospace">${label}</text></g>`;}
  a+=`<path d="M${x-13} ${topEnd}l4 5h18l4-5" stroke="#eac281" fill="#29293a"/>`;
 }
 a+=`<text x="320" y="844" text-anchor="middle" class="svg-label" style="font-size:9px">PORTALES · FILA 8 → FILA 1 · MISMA PIEZA</text></g><g id="queues">`;
 for(let c=0;c<6;c++){const x=160+c*64,g=state.gates[c];a+=`<g data-lane="${c}" class="gate"><text x="${x}" y="130" text-anchor="middle" font-size="8" fill="${g.mixed?'#f3cb8a':'#9eb8cf'}" font-family="monospace">G${c+1}${g.mixed?' ✦':''}</text>`;g.queue.forEach((p,i)=>{a+=tile(p,x+(i===1?-12:i===2?12:0),i===0?69:103,i===0?.53:.3);});a+='</g>';}
 a+='</g><g id="cells">';for(let i=0;i<48;i++){const p=xy(i),t=state.board[i];a+=`<g data-index="${i}" class="tile-hit" role="button" tabindex="${t?0:-1}" aria-label="Fila ${E.row(i)+1}, columna ${E.col(i)+1}: ${t?names[t.kind]+(t.kind==='normal'?' '+names[t.color]:''): 'vacío'}"><rect x="${p.x-29}" y="${p.y-29}" width="58" height="60" rx="9" fill="#070f2080" stroke="#30465f" stroke-width=".65"/>${tile(t,p.x,p.y)}<rect class="focus-ring" x="${p.x-30}" y="${p.y-30}" width="60" height="62" rx="10" fill="none" stroke="#fff" stroke-width="2" opacity="0"/></g>`;}
 return a+'</g><g id="preview" pointer-events="none"></g><g id="fx" pointer-events="none"></g>';
}
function svgIcon(kind,color='cyan'){return `<svg viewBox="-33 -33 66 66" aria-hidden="true">${tile({kind,color,hp:2,id:-2})}</svg>`;}
function render(){
 $('board').innerHTML=staticBoard();$('moves').textContent=state.moves;$('modeLabel').textContent=demoSnapshot?'DEMO DE FLUJO':busy?'RESOLVIENDO':'JUGAR';
 $('objectives').innerHTML=Object.entries(state.goals).map(([k,v])=>`<div class="obj ${v===0?'done':''}"><div class="oi" style="color:${palette[k]?.[0]||'#efc282'}">${k==='block'?'▧':k==='relic'?'◈':'◆'}</div><b>${v===0?'✓':v}</b><small>${k==='block'?'BLOQUES':k==='relic'?'RELIQUIAS':k==='cyan'?'CIAN':'ROSA'}</small><div class="progress"><i style="width:${100*(1-v/state.initialGoals[k])}%"></i></div></div>`).join('');
 $('laneButtons').innerHTML=Array.from({length:6},(_,c)=>`<button data-lane="${c}" class="${c===selectedLane?'active':''}" aria-label="Carril ${c+1}" aria-pressed="${c===selectedLane}">${c+1}</button>`).join('');
 const g=state.gates[selectedLane];$('laneCode').textContent=String(selectedLane+1).padStart(2,'0');$('gateName').textContent='Compuerta '+String(selectedLane+1).padStart(2,'0');$('gateBadge').textContent=g.mixed?'MIXTA':'NORMAL';$('gateBadge').className='tag'+(g.mixed?' gold':'');
 $('queueDetail').innerHTML=g.queue.map((p,i)=>`<div>${svgIcon(p.kind,p.color)}<small>${i+1} · ${p.kind==='normal'?names[p.color]:names[p.kind]}</small></div>`).join('');
 $('laneInfo').textContent=`G${selectedLane+1} → F${state.split+1} → F8 → P${selectedLane+1} → F1 → F${state.split}. `+(g.mixed?'Admite especiales anunciados.':'Solo suministro normal.');
 $('emitted').textContent=g.delivered;$('transferred').textContent=state.stats.portals;
 $('routeGate').textContent='Entrada en la fila '+(state.split+1);$('routeEnd').textContent='Final en la fila '+state.split;
 $('demo').innerHTML=demoSnapshot?'↩ Volver a la partida':'▷ Ver el recorrido';$('demoMobile').textContent=demoSnapshot?'↩ Volver a partida':'▷ Ver flujo';
 for(const id of['hint','undo','entry','mixed'])$(id).disabled=busy||!!demoSnapshot||(id==='undo'&&!history.length)||(id==='hint'&&state.status!=='playing');
 if(state.status!=='playing'&&!demoSnapshot&&!busy){$('result').hidden=false;$('result').innerHTML=`<div class="eyebrow">${state.status==='won'?'OBJETIVOS COMPLETADOS':'SIN MOVIMIENTOS'}</div><h2>${state.status==='won'?'Circuito restaurado.':'Una ruta más por descubrir.'}</h2><p>${state.status==='won'?'La energía llegó a su destino.':'Puedes deshacer la última jugada o reiniciar el nivel.'}</p><button class="button primary" data-restart>Volver a jugar</button>`;}else $('result').hidden=true;
}
function status(t){$('status').textContent=t;}
function sound(type){if(!audioEnabled)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime;const freq={pop:530,spawn:370,portal:720,seeker:1250,collect:1046,win:880}[type]||440;o.type=type==='seeker'?'triangle':'sine';o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(type==='portal'?1100:freq*.65,now+.15);g.gain.setValueAtTime(.035,now);g.gain.exponentialRampToValueAtTime(.001,now+.22);o.connect(g);g.connect(audio.destination);o.start();o.stop(now+.23);}catch(_){audioEnabled=false;}}
const lerp=(a,b,t)=>a+(b-a)*t,clamp=x=>Math.max(0,Math.min(1,x));
function animate(ms,draw,token){return new Promise(resolve=>{let last=0,age=0;function frame(t){if(token!==epoch){resolve(false);return;}if(last)age+=Math.min(t-last,60)*speed;last=t;const u=Math.min(1,age/ms);const fx=$('fx');if(fx)fx.innerHTML=draw(u);if(u<1)requestAnimationFrame(frame);else resolve(true);}requestAnimationFrame(frame);});}
function markHidden(indices){for(const i of indices){const n=$('board').querySelector(`[data-index="${i}"]`);if(n)n.style.opacity='.1';}}
function ring(p,t,color='#91f9dc',rad=40){return `<circle cx="${p.x}" cy="${p.y}" r="${8+t*rad}" fill="none" stroke="${color}" stroke-width="${3*(1-t)+.3}" opacity="${1-t}"/>`;}
function preview(i){hoverIndex=i;const node=$('preview');if(!node||busy||demoSnapshot){if(node)node.innerHTML='';return;}const t=state.board[i];if(!t){node.innerHTML='';return;}let ids=[],text='';if(t.kind==='normal'){ids=E.group(state,i);const k=E.recipe(ids.length);text=ids.length>=2?`${ids.length} tiles${k?' → '+names[k]:''}`:'Necesitas un grupo de 2 o más.';}
 else if(E.special(t.kind)){const j=E.partner(state,i);if(j>=0){const p=state.board[j];text=names[t.kind]+' + '+names[p.kind];ids=t.kind==='burst'&&p.kind==='burst'?E.area(i,'widecross',state):t.kind==='prism'||p.kind==='prism'?[i,j]:E.area(i,'cross',state);}else{ids=t.kind==='seeker'?[i]:t.kind==='prism'?state.board.flatMap((p,j)=>p?.kind==='normal'&&p.color===t.color?[j]:[]):E.area(i,t.kind,state);text=names[t.kind]+(t.kind==='seeker'?' · impacto estratégico':' · '+ids.length+' posiciones');}}
 else{text=t.kind==='block'?`${t.hp} impacto(s) · bloqueo fijo`:'Core Relic · llévala al terminal';ids=[i];}
 node.innerHTML=ids.map(j=>{const p=xy(j);return `<rect x="${p.x-30}" y="${p.y-30}" width="60" height="62" rx="9" stroke="#e6ffee" stroke-width="2" fill="#94fbe20c"/>`;}).join('');status(text);
}
async function phaseAnim(phase,token){const p=xy(phase.i);if(phase.kind==='seeker'&&phase.target&&phase.target.i>=0){const q=xy(phase.target.i);markHidden([phase.i]);$('seekerInfo').textContent=`F${E.row(phase.target.i)+1} · C${E.col(phase.target.i)+1}. ${phase.target.reason}`;status('Seeker: '+phase.target.reason);sound('seeker');
 return animate(760,t=>{const u=clamp((t-.16)/.75),bend=Math.sin(u*Math.PI)*65,x=lerp(p.x,q.x,u)+bend,y=lerp(p.y,q.y,u)-Math.sin(u*Math.PI)*55;return `<path d="M${p.x} ${p.y} Q${(p.x+q.x)/2+70} ${(p.y+q.y)/2-70} ${q.x} ${q.y}" stroke="#74e7e7" stroke-width="1" stroke-dasharray="4 5" opacity=".4" fill="none"/><circle cx="${q.x}" cy="${q.y}" r="${27+Math.sin(t*12)*2}" fill="none" stroke="#fbdf94" stroke-width="2" stroke-dasharray="10 5"/>${tile({kind:'seeker',color:'cyan',id:-1},x,y,.7)}${t>.82?ring(q,(t-.82)/.18):''}`;},token);}
 const label=phase.created?`${names[phase.created]} creado`:phase.kind==='match'?`${phase.hits.length} impactos`:phase.kind==='collect'?'Reliquia recuperada':phase.kind==='convert'?'Prism · conversión':names[phase.kind]||'COMBO';status(label);sound('pop');markHidden(phase.hits.filter(i=>state.board[i]?.kind!=='block'));
 return animate(phase.kind==='match'?220:330,t=>phase.hits.map(i=>ring(xy(i),t,phase.kind==='burst'?'#ffb994':'#75e8e0',34)).join('')+`<text x="320" y="${p.y-42-t*15}" text-anchor="middle" fill="#f0ffff" stroke="#071322" stroke-width="3" paint-order="stroke" font-weight="700" font-size="17" opacity="${1-t*.8}">${safe(label)}</text>`,token);
}
async function flow(token){for(let tick=0;tick<100;tick++){if(token!==epoch)return false;const next=E.clone(state),events=E.stepFlow(next);if(!events.length)return true;const hasPortal=events.some(e=>e.kind==='portal'),hasSpawn=events.some(e=>e.kind==='spawn'),hasCollect=events.some(e=>e.kind==='collect');
 markHidden(events.filter(e=>e.from>=0).map(e=>e.from));
 const tracked=events.find(e=>e.piece.id===trackingId);
 if(demoSnapshot){if(tracked)status(tracked.kind==='portal'?`La misma pieza cruza P${E.col(tracked.to)+1}: fila 8 → fila 1.`:tracked.kind==='spawn'?`Incoming → compuerta G${selectedLane+1} → fila ${state.split+1}.`:`Pieza trazada: fila ${E.row(tracked.from)+1} → fila ${E.row(tracked.to)+1}.`);else status(`Rellenando el carril ${selectedLane+1}; la compuerta espera cuando no hay espacio.`);}else if(hasCollect)status('Core Relic recuperada en el terminal.');else if(hasPortal)status('Transferencia 8 → 1 · misma pieza, sin duplicación.');else if(hasSpawn)status(`El incoming entra por la fila ${state.split+1}.`);
 if(hasCollect)sound('collect');else if(hasPortal)sound('portal');else if(hasSpawn&&tick%2===0)sound('spawn');
 const ok=await animate(hasPortal?450:hasSpawn?265:155,t=>events.map(e=>{const end=xy(e.to>=0?e.to:e.from),start=e.from>=0?xy(e.from):{x:160+e.lane*64,y:69};let x,y,z=1,alpha=1;
 if(e.kind==='fall'){const u=1-(1-t)**2;x=lerp(start.x,end.x,u);y=lerp(start.y,end.y,u);}
 else if(e.kind==='collect'){x=start.x;y=start.y+t*36;z=1-t;alpha=1-t;}
 else if(e.kind==='spawn'){x=end.x;if(t<.3){y=69+t*90;z=.5*(1-t/.3);alpha=1-t/.3;}else{x=end.x;y=lerp(gateY(),end.y,(t-.3)/.7);z=.4+.6*(t-.3)/.7;}return `<rect x="${end.x-28}" y="${gateY()-13}" width="56" height="28" rx="5" fill="${E.special(e.piece.kind)?'#ffd69b':'#71eddf'}" opacity="${Math.sin(t*Math.PI)*.5}"/>${tile(e.piece,x,y,z,alpha)}`;}
 else{if(t<.28){x=start.x;y=lerp(start.y,inY(),t/.28);z=1-t/.28*.86;}else if(t<.7){const u=(t-.28)/.42,side=E.col(e.from)<3?65-E.col(e.from)*16:575+(E.col(e.from)-3)*16;x=side;y=lerp(inY(),outY(),u);z=.13;}else{x=end.x;y=lerp(outY(),end.y,(t-.7)/.3);z=.15+.85*(t-.7)/.3;}return `<path d="${portalPath(E.col(e.to))}" stroke="#d0b6ff" stroke-width="2.5" fill="none" opacity="${Math.sin(t*Math.PI)*.8}"/>${tile(e.piece,x,y,z)}${ring({x:start.x,y:inY()},t,'#ba93ff',17)}${ring({x:end.x,y:outY()},t,'#ba93ff',17)}`;}
 return tile(e.piece,x,y,z,alpha);
 }).join(''),token);if(!ok)return false;state=next;render();}
 throw Error('El circuito no se estabilizó.');}
async function play(i){if(busy||demoSnapshot||state.status!=='playing')return false;const outcome=E.act(state,i);if(!outcome.ok){status(outcome.reason);return false;}history.push(E.clone(state));busy=true;const token=++epoch;render();try{for(const p of outcome.phases){if(!await phaseAnim(p,token))return false;state=E.clone(p.snapshot);render();}state=outcome.state;render();if(!await flow(token))return false;E.finish(state);if(state.status==='won'){status('Objetivos completados.');sound('win');}else if(state.status==='lost')status('No quedan taps. Puedes deshacer o reiniciar.');else status(E.legal(state).length?'Toca un grupo o activa un especial.':'Sin jugadas: deshaz o reinicia este prototipo.');return true;}catch(e){if(token===epoch){state=history.pop();status('La acción se revirtió: '+e.message);console.error(e);}return false;}finally{if(token===epoch){busy=false;render();}}}
async function demo(){if(demoSnapshot){epoch++;state=demoSnapshot;demoSnapshot=null;trackingId=-1;busy=false;render();status('Partida restaurada: taps, objetivos e incoming intactos.');return;}if(busy)return;demoSnapshot=E.clone(state);state=E.clone(state);state.status='playing';for(let r=0;r<8;r++)state.board[E.at(r,selectedLane)]=null;trackingId=state.gates[selectedLane].queue[0].id;busy=true;const token=++epoch;render();status('Demostración aislada: observa la pieza con contorno dorado.');try{await flow(token);if(token===epoch)status(`Circuito completo: ${E.route(state).map(r=>r+1).join(' → ')}. La pieza trazada no se duplicó.`);}catch(e){status(e.message);}finally{if(token===epoch){busy=false;render();}}}
function reset(){epoch++;demoSnapshot=null;trackingId=-1;busy=false;history=[];state=E.init({split:Number($('entry').value),mixed:$('mixed').checked});$('seekerInfo').textContent='Al lanzar un dron verás aquí el destino elegido y su motivo.';render();status(state.split===4?'Toca el grupo de 4 amarillos para crear tu primer Seeker.':`Entrada por fila ${state.split+1}. Toca un grupo o activa un especial.`);}
function undo(){if(busy||demoSnapshot||!history.length)return;epoch++;state=history.pop();render();status('Jugada deshecha. Incoming y contadores restaurados.');}
function selectLane(c){if(!Number.isInteger(c)||c<0||c>5||busy||demoSnapshot)return;selectedLane=c;render();}
$('board').addEventListener('click',e=>{const cell=e.target.closest('[data-index]'),lane=e.target.closest('[data-lane]');if(cell)play(Number(cell.dataset.index));else if(lane)selectLane(Number(lane.dataset.lane));});
$('board').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){const cell=e.target.closest('[data-index]'),lane=e.target.closest('[data-lane]');if(cell||lane){e.preventDefault();if(cell)play(Number(cell.dataset.index));else selectLane(Number(lane.dataset.lane));}}});
$('board').addEventListener('pointerover',e=>{if(e.pointerType==='touch')return;const cell=e.target.closest('[data-index]');if(cell)preview(Number(cell.dataset.index));});
$('board').addEventListener('pointerleave',()=>{if($('preview'))$('preview').innerHTML='';});
$('laneButtons').addEventListener('click',e=>{const b=e.target.closest('[data-lane]');if(b)selectLane(Number(b.dataset.lane));});
$('demo').onclick=demo;$('demoMobile').onclick=demo;$('reset').onclick=reset;$('undo').onclick=undo;
$('entry').onchange=reset;$('mixed').onchange=reset;$('routes').onchange=e=>{routes=e.target.checked;if(!busy)render();};
$('speed').oninput=e=>{speed=Number(e.target.value);$('speedValue').textContent=speed.toFixed(1).replace('.0','')+'×';};
$('hint').onclick=()=>{if(busy||demoSnapshot)return;const h=E.hint(state);if(h){preview(h.i);status(`Sugerencia: fila ${E.row(h.i)+1}, columna ${E.col(h.i)+1}. Toca la pieza resaltada.`);}else status('No quedan jugadas legales: deshaz o reinicia.');};
$('sound').onclick=()=>{audioEnabled=!audioEnabled;$('sound').setAttribute('aria-pressed',String(audioEnabled));$('sound').textContent=audioEnabled?'♫ Audio ON':'♫ Audio';if(audioEnabled)sound('spawn');};
$('help').onclick=()=>$('instructions').showModal();$('closeHelp').onclick=()=>$('instructions').close();
$('result').onclick=e=>{if(e.target.closest('[data-restart]'))reset();};
$('export').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(E.config(state),null,2)],{type:'application/json'}));a.href=url;a.download='novapop-flow-lab-level.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
// Small deterministic API for browser verification; not connected to any account.
window.__FLOW_LAB__={getState:()=>E.clone(state),isBusy:()=>busy,isDemo:()=>!!demoSnapshot,play,reset,undo,demo,selectLane,instantPlay:i=>{if(busy||demoSnapshot)return false;const r=E.act(state,i);if(!r.ok)return false;history.push(E.clone(state));state=r.state;E.settle(state);E.finish(state);render();return true;}};
render();
})();
