'use strict';
const assert=require('node:assert/strict');const E=require('./engine.js');let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
function valid(s){const ids=s.board.filter(Boolean).map(x=>x.id),all=ids.concat(...s.gates.map(g=>g.queue.map(x=>x.id)));assert.equal(new Set(all).size,all.length);assert.equal(s.board.filter(Boolean).length,48+s.stats.spawned+s.stats.created-s.stats.removed-s.stats.collected);assert(s.goals.relic>=0&&s.moves>=0);}
test('Recipes 2,3,4,5,6,7,8,9,12',()=>assert.deepEqual([2,3,4,5,6,7,8,9,12].map(E.recipe),[null,null,'seeker','slash','beam','burst','burst','prism','prism']));
test('Entry always below first row; paths contain 8 unique rows',()=>{for(const split of[3,4,5]){let s=E.init({split});assert.equal(new Set(E.route(s)).size,8);assert.equal(E.route(s)[0],split);assert.equal(E.route(s).at(-1),split-1);assert.equal(s.board.filter(p=>p.kind==='relic').length,2);valid(s);}});
test('No movement, spawning or cursor changes on a settled board',()=>{const s=E.init(),copy=E.clone(s);assert.deepEqual(E.stepFlow(s),[]);assert.deepEqual(s,copy);});
test('Flow moves only one edge per tick and retains portal identity',()=>{const s=E.init();s.board.fill(null);s.gates.forEach(g=>g.queue=[]);const p={kind:'prism',color:'pink',id:999,hp:0};s.board[42]=p;const e=E.stepFlow(s,false);assert.equal(e[0].kind,'portal');assert.equal(s.board[0],p);assert.equal(s.board[6],null);assert.equal(s.stats.spawned,0);});
test('Eight deliveries fill a cleared lane with four portal crossings',()=>{const s=E.init(),c=1,first=s.gates[c].queue[0].id;for(let r=0;r<8;r++)s.board[E.at(r,c)]=null;E.settle(s);assert.equal(s.stats.spawned,8);assert.equal(s.stats.portals,4);assert.equal(s.board[E.at(3,c)].id,first);assert.equal(new Set(s.board.filter(Boolean).map(p=>p.id)).size,48);assert.deepEqual(E.stepFlow(s),[]);});
test('Four normal tiles create one Seeker and consume one tap',()=>{const s=E.init(),before=E.clone(s),r=E.act(s,24);assert(r.ok);assert.equal(r.state.moves,25);assert.equal(r.state.board[24].kind,'seeker');assert.equal(r.state.stats.created,1);assert.deepEqual(s,before);E.settle(r.state);valid(r.state);});
test('Groups do not cross the segment border',()=>{const s=E.init();s.board[18].color=s.board[24].color='cyan';assert(!E.group(s,18).includes(24));});
test('Seeker evaluates deterministically without changing live state or RNG',()=>{const s=E.init();s.board[35]=null;const before=E.clone(s);assert.deepEqual(E.target(s),E.target(s));assert.deepEqual(s,before);assert.notEqual(s.board[E.target(s).i].kind,'relic');});
test('Seeker launch does not destroy any relic and has one initial impact',()=>{const s=E.init(),r=E.act(s,35);assert(r.ok);assert.equal(r.phases[0].kind,'seeker');assert.equal(r.phases[0].hits.length,1);assert.equal(r.state.board.filter(p=>p?.kind==='relic').length,2);assert.equal(r.state.moves,25);});
test('Relics collect exactly once only at the terminal',()=>{const s=E.init();s.board.fill(null);s.gates.forEach(g=>g.queue=[]);s.board[18]={kind:'relic',color:'cyan',id:555,hp:0};E.stepFlow(s,false);assert.equal(s.goals.relic,1);E.stepFlow(s,false);assert.equal(s.goals.relic,1);});
test('An incoming special does not auto-activate when emitted',()=>{const s=E.init();s.board[25]=null;const next=s.gates[1].queue[0];assert.equal(next.kind,'seeker');E.stepFlow(s);assert.equal(s.board[25].id,next.id);assert.equal(s.board[25].kind,'seeker');});
test('Prism stores its normal origin color and leaves relics alone',()=>{const s=E.init();s.board[0].kind='prism';s.board[1].kind='normal';s.board[6].kind='normal';s.board[6].color='orange';const r=E.act(s,0);assert(r.ok);assert(r.state.board.every(p=>!p||p.kind!=='normal'||p.color!=='cyan'));assert.equal(r.state.board.filter(p=>p?.kind==='relic').length,2);});
test('All supported layouts: random legal sequences conserve pieces',()=>{let steps=0;for(const split of[3,4,5])for(let seed=1;seed<=12;seed++){let s=E.init({split,seed});for(let n=0;n<26;n++){const l=E.legal(s);if(!l.length)break;const i=l[(seed*37+n*11)%l.length],r=E.act(s,i);assert(r.ok);s=r.state;E.settle(s);E.finish(s);valid(s);steps++;if(s.status!=='playing')break;}}console.log('  random actions '+steps);});
test('Default level is winnable with the built-in local hint evaluator',()=>{let s=E.init(),path=[];for(let n=0;n<26&&s.status==='playing';n++){const h=E.hint(s);assert(h);path.push(h.i);s=E.act(s,h.i).state;E.settle(s);E.finish(s);valid(s);}assert.equal(s.status,'won');console.log('  winning path '+JSON.stringify(path));});
console.log(count+' tests passed.');
