'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'premium-one-fullscreen.css'),'utf8');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
assert(!html.includes('class="lane-label"'),'Sender labels must not cover optical cells');
assert(css.includes('.lane-label{display:none!important}'),'Cached HTML must also hide lane labels');
assert(!/\.data-live\s+\.(stage-hud|stage-controls|triframe-grid|optical-frame)\s*\{/.test(css),'HELLO and DATA must not change optical geometry or overlay controls');
assert(css.includes('height:calc(52px + var(--safe-top))'));
assert(css.includes('height:calc(52px + var(--safe-bottom))'));
assert(css.includes('.stage-controls [hidden]{display:none!important}'));
assert.equal((html.match(/id="stageDockCanvas"/g)||[]).length,1,'Atomic canonical dock canvas');
require('../anchor-scan.js');
assert.deepEqual(global.HopperAnchorScan.LANE_Y,[22,65,108],'Three actual vertically stacked payload regions');
assert.equal(global.HopperAnchorScan.COLS,60);assert.equal(global.HopperAnchorScan.ROWS,36);
assert(css.includes('object-fit:contain'),'Do not stretch corner tags');
const cssPath='premium-one-fullscreen.css?v=1500';
assert(html.includes(cssPath)&&sw.includes(cssPath),'HTML and offline cache must load the fixed CSS');
assert(html.includes('Pantalla limpia'));
assert(sw.includes('hopperlink-one-v1500'));
assert(sw.includes('./hopper-one.js?v=1500'));
assert(sw.includes('./runtime/hopper-one.bundle-01.txt?v=1500'));
console.log('Unobstructed optical surface / stable HELLO-DATA geometry contract: PASS');
